"""Build the Snowsight deploy bundle (backend/sql/deploy/) from the repo SQL so it cannot drift.

    ./venv/bin/python -m backend.scripts.build_deploy_bundle          # rewrite the bundle
    ./venv/bin/python -m backend.scripts.build_deploy_bundle --check  # exit 1 if it is stale

Each numbered file is a plain concatenation of the exact current repo SQL (plus a context header
and a read-only verification block) sized for one Snowsight worksheet "Run all". Nothing here
connects to Snowflake, reads credentials, or includes setup.sql (its tables/20_core.sql drops CORE
tables). Generated cohort-document MERGEs come from data/generated/cohort_document_manifest.json
and the synthetic PDFs, via backend.scripts.prepare_synthetic_documents (pure SQL, no PUT).
Every statement is `unverified-needs-deploy` until a human runs it; engineering checks on
synthetic data, not clinical validation.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SQL = REPO / "backend/sql"
OUT = SQL / "deploy"
MANIFEST = REPO / "data/generated/cohort_document_manifest.json"
PDF_DIR = REPO / "data/generated/pdf/cohort"

HEADER = """-- {name}: {title}
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;
"""

FORBIDDEN = ("setup.sql",)  # never bundled: drops CORE tables


def _read(rel: str) -> str:
    assert not rel.endswith(FORBIDDEN), rel
    return (SQL / rel).read_text()


def _file(rel: str) -> str:
    text = _read(rel)
    return f"-- ===== BEGIN {rel} =====\n{text.rstrip()}\n-- ===== END {rel} =====\n"


def _slice(rel: str, start: str, end: str, include_end: bool = False) -> str:
    text = _read(rel)
    a = text.index(start)
    b = text.index(end, a) + (len(end) if include_end else 0)
    return f"-- ===== BEGIN {rel} (section) =====\n{text[a:b].rstrip()}\n-- ===== END {rel} =====\n"


def _split_at(rel: str, marker: str) -> tuple[str, str]:
    """Return (text before marker, text from marker on) as two labelled sections of one repo file."""
    text = _read(rel)
    i = text.index(marker)
    return (f"-- ===== BEGIN {rel} (procedure part) =====\n{text[:i].rstrip()}\n-- ===== END {rel} (procedure part) =====\n",
            f"-- ===== BEGIN {rel} (task part) =====\n{text[i:].rstrip()}\n-- ===== END {rel} (task part) =====\n")


def _grants() -> tuple[str, str]:
    """03_grants.sql split so the unconditional grants run first and the AGENT/MCP grants are guarded."""
    text = _read("governance/03_grants.sql")
    marker = "-- Agent + MCP server access."
    i = text.index(marker)
    main = f"-- ===== BEGIN governance/03_grants.sql (section) =====\n{text[:i].rstrip()}\n-- ===== END governance/03_grants.sql (section) =====\n"
    comment = text[i:text.index("REVOKE USAGE ON AGENT")].rstrip()
    guarded = [f"-- ===== BEGIN governance/03_grants.sql (agent/mcp, guarded) =====\n{comment}\n"
               "-- N4-01: the bundle does not create the agent or the MCP server. A missing object must not stop\n"
               "-- Run all; the block returns 'skipped ...' (read the result) and the grant is re-run after the object exists.\n"]
    for kind, name in (("AGENT", "SAARTHI_AGENT"), ("MCP SERVER", "SAARTHI_MCP")):
        verb, direction = ("REVOKE", "FROM") if kind == "AGENT" else ("GRANT", "TO")
        guarded.append(
            "EXECUTE IMMEDIATE $$\nBEGIN\n"
            f"    {verb} USAGE ON {kind} SAARTHI.OPERATIONAL.{name} "
            f"{direction} ROLE SAARTHI_APP;\n"
            f"    RETURN '{verb.lower()}: {name}';\nEXCEPTION\n    WHEN OTHER THEN\n"
            f"        RETURN 'skipped {name} (object absent or not grantable): ' || SQLERRM;\nEND;\n$$;\n")
    guarded.append("-- ===== END governance/03_grants.sql (agent/mcp, guarded) =====\n")
    return main, "\n".join(guarded)


def _generated_documents() -> str:
    from backend.scripts.prepare_synthetic_documents import prepare
    if not MANIFEST.exists():
        raise SystemExit("missing data/generated/cohort_document_manifest.json: run "
                         "`./venv/bin/python -m data.generator.cohort_documents --manifest "
                         "data/generated/cohort_document_manifest.json`")
    records = json.loads(MANIFEST.read_text())
    sql = prepare(records, PDF_DIR)
    # prepare() emits its own USE ROLE header; the bundle header already sets context.
    body = "\n".join(line for line in sql.splitlines()
                     if not line.startswith(("USE ROLE", "USE SECONDARY", "-- Synthetic cohort")))
    digest = hashlib.sha256(MANIFEST.read_bytes()).hexdigest()[:12]
    return (f"-- ===== BEGIN generated cohort documents ({len(records)} documents, manifest sha256 "
            f"{digest}) =====\n{body}\n-- ===== END generated cohort documents =====\n")


SKILLS_DIR = REPO / "backend/skills"
SKILLS_SQL = SKILLS_DIR / "upload_skills.sql"
SKILL_NAMES = ("clinical-question-routing", "evidence-retrieval", "risk-stratification", "evidence-reconciliation")


def skills_upload_sql() -> str:
    """One COPY INTO per SKILL.md (SINGLE file, no PUT, so deployment stays reproducible from SQL alone).

    Markdown is embedded as a single-quoted literal (backslash and quote escaped) so the same text can be pasted
    into a worksheet. Never executed against Snowflake in this repo: `unverified-needs-deploy`.
    """
    out = ["-- GENERATED by backend/scripts/build_deploy_bundle.py from backend/skills/*/SKILL.md. Do not edit; rebuild instead.",
           "-- Loads the 4 skill definitions to @SAARTHI.STAGES.SKILLS/<skill-name>/SKILL.md. The agent references the FOLDER, not the file.",
           "-- Status: unverified-needs-deploy (COPY INTO ... SINGLE=TRUE path behaviour not yet run on this account).", ""]
    for name in SKILL_NAMES:
        text = (SKILLS_DIR / name / "SKILL.md").read_text()
        assert "$$" not in text, name
        lit = text.replace("\\", "\\\\").replace("'", "''")
        out.append(f"COPY INTO @SAARTHI.STAGES.SKILLS/{name}/SKILL.md\nFROM (SELECT '{lit}')\n"
                   "FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, RECORD_DELIMITER = NONE, FIELD_DELIMITER = NONE)\n"
                   "SINGLE = TRUE OVERWRITE = TRUE;\n")
    out.append("-- VERIFY: expect 4 files, one per skill folder.\nLIST @SAARTHI.STAGES.SKILLS;\n")
    return "\n".join(out)


def _semantic_view_guarded() -> str:
    """The view is created inside a handler: a rejected AI_VERIFIED_QUERIES / AI_QUESTION_CATEGORIZATION clause
    (syntax not yet run live) must not stop Run all; the previous view stays in place and the result says so."""
    text = _read("semantic/01_semantic_view.sql")
    stmt = text[text.index("CREATE OR REPLACE SEMANTIC VIEW"):].rstrip()
    assert "$$" not in stmt
    return ("-- ===== BEGIN semantic/01_semantic_view.sql (guarded) =====\n"
            "EXECUTE IMMEDIATE $$\nBEGIN\n" + stmt + "\n"
            "    RETURN 'created: SAARTHI_SEMANTIC_VIEW (with 7 verified queries)';\nEXCEPTION\n    WHEN OTHER THEN\n"
            "        RETURN 'skipped SAARTHI_SEMANTIC_VIEW (previous view kept; clause syntax unverified): ' || SQLERRM;\nEND;\n$$;\n"
            "-- ===== END semantic/01_semantic_view.sql (guarded) =====\n")


def _verify_procs(names: list[str]) -> str:
    listed = ", ".join(f"'{n.upper()}'" for n in names)
    return ("-- VERIFY: expect one row per name, CREATED just now.\n"
            "SELECT procedure_name, created FROM SAARTHI.INFORMATION_SCHEMA.PROCEDURES\n"
            f" WHERE procedure_schema = 'OPERATIONAL' AND procedure_name IN ({listed})\n"
            f" ORDER BY 1;  -- expect {len(set(names))} rows\n")


SUSPEND_ROOT = """-- N4-01: EXECUTED (not commented). A started task graph makes CREATE OR REPLACE TASK on a child fail.
-- IF EXISTS plus the handler make this a no-op on a fresh account. Resume is a deliberate manual step (step 08 tail).
EXECUTE IMMEDIATE $$
BEGIN
    ALTER TASK IF EXISTS SAARTHI.OPERATIONAL.TASK_PARSE_DOCUMENTS SUSPEND;
    RETURN 'TASK_PARSE_DOCUMENTS suspended (or absent)';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'task suspend skipped: ' || SQLERRM;
END;
$$;
"""

DETACH_RAP = """-- N4-02: DOC_PAGE is MERGEd below. A MERGE target scan is filtered by the row access policy, so under the
-- policy an existing page can be invisible to the running user and a re-run would insert a duplicate. The
-- policy is therefore detached here (nothing to detach on a fresh account) and re-attached by step 07.
-- IF THIS STEP FAILS PART WAY: run step 07 again BEFORE anything else (step 08/09 also refuse to run
-- while DOC_PAGE has no PATIENT_SCOPE policy).
EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE SAARTHI.DOCUMENTS.DOC_PAGE DROP ROW ACCESS POLICY SAARTHI.GOVERNANCE.patient_scope;
    RETURN 'detached';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'nothing to detach';
END;
$$;
"""

GUARD_RAP = """-- GUARD (fail closed): DOC_PAGE must carry PATIENT_SCOPE. If not, run step 07 again before anything else.
EXECUTE IMMEDIATE $$
DECLARE
    rap_missing EXCEPTION (-20010, 'DOC_PAGE has no PATIENT_SCOPE row access policy. Run step 07 (04 failure path) again before anything else.');
    n INTEGER;
BEGIN
    SELECT COUNT(*) INTO :n
      FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'))
     WHERE ref_entity_name = 'DOC_PAGE';
    IF (n = 0) THEN
        RAISE rap_missing;
    END IF;
    RETURN 'ok: PATIENT_SCOPE is attached to DOC_PAGE';
END;
$$;
"""

GUARD_PIPELINE = """-- GUARD (fail closed, N4-02/N4-06): the pipeline reads DOC_PAGE through the row access policy as the CURRENT user.
-- It must run as the Snowflake user stored on PRAC-01, the procedures must exist, and the cohort pages must be
-- visible. Otherwise the CALLs below would see nothing and report success.
EXECUTE IMMEDIATE $$
DECLARE
    not_prac01 EXCEPTION (-20011, 'Current user is not the snowflake_user on PRAC-01: the row access policy hides every page from this user. UPDATE SAARTHI.GOVERNANCE.PRACTITIONER SET snowflake_user = <this user> WHERE practitioner_id = PRAC-01 (and ensure the care-team links exist), or run as that user.');
    no_pages EXCEPTION (-20012, 'Cohort documents (DOC-LAB-DC-*, DOC-PATH-DC-*) have no VISIBLE DOC_PAGE rows for this user: run steps 05-06 first, and run as the PRAC-01 user.');
    procs_missing EXCEPTION (-20013, 'A pipeline procedure is missing (parse_documents_proc, chunk_documents_proc, extract_assertions_proc, reconcile_evidence_proc, refresh_readiness_proc). Deploy it from backend/sql/tasks and backend/sql/procedures first.');
    rap_missing EXCEPTION (-20010, 'DOC_PAGE has no PATIENT_SCOPE row access policy. Run step 07 again before anything else.');
    n INTEGER;
BEGIN
    SELECT COUNT(*) INTO :n
      FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'))
     WHERE ref_entity_name = 'DOC_PAGE';
    IF (n = 0) THEN
        RAISE rap_missing;
    END IF;
    SELECT COUNT(*) INTO :n FROM SAARTHI.GOVERNANCE.PRACTITIONER
     WHERE practitioner_id = 'PRAC-01' AND snowflake_user = CURRENT_USER();
    IF (n = 0) THEN
        RAISE not_prac01;
    END IF;
    SELECT COUNT(DISTINCT procedure_name) INTO :n FROM SAARTHI.INFORMATION_SCHEMA.PROCEDURES
     WHERE procedure_schema = 'OPERATIONAL'
       AND procedure_name IN ('PARSE_DOCUMENTS_PROC', 'CHUNK_DOCUMENTS_PROC', 'EXTRACT_ASSERTIONS_PROC',
                              'RECONCILE_EVIDENCE_PROC', 'REFRESH_READINESS_PROC');
    IF (n < 5) THEN
        RAISE procs_missing;
    END IF;
    SELECT COUNT(*) INTO :n FROM SAARTHI.DOCUMENTS.DOCUMENT d
     WHERE (d.doc_id LIKE 'DOC-LAB-DC-%' OR d.doc_id LIKE 'DOC-PATH-DC-%')
       AND NOT EXISTS (SELECT 1 FROM SAARTHI.DOCUMENTS.DOC_PAGE p WHERE p.doc_id = d.doc_id);
    IF (n > 0) THEN
        RAISE no_pages;
    END IF;
    RETURN 'ok: pipeline preconditions hold';
END;
$$;
"""

RAP_CANARY = """-- N4-03 canary: a synthetic patient-scope document whose patient is on NO care team, so no user may ever see its page.
-- Inserted BEFORE the policy is attached (an INSERT is not filtered, a guarded re-run never needs to see the page:
-- the DOCUMENT row, which has no policy, is the idempotency key). Excluded from the verification counts by name.
EXECUTE IMMEDIATE $$
BEGIN
    IF (NOT EXISTS (SELECT 1 FROM SAARTHI.DOCUMENTS.DOCUMENT WHERE doc_id = 'DOC-RAP-CANARY-01')) THEN
        INSERT INTO SAARTHI.DOCUMENTS.DOCUMENT (doc_id, patient_id, scope, doc_type, version, ingested_at, ingestion_method, status)
        VALUES ('DOC-RAP-CANARY-01', 'PAT-RAP-CANARY', 'patient', 'rap_canary', 1, CURRENT_TIMESTAMP(), 'digital_emr', 'duplicate');
        INSERT INTO SAARTHI.DOCUMENTS.DOC_PAGE (doc_id, page_index, text, char_count)
        VALUES ('DOC-RAP-CANARY-01', 0, 'SYNTHETIC RAP CANARY. No care team may read this page.', 53);
        RETURN 'canary inserted';
    END IF;
    RETURN 'canary already present';
END;
$$;
"""

RAP_NEGATIVE = """-- N4-03 cross-patient negative test (fail closed). The canary page belongs to a patient nobody is on the care
-- team of, so the policy must hide it. PASS: this returns 0 rows, and the block below does not raise.
SELECT doc_id, page_index FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-RAP-CANARY-01';  -- expect 0 rows
EXECUTE IMMEDIATE $$
DECLARE
    rap_leak EXCEPTION (-20020, 'FAIL CLOSED: the DOC_PAGE canary page of a patient with no care team is VISIBLE. patient_scope is not filtering (name-binding or attach fault). Do not run steps 08/09; fix 01_policies.sql and re-run step 07.');
    n INTEGER;
BEGIN
    SELECT COUNT(*) INTO :n FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-RAP-CANARY-01';
    IF (n > 0) THEN
        RAISE rap_leak;
    END IF;
    RETURN 'ok: canary page hidden by patient_scope';
END;
$$;
-- Positive control: a patient the running user IS on the care team of must stay visible (1 row, if you are the PRAC-01 user).
SELECT COUNT(*) AS own_patient_pages_visible FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-SURG-NOTE-01';
"""

PREFLIGHT = """-- Read-only EXCEPT the one guarded task suspend at the end. Record the output; compare after step 9.
SELECT CURRENT_ROLE() AS role, CURRENT_SECONDARY_ROLES() AS secondary_roles;  -- ACCOUNTADMIN, none
DESC STAGE SAARTHI.STAGES.PATIENT_DOCS;  -- property "ENCRYPTION" / TYPE must be SNOWFLAKE_SSE (AGENTS.md 3.7)
SHOW TASKS IN SCHEMA SAARTHI.OPERATIONAL;  -- note which are "started" BEFORE the suspend below
SELECT patient_id, COUNT(*) AS documents FROM SAARTHI.DOCUMENTS.DOCUMENT GROUP BY 1 ORDER BY 1;  -- baseline
SELECT COUNT(*) AS patients_present FROM SAARTHI.CORE.PATIENT
 WHERE patient_id = 'PAT-DEEP-0001' OR patient_id LIKE 'PAT-DC-%';  -- if 12, step 7 (cohort) may be skipped
SELECT verification_status, missingness_state, COUNT(*) AS n
  FROM SAARTHI.EVIDENCE.ASSERTION GROUP BY 1, 2 ORDER BY 1, 2;  -- baseline
-- N4-06: procedures that the web and step 08 depend on but this bundle does not create (earlier rounds / setup.sql).
-- PASS: 0 rows. Any row = deploy that procedure from the repo first (backend/sql/procedures, tasks, agent).
SELECT n.name AS missing_procedure
  FROM (SELECT column1 AS name FROM VALUES ('RELEASE_PATIENT_BINDING'), ('ASK_SAARTHI'), ('PARSE_DOCUMENTS_PROC'),
                                           ('CHUNK_DOCUMENTS_PROC'), ('EXTRACT_ASSERTIONS_PROC'), ('REFRESH_READINESS_PROC')) n
  LEFT JOIN SAARTHI.INFORMATION_SCHEMA.PROCEDURES p
    ON p.procedure_schema = 'OPERATIONAL' AND p.procedure_name = n.name
 WHERE p.procedure_name IS NULL;  -- expect 0 rows
""" + SUSPEND_ROOT

VERIFY = GUARD_RAP + """-- All read-only. QUERY_HISTORY is live; ACCESS_HISTORY lags up to 180 minutes (do not mix them up).
-- 1. Documents per patient. PASS: all 12 patients appear. PAT-DC-01..11 carry the manifest documents
--    (16 documents over 11 patients in total, 5 patients with a pathology report). PAT-DEEP-0001 carries
--    DOC-SURG-NOTE-01 (1 page, synthetic), DOC-DUP-ORIG-01, DOC-DUP-COPY-01 (status duplicate), DOC-INJECT-01.
SELECT patient_id, COUNT(*) AS documents, COUNT_IF(status = 'active') AS active
  FROM SAARTHI.DOCUMENTS.DOCUMENT WHERE scope = 'patient' AND doc_id NOT LIKE 'DOC-RAP-CANARY%' GROUP BY 1 ORDER BY 1;
-- 2. Pages. PASS: every manifest and seeded document that has text has a non-empty page; empty = 0 for the 16 manifest docs.
SELECT d.doc_id, COUNT(p.page_index) AS pages, COUNT_IF(p.char_count > 0) AS non_empty
  FROM SAARTHI.DOCUMENTS.DOCUMENT d LEFT JOIN SAARTHI.DOCUMENTS.DOC_PAGE p ON p.doc_id = d.doc_id
 WHERE d.scope = 'patient' AND d.doc_id NOT LIKE 'DOC-RAP-CANARY%' GROUP BY 1 ORDER BY 1;
-- 2b. Duplicate pages (N4-02). PASS: 0 rows.
SELECT doc_id, page_index, COUNT(*) AS n FROM SAARTHI.DOCUMENTS.DOC_PAGE GROUP BY 1, 2 HAVING COUNT(*) > 1;
-- 3. Assertions by status (R7). The counts depend on live model output, so the criterion is an invariant, not a number:
SELECT verification_status, missingness_state, COUNT(*) AS n
  FROM SAARTHI.EVIDENCE.ASSERTION GROUP BY 1, 2 ORDER BY 1, 2;
--    PASS: this returns 0 rows (a verified assertion needs two agreeing passes (NULL = NULL is fine for
--    pending/unreadable) and a source span):
SELECT assertion_id, doc_id FROM SAARTHI.EVIDENCE.ASSERTION
 WHERE verification_status = 'verified'
   AND (pass1_value IS DISTINCT FROM pass2_value OR char_start IS NULL OR char_end IS NULL);
--    PASS: DOC-SURG-NOTE-01 assertions are not 'verified' until the two-pass run has read the page:
SELECT assertion_id, verification_status, missingness_state FROM SAARTHI.EVIDENCE.ASSERTION
 WHERE doc_id = 'DOC-SURG-NOTE-01' ORDER BY 1;
-- 4. Evidence links. PASS: relation 'supports' rows exist once the pipeline has verified numeric lab assertions.
SELECT relation, COUNT(*) AS n FROM SAARTHI.EVIDENCE.EVIDENCE_LINK GROUP BY 1 ORDER BY 1;
-- 5. Gates per patient. PASS: all 12 patients have rows and with_evidence >= 1 (gates cite structured event,
--    coverage, authorization or verified-assertion ids). A patient with with_evidence = 0 is a failure to investigate.
--    Gates with no inputs legitimately keep an empty evidence_ids; those are listed by the second query.
SELECT patient_id, COUNT(*) AS gates, COUNT_IF(ARRAY_SIZE(evidence_ids) > 0) AS with_evidence,
       COUNT_IF(ARRAY_SIZE(evidence_ids) = 0) AS empty
  FROM SAARTHI.OPERATIONAL.READINESS_STATE GROUP BY 1 ORDER BY 1;
SELECT patient_id, rule_id, outcome, reason FROM SAARTHI.OPERATIONAL.READINESS_STATE
 WHERE ARRAY_SIZE(evidence_ids) = 0 ORDER BY 1, 2;
-- 6. Objects. PASS: DT_SCHEME_ELIGIBILITY refresh_mode = FULL; RAP attached to DOC_PAGE only.
SHOW DYNAMIC TABLES LIKE 'DT_SCHEME_ELIGIBILITY' IN SCHEMA SAARTHI.OPERATIONAL;
SELECT policy_name, ref_entity_name, ref_entity_domain FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(
  POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'));
--    Cross-patient negative test (N4-03). PASS: 0 rows (the canary page belongs to a patient with no care team):
SELECT doc_id, page_index FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-RAP-CANARY-01';
-- 7. Tasks stay as the checklist recorded them (re-created tasks are SUSPENDED).
SHOW TASKS IN SCHEMA SAARTHI.OPERATIONAL;
-- 8. Timeline/labs state rule (N3-01) is checked in the app, not here (the procedure binds on the caller):
--    /patient/PAT-DC-01 timeline shows the diagnosis event as "Present", never "Not received".
"""

PIPELINE = GUARD_PIPELINE + """-- Run each CALL on its own, in order. Spends Cortex credits (two model families, R7). Paste, then run
-- statement by statement (Run, not Run all): extract_assertions_proc handles a bounded batch per call.
CALL SAARTHI.OPERATIONAL.chunk_documents_proc();
CALL SAARTHI.OPERATIONAL.extract_assertions_proc();  -- REPEAT until it reports nothing pending
CALL SAARTHI.OPERATIONAL.extract_assertions_proc();
CALL SAARTHI.OPERATIONAL.reconcile_evidence_proc();
CALL SAARTHI.OPERATIONAL.refresh_readiness_proc();
-- If TASK_PARSE_DOCUMENTS was started in the preflight, re-enable the graph afterwards:
-- SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('SAARTHI.OPERATIONAL.TASK_PARSE_DOCUMENTS');
"""


PARSE_COLUMN = """-- Round 6 (task dedupe): parse_documents_proc keys on DOCUMENT.source_path (stable stage path), not on etag.
-- ADD COLUMN IF NOT EXISTS is additive; no table is dropped. TASK_PARSE_DOCUMENTS itself is NOT re-created here
-- (it names EXECUTE AS USER SITAR, an account-specific user); it stays suspended.
ALTER TABLE SAARTHI.DOCUMENTS.DOCUMENT ADD COLUMN IF NOT EXISTS source_path VARCHAR;
"""


def steps() -> list[tuple[str, str, list[str]]]:
    web_names = ["GET_WEB_WORKSPACE", "GET_WEB_PATIENT_DATA", "UPDATE_WEB_REVIEW_TASK",
                 "REFRESH_BOUND_READINESS", "RECORD_WEB_ANSWER", "PREPARE_WEB_PACKET"]
    tool_names = ["get_patient_facts", "get_readiness", "search_patient_documents", "get_timeline",
                  "get_changes", "create_review_task", "bind_patient", "evaluate_gates",
                  "EXTRACT_ONE_DOCUMENT", "validate_answer", "ASK_SAARTHI",
                  "ANSWER_GATEWAY_CANDIDATES", "ANSWER_GATEWAY_REFERENCE", "ANSWER_GATEWAY_RECORD",
                  "ANSWER_GATEWAY_RULE",
                  "ANSWER_GATEWAY_RESOLVE_IDS",
                  "ANSWER_GATEWAY_REFUSAL", "ANSWER_GATEWAY_FINALIZE",
                  "ANSWER_GATEWAY_RECORD_FALLBACK"]
    rec_proc, rec_task = _split_at("tasks/reconcile_evidence.sql", "CREATE OR REPLACE TASK")
    orch_proc, orch_task = _split_at("tasks/orchestrator.sql", "CREATE OR REPLACE TASK")
    parse_proc, _parse_task = _split_at("tasks/parse_documents.sql", "-- EXECUTE AS USER: chunk_documents_proc")
    grants_main, grants_guarded = _grants()
    return [
        ("00_preflight.sql", "pre-flight checks (read-only; suspends the task graph root)", [PREFLIGHT]),
        ("01_web_procedures.sql", "web read, workflow and evidence procedures",
         [_file("dynamic_tables/01_harmonized_events.sql"),
          _file("procedures/web_reads.sql"), _file("procedures/web_workflows.sql"),
          _file("procedures/web_evidence.sql"), _verify_procs(web_names)]),
        ("02_gates_and_scheme_table.sql", "gate evaluation, binding, scheme eligibility dynamic table",
         [_file("procedures/evaluate_gates.sql"), _file("procedures/bind_patient.sql"),
          _file("dynamic_tables/04_scheme_eligibility.sql"),
          _semantic_view_guarded(),
          _verify_procs(["evaluate_gates", "bind_patient"])
          + "SHOW DYNAMIC TABLES LIKE 'DT_SCHEME_ELIGIBILITY' IN SCHEMA SAARTHI.OPERATIONAL;"
            "  -- refresh_mode = FULL\n"]),
        ("03_tool_procedures.sql", "agent tool procedures, extraction, answer validation",
         [_file("procedures/tools/01_get_patient_facts.sql"), _file("procedures/tools/02_get_readiness.sql"),
          _file("procedures/tools/03_search_patient_documents.sql"),
          _file("procedures/tools/06_get_timeline.sql"), _file("procedures/tools/07_get_changes.sql"),
          _file("procedures/tools/08_create_review_task.sql"),
          _file("procedures/extract_one_document.sql"),
          _file("procedures/answer_gateway_rule.sql"),
          _file("procedures/answer_gateway_record.sql"),
          _file("procedures/answer_gateway_reference.sql"),
          _file("procedures/validate_answer.sql"),
          _file("procedures/answer_gateway_candidates.sql"),
          _file("procedures/answer_gateway_resolve.sql"),
          _file("procedures/answer_gateway_refusal.sql"),
          _file("procedures/answer_gateway_finalize.sql"),
          _file("procedures/answer_gateway_record_fallback.sql"),
          _file("procedures/answer_gateway_context_pack.sql"),
          _file("procedures/answer_gateway_context_section.sql"),
          _file("procedures/answer_gateway_context.sql"),
          _file("procedures/answer_gateway_infer.sql"), _file("agent/ask_saarthi.sql"),
          _verify_procs(tool_names)]),
        ("04_tasks_and_grants.sql",
         "suspend task root, procedures, GRANTS FIRST, then tasks re-created SUSPENDED",
         [SUSPEND_ROOT, PARSE_COLUMN, parse_proc, rec_proc, orch_proc, grants_main, grants_guarded,
          "-- VERIFY: SAARTHI_APP must hold USAGE on the OPERATIONAL procedures (grants run BEFORE the tasks below).\n"
          "SHOW GRANTS TO ROLE SAARTHI_APP;\n",
          rec_task, orch_task,
          skills_upload_sql(),
          _verify_procs(["parse_documents_proc", "reconcile_evidence_proc", "orchestrator_proc"])
          + "SHOW TASKS IN SCHEMA SAARTHI.OPERATIONAL;  -- TASK_RECONCILE_EVIDENCE and "
            "TASK_SAARTHI_ORCHESTRATOR: state = suspended\n"]),
        ("05_seed_data.sql", "deep-case seed data (includes the DOC-SURG-NOTE-01 source page)",
         [DETACH_RAP, _file("data/load_synthetic.sql"),
          "-- If the app logs in as a different Snowflake user than the one running this worksheet:\n"
          "-- UPDATE SAARTHI.GOVERNANCE.PRACTITIONER SET snowflake_user = '<app user, exact case>' "
          "WHERE practitioner_id = 'PRAC-01';  -- AGENTS.md 3.1\n"
          "-- VERIFY: expect 1 and 1 (read after step 07 re-attaches the policy, as the PRAC-01 user).\n"
          "SELECT (SELECT COUNT(*) FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-SURG-NOTE-01') AS surg_pages,\n"
          "       (SELECT COUNT(*) FROM SAARTHI.CORE.PATIENT WHERE patient_id = 'PAT-DEEP-0001') AS deep_patient;\n"]),
        ("06_cohort_and_documents.sql",
         "day-care cohort (PAT-DC-01..11) and its generated synthetic documents",
         [DETACH_RAP,
          "-- SKIP the cohort block below if preflight showed all 12 patients present (it re-anchors event dates to today,\n"
          "-- and the document effective_at values are frozen at manifest generation: see README). Keep the detach above\n"
          "-- and the document MERGEs in every case: they are idempotent only while the policy is detached.\n",
          _file("data/load_daycare_cohort.sql"), _generated_documents(),
          "-- VERIFY: expect 16 documents over 11 patients (page counts are read after step 07 re-attaches the policy).\n"
          "SELECT COUNT(*) AS documents, COUNT(DISTINCT patient_id) AS patients FROM SAARTHI.DOCUMENTS.DOCUMENT\n"
          " WHERE doc_id LIKE 'DOC-LAB-DC-%' OR doc_id LIKE 'DOC-PATH-DC-%';\n"]),
        ("07_governance_row_access.sql",
         "DOC_PAGE row access policy (layer 3 of R5): detach, recreate, canary, re-attach, negative test",
         [_slice("governance/01_policies.sql", "EXECUTE IMMEDIATE $$", "-- Sensitivity tag"),
          RAP_CANARY,
          _slice("governance/02_attach_policies.sql", "ALTER TABLE SAARTHI.DOCUMENTS.DOC_PAGE",
                 ";", include_end=True),
          "-- VERIFY: one row, DOC_PAGE.\nSELECT policy_name, ref_entity_name FROM TABLE("
          "SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => "
          "'SAARTHI.GOVERNANCE.PATIENT_SCOPE'));\n",
          RAP_NEGATIVE]),
        ("08_pipeline_kickoff.sql", "document pipeline: chunk, two-pass extract, reconcile, readiness", [PIPELINE]),
        ("09_verify.sql", "post-deploy verification (read-only)", [VERIFY]),
    ]


def build() -> dict[str, str]:
    files: dict[str, str] = {}
    for name, title, parts in steps():
        header = HEADER.format(name=name, title=title)
        files[name] = header + "\n" + "\n".join(parts).rstrip() + "\n"
    files["README.md"] = readme(files)
    return files


def readme(files: dict[str, str]) -> str:
    rows = "\n".join(f"| {n} | {len(files[n].encode()) // 1024 + 1} KB |"
                     for n in sorted(files) if n.endswith(".sql"))
    return f"""# SAARTHI deploy bundle (generated)

Generated by `backend/scripts/build_deploy_bundle.py` from the repo SQL; `backend/tests/test_deploy_bundle.py`
fails if this directory is stale. Rebuild with `./venv/bin/python -m backend.scripts.build_deploy_bundle`.
It supersedes `evidence/qa/DEPLOY-ROUND-2.md`; the walk-through with per-step checks is
`evidence/qa/DEPLOY-ROUND-4.md` (supersedes DEPLOY-ROUND-3.md). Nothing here has been executed on Snowflake (`unverified-needs-deploy`);
all data is synthetic; engineering checks are not clinical validation. `setup.sql` is never included (it drops
CORE tables). No credentials appear anywhere in these files.

## How to run
Open Snowsight as ACCOUNTADMIN (object DDL; the script runner refuses it without `--allow-accountadmin`).
For each file in order: paste it into one worksheet, **Run all**, then read the VERIFY block at its end.
Stop at the first failure. Exception: `08_pipeline_kickoff.sql` is run statement by statement.
After step 08 restart the web server (it must not serve code built before the procedures changed).

| File | Size |
|------|------|
{rows}

## Step order (changed in Round 4: DEPLOY-ROUND-4.md supersedes DEPLOY-ROUND-3.md)
The row access policy is attached LAST among the data steps (07), because a MERGE into `DOC_PAGE` under the policy
cannot see rows the running user is not entitled to and would insert duplicates on a re-run (N4-02). Steps 05 and 06
detach the policy first (a no-op on a fresh account); step 07 recreates and re-attaches it.
**If step 05, 06 or 07 fails part way, run step 07 again before anything else.** Steps 08 and 09 refuse to run
(a raised exception, not a silent pass) while `DOC_PAGE` has no `PATIENT_SCOPE` policy.

## Pass criteria per step
| Step | Pass criterion |
|------|----------------|
| 00 | role ACCOUNTADMIN, no secondary roles; stage encryption `SNOWFLAKE_SSE`; task states recorded; baseline counts saved; missing-procedure query returns 0 rows; `TASK_PARSE_DOCUMENTS` suspended (executed) |
| 01 | VERIFY returns 6 procedures (GET_WEB_WORKSPACE, GET_WEB_PATIENT_DATA, UPDATE_WEB_REVIEW_TASK, REFRESH_BOUND_READINESS, RECORD_WEB_ANSWER, PREPARE_WEB_PACKET) |
| 02 | 2 procedures; `DT_SCHEME_ELIGIBILITY` `refresh_mode = FULL`; semantic view block returns `created: ...` or a readable `skipped` (clause syntax unverified) |
| 03 | 10 procedures listed |
| 04 | task root suspended; grants applied BEFORE the tasks (`SHOW GRANTS TO ROLE SAARTHI_APP`); AGENT/MCP grant blocks return `granted` or a readable `skipped`; `LIST @SAARTHI.STAGES.SKILLS` shows 4 skill files; 3 procedures (`PARSE_DOCUMENTS_PROC` now keyed on `source_path`, `RECONCILE_EVIDENCE_PROC`, `ORCHESTRATOR_PROC`); both tasks `suspended` |
| 05 | DOC-SURG-NOTE-01 source page merged once; PAT-DEEP-0001 exists |
| 06 | 16 documents over 11 patients (PAT-DC-01..11): 11 lab reports, 5 pathology reports (PAT-DC-01, 02, 04, 06, 10) |
| 07 | `PATIENT_SCOPE` referenced by exactly `DOC_PAGE`; canary query returns 0 rows and the negative-test block does not raise (RAISE = fail closed) |
| 08 | guard block returns `ok`; each CALL returns without error; repeat `extract_assertions_proc` until nothing is pending |
| 09 | all 12 patients in the documents query; no duplicate pages; canary 0 rows; 0 rows from the "verified without agreeing passes/span" query; every patient has gates with `with_evidence >= 1` |

Counts that cannot be fixed in advance: assertions by `verification_status` depend on live model output, so the
criterion is the R7 invariant (a `verified` row has two agreeing passes and a source span), not a number.
Expected before the pipeline runs: the three seeded `DOC-SURG-NOTE-01` assertions are `unverified`/`pending`.

## Known caveats
* The cohort document `effective_at` values are frozen when the manifest was generated; `load_daycare_cohort.sql`
  re-anchors event dates to the deploy day. If you deploy on a later day, regenerate the manifest first
  (`./venv/bin/python -m data.generator.cohort_documents --manifest data/generated/cohort_document_manifest.json`,
  then rebuild this bundle) or the document to event `supports` links will not match by date.
* A web server that was built earlier must be restarted after step 8.
* Step 08 reads DOC_PAGE through the row access policy, which keys on `CURRENT_USER()` (AGENTS.md 3.1): run it as the
  Snowflake user stored on practitioner `PRAC-01`. Its first statement is a guard that raises when the user, the
  procedures, the policy or the cohort pages are wrong, so a mismatch fails loudly instead of seeing nothing.
* `RELEASE_PATIENT_BINDING`, `ASK_SAARTHI`, `CHUNK_DOCUMENTS_PROC`, `EXTRACT_ASSERTIONS_PROC`
  and `REFRESH_READINESS_PROC` are NOT created by this bundle; step 00 lists any that are missing (deploy them from the repo).
* `SAARTHI_AGENT` and `SAARTHI_MCP` are not created by the bundle; their grants are guarded and report `skipped` if absent.
* The canary document `DOC-RAP-CANARY-01` (patient `PAT-RAP-CANARY`, no care team) is synthetic test data kept for the
  negative test; it is excluded from the verification counts by name.
* PAT-DEEP-0001 can show a document-cited gate span only after the two-pass run verifies an assertion from
  DOC-SURG-NOTE-01 (or the live Tata Memorial CBC); that is intended and is not forced by the seed.
"""


def main(argv: list[str]) -> int:
    files = build()
    if "--check" in argv:
        stale = [n for n, text in files.items()
                 if not (OUT / n).exists() or (OUT / n).read_text() != text]
        if not SKILLS_SQL.exists() or SKILLS_SQL.read_text() != skills_upload_sql():
            stale.append("backend/skills/upload_skills.sql")
        extra = [p.name for p in OUT.glob("*") if p.name not in files] if OUT.exists() else []
        if stale or extra:
            print("deploy bundle is stale: " + ", ".join(stale + extra), file=sys.stderr)
            return 1
        print(f"deploy bundle is current ({len(files)} files)")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*"):
        if old.name not in files:
            old.unlink()
    for name, text in files.items():
        (OUT / name).write_text(text)
    SKILLS_SQL.write_text(skills_upload_sql())
    print(f"wrote {len(files)} files to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
