-- 00_preflight.sql: pre-flight checks (read-only; suspends the task graph root)
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;

-- Read-only EXCEPT the one guarded task suspend at the end. Record the output; compare after step 9.
SELECT CURRENT_ROLE() AS role, CURRENT_SECONDARY_ROLES() AS secondary_roles;  -- ACCOUNTADMIN, none
DESC STAGE SAARTHI.STAGES.PATIENT_DOCS;  -- property "ENCRYPTION" / TYPE must be SNOWFLAKE_SSE (AGENTS.md 3.7)
SHOW TASKS IN SCHEMA SAARTHI.OPERATIONAL;  -- note which are "started" BEFORE the suspend below
SELECT patient_id, COUNT(*) AS documents FROM SAARTHI.DOCUMENTS.DOCUMENT GROUP BY 1 ORDER BY 1;  -- baseline
SELECT COUNT(*) AS patients_present FROM SAARTHI.CORE.PATIENT
 WHERE patient_id = 'PAT-DEEP-0001' OR patient_id LIKE 'PAT-DC-%';  -- if 12, step 7 (cohort) may be skipped
SELECT verification_status, missingness_state, COUNT(*) AS n
  FROM SAARTHI.EVIDENCE.ASSERTION GROUP BY 1, 2 ORDER BY 1, 2;  -- baseline
-- N4-06: procedures that the web and step 08 depend on but this bundle does not create (earlier rounds / setup.sql).
-- PASS: 0 rows. Any row = deploy that procedure from the repo first (backend/sql/procedures, tasks, agent).
SELECT n.name AS missing_procedure
  FROM (SELECT column1 AS name FROM VALUES ('RELEASE_PATIENT_BINDING'), ('ASK_SAARTHI'), ('PARSE_DOCUMENTS_PROC'),
                                           ('CHUNK_DOCUMENTS_PROC'), ('EXTRACT_ASSERTIONS_PROC'), ('REFRESH_READINESS_PROC')) n
  LEFT JOIN SAARTHI.INFORMATION_SCHEMA.PROCEDURES p
    ON p.procedure_schema = 'OPERATIONAL' AND p.procedure_name = n.name
 WHERE p.procedure_name IS NULL;  -- expect 0 rows
-- N4-01: EXECUTED (not commented). A started task graph makes CREATE OR REPLACE TASK on a child fail.
-- IF EXISTS plus the handler make this a no-op on a fresh account. Resume is a deliberate manual step (step 08 tail).
EXECUTE IMMEDIATE $$
BEGIN
    ALTER TASK IF EXISTS SAARTHI.OPERATIONAL.TASK_PARSE_DOCUMENTS SUSPEND;
    RETURN 'TASK_PARSE_DOCUMENTS suspended (or absent)';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'task suspend skipped: ' || SQLERRM;
END;
$$;
