-- 01_web_procedures.sql: web read, workflow and evidence procedures
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;

-- ===== BEGIN dynamic_tables/01_harmonized_events.sql =====
-- =============================================================================
-- STEP 15a - DT_HARMONIZED_EVENTS (pulled forward - the vertical slice needs it)
-- =============================================================================
-- SPEC.md §13, WORK-PLAN.md Day 4-5. The single most load-bearing Dynamic
-- Table. NO AI FUNCTIONS HERE - a DT requires deterministic refresh; AI steps
-- live in Tasks (step 16).
--
-- This build implements ANC derivation and registered conversions, preserving
-- canonical values without double conversion. CrCl is evaluated by evaluate_gates,
-- not materialized here. Missing required inputs yield not_evaluated.
CREATE OR REPLACE DYNAMIC TABLE SAARTHI.CORE.DT_HARMONIZED_EVENTS
  TARGET_LAG = '1 minute'
  WAREHOUSE = SAARTHI_AI_WH
AS
WITH converted AS (
    SELECT ce.*, co.canonical_name AS concept_name,
           ur.canonical_unit, ur.plausible_min, ur.plausible_max,
           CASE WHEN ur.canonical_unit IS NULL THEN ce.value_num
                WHEN ce.unit = ur.canonical_unit THEN ce.value_num
                WHEN ce.unit = ur.source_unit_pattern AND ur.conversion_factor > 0
                  THEN ce.value_num * ur.conversion_factor
                ELSE NULL END AS normalized_value
      FROM SAARTHI.CORE.CLINICAL_EVENT ce
      LEFT JOIN SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY co ON co.concept_id = ce.concept_id
      LEFT JOIN SAARTHI.OPERATIONAL.UNIT_REGISTRY ur
        ON ur.concept_id = ce.concept_id AND ur.source_unit_pattern = ce.original_unit
),
normalized AS (
    SELECT event_id, patient_id, encounter_id, event_type, concept_id, concept_name,
           normalized_value AS value_num, value_text, abnormal_flag,
           CASE WHEN value_num IS NOT NULL AND normalized_value IS NULL THEN 'unreadable'
                WHEN plausible_min IS NOT NULL AND normalized_value < plausible_min
                  THEN 'unreadable'
                WHEN plausible_max IS NOT NULL AND normalized_value > plausible_max
                  THEN 'unreadable'
                ELSE 'present' END AS plausibility_state,
           event_time, source_recorded_at, ingested_at, valid_until, specimen_id,
           COALESCE(canonical_unit,unit) AS unit
      FROM converted
),
anc_derived AS (
    -- ANC = WBC x (neutrophil% + band%) / 100, computed only when the lab
    -- reported a differential and no direct ANC row exists (WORK-PLAN.md
    -- Day 4-5 acceptance test: WBC 6000, neutrophils 35% -> ANC 2100).
    SELECT
        wbc.event_id || '-ANC-DERIVED' AS event_id,
        wbc.patient_id, wbc.encounter_id, 'lab' AS event_type,
        (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'ANC') AS concept_id,
        'ANC' AS concept_name,
        wbc.value_num * (neut.value_num) / 100 AS value_num,
        NULL AS value_text,
        NULL AS abnormal_flag,
        'present' AS plausibility_state,
        wbc.event_time,
        CASE WHEN wbc.source_recorded_at > neut.source_recorded_at
             THEN wbc.source_recorded_at ELSE neut.source_recorded_at END AS source_recorded_at,
        CASE WHEN wbc.ingested_at > neut.ingested_at
             THEN wbc.ingested_at ELSE neut.ingested_at END AS ingested_at,
        wbc.valid_until, wbc.specimen_id, wbc.unit
    FROM normalized wbc
    JOIN normalized neut
      ON neut.patient_id = wbc.patient_id
     AND neut.encounter_id = wbc.encounter_id
     -- Null-safe: structured CBC feeds often carry no specimen_id, and NULL = NULL
     -- would silently drop every derivation. The COUNT = 1 guard below still
     -- refuses to pick between two differentials for the same draw.
     AND neut.specimen_id IS NOT DISTINCT FROM wbc.specimen_id
     AND neut.event_time   = wbc.event_time
     AND neut.concept_name = 'NEUTROPHIL_PCT'
    WHERE wbc.concept_name = 'WBC'
      AND wbc.plausibility_state = 'present' AND neut.plausibility_state = 'present'
      AND wbc.value_num > 0 AND neut.value_num BETWEEN 0 AND 100
      AND wbc.unit IN ('/uL','/cumm','/CUMM') AND neut.unit = '%'
      AND wbc.source_recorded_at IS NOT NULL AND neut.source_recorded_at IS NOT NULL
      AND wbc.ingested_at IS NOT NULL AND neut.ingested_at IS NOT NULL
      AND 1 = (SELECT COUNT(*) FROM normalized differential
                WHERE differential.patient_id = wbc.patient_id
                  AND differential.encounter_id = wbc.encounter_id
                  AND differential.specimen_id IS NOT DISTINCT FROM wbc.specimen_id
                  AND differential.event_time = wbc.event_time
                  AND differential.concept_name = 'NEUTROPHIL_PCT')
      AND NOT EXISTS (
            SELECT 1 FROM normalized anc
             WHERE anc.patient_id = wbc.patient_id
               AND anc.encounter_id = wbc.encounter_id
               AND anc.specimen_id IS NOT DISTINCT FROM wbc.specimen_id
               AND anc.event_time = wbc.event_time AND anc.concept_name = 'ANC'
          )
)
SELECT event_id, patient_id, encounter_id, event_type, concept_id, concept_name,
       value_num, value_text, abnormal_flag, plausibility_state,
       FALSE AS is_derived,
       NULL AS derivation,
       event_time, source_recorded_at, ingested_at, valid_until, specimen_id, unit
FROM normalized
UNION ALL
SELECT event_id, patient_id, encounter_id, event_type, concept_id, concept_name,
       value_num, value_text, abnormal_flag, plausibility_state,
       TRUE AS is_derived,
       'ANC computed as WBC x neutrophil% / 100' AS derivation,
       event_time, source_recorded_at, ingested_at, valid_until, specimen_id, unit
FROM anc_derived;
-- ===== END dynamic_tables/01_harmonized_events.sql =====

-- ===== BEGIN procedures/web_reads.sql =====
-- Bounded web reads. No table grants or shared patient sessions; CURRENT_USER is authoritative.
CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.GET_WEB_WORKSPACE(VIEW_NAME VARCHAR, HORIZON_DAYS INTEGER)
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS $$
DECLARE v_rows ARRAY;
BEGIN
IF (HORIZON_DAYS IS NULL OR HORIZON_DAYS < 1 OR HORIZON_DAYS > 31) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
IF (VIEW_NAME = 'patients') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
WITH patient_scope AS (
  SELECT DISTINCT p.patient_id, p.name
  FROM SAARTHI.CORE.PATIENT p
  JOIN SAARTHI.GOVERNANCE.CARE_TEAM ct ON ct.patient_id = p.patient_id
  JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr ON pr.practitioner_id = ct.practitioner_id
  LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id = pr.facility_id
  WHERE pr.snowflake_user = CURRENT_USER() AND pr.active = TRUE
    AND ct.role_type IN ('treating', 'coordinator')
    AND ct.active_from <= CURRENT_DATE()
    AND (ct.active_to IS NULL OR ct.active_to >= CURRENT_DATE())
    AND EXISTS (
      SELECT 1 FROM SAARTHI.GOVERNANCE.CONSENT c
      WHERE c.patient_id = p.patient_id AND c.status = 'active'
        AND c.valid_from <= CURRENT_TIMESTAMP()
        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
        AND c.purpose_code IN ('treatment', 'coordination')
        AND COALESCE(ARRAY_CONTAINS('identity'::VARIANT, c.data_categories), FALSE)
        AND (:VIEW_NAME = 'patients' OR (
          COALESCE(ARRAY_CONTAINS('clinical'::VARIANT, c.data_categories), FALSE)
          AND COALESCE(ARRAY_CONTAINS('financial'::VARIANT, c.data_categories), FALSE)))
        AND (c.granted_to_facility_id = pr.facility_id OR c.granted_to_org_id = f.org_id)
    )
)
SELECT patient_id, name FROM patient_scope ORDER BY name, patient_id
);
ELSEIF (VIEW_NAME = 'queue_readiness') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
WITH patient_scope AS (
  SELECT DISTINCT p.patient_id, p.name
  FROM SAARTHI.CORE.PATIENT p
  JOIN SAARTHI.GOVERNANCE.CARE_TEAM ct ON ct.patient_id = p.patient_id
  JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr ON pr.practitioner_id = ct.practitioner_id
  LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id = pr.facility_id
  WHERE pr.snowflake_user = CURRENT_USER() AND pr.active = TRUE
    AND ct.role_type IN ('treating', 'coordinator')
    AND ct.active_from <= CURRENT_DATE()
    AND (ct.active_to IS NULL OR ct.active_to >= CURRENT_DATE())
    AND EXISTS (
      SELECT 1 FROM SAARTHI.GOVERNANCE.CONSENT c
      WHERE c.patient_id = p.patient_id AND c.status = 'active'
        AND c.valid_from <= CURRENT_TIMESTAMP()
        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
        AND c.purpose_code IN ('treatment', 'coordination')
        AND COALESCE(ARRAY_CONTAINS('identity'::VARIANT, c.data_categories), FALSE)
        AND (:VIEW_NAME = 'patients' OR (
          COALESCE(ARRAY_CONTAINS('clinical'::VARIANT, c.data_categories), FALSE)
          AND COALESCE(ARRAY_CONTAINS('financial'::VARIANT, c.data_categories), FALSE)))
        AND (c.granted_to_facility_id = pr.facility_id OR c.granted_to_org_id = f.org_id)
    )
), selected_visit AS (
  SELECT e.patient_id, e.encounter_id, e.scheduled_time
  FROM SAARTHI.CORE.ENCOUNTER e JOIN patient_scope p ON p.patient_id = e.patient_id
  WHERE e.encounter_type = 'daycare'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY e.patient_id ORDER BY
    IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), 0, 1),
    IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), e.scheduled_time, NULL) ASC NULLS LAST,
    IFF(e.scheduled_time < CURRENT_TIMESTAMP(), e.scheduled_time, NULL) DESC NULLS LAST,
    e.encounter_id) = 1
)
SELECT p.patient_id, p.name, e.encounter_id,
       TO_VARCHAR(e.scheduled_time, 'YYYY-MM-DD"T"HH24:MI:SS') AS scheduled,
       DATEDIFF(day, CURRENT_DATE(), e.scheduled_time) AS days_to_visit,
       rs.gate, rs.rule_id, rs.rule_version, rs.outcome, rs.severity, rs.reason,
       TO_VARCHAR(rs.known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS') AS known_as_of
FROM patient_scope p
LEFT JOIN selected_visit e ON e.patient_id = p.patient_id
LEFT JOIN SAARTHI.OPERATIONAL.READINESS_STATE rs
  ON rs.patient_id = p.patient_id AND rs.encounter_id = e.encounter_id
ORDER BY e.scheduled_time, p.patient_id, rs.gate, rs.rule_id
);
ELSEIF (VIEW_NAME = 'queue_tasks') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
WITH patient_scope AS (
  SELECT DISTINCT p.patient_id, p.name
  FROM SAARTHI.CORE.PATIENT p
  JOIN SAARTHI.GOVERNANCE.CARE_TEAM ct ON ct.patient_id = p.patient_id
  JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr ON pr.practitioner_id = ct.practitioner_id
  LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id = pr.facility_id
  WHERE pr.snowflake_user = CURRENT_USER() AND pr.active = TRUE
    AND ct.role_type IN ('treating', 'coordinator')
    AND ct.active_from <= CURRENT_DATE()
    AND (ct.active_to IS NULL OR ct.active_to >= CURRENT_DATE())
    AND EXISTS (
      SELECT 1 FROM SAARTHI.GOVERNANCE.CONSENT c
      WHERE c.patient_id = p.patient_id AND c.status = 'active'
        AND c.valid_from <= CURRENT_TIMESTAMP()
        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
        AND c.purpose_code IN ('treatment', 'coordination')
        AND COALESCE(ARRAY_CONTAINS('identity'::VARIANT, c.data_categories), FALSE)
        AND (:VIEW_NAME = 'patients' OR (
          COALESCE(ARRAY_CONTAINS('clinical'::VARIANT, c.data_categories), FALSE)
          AND COALESCE(ARRAY_CONTAINS('financial'::VARIANT, c.data_categories), FALSE)))
        AND (c.granted_to_facility_id = pr.facility_id OR c.granted_to_org_id = f.org_id)
    )
), task_subjects AS (
  SELECT rt.*, ri.patient_id, ri.rule_id, ri.encounter_id
  FROM SAARTHI.OPERATIONAL.REVIEW_TASK rt
  JOIN SAARTHI.OPERATIONAL.REVIEW_ISSUE ri ON ri.issue_id = rt.issue_id
  JOIN patient_scope p ON p.patient_id = ri.patient_id
  UNION ALL
  SELECT rt.*, r.patient_id, r.rule_id, NULL AS encounter_id
  FROM SAARTHI.OPERATIONAL.REVIEW_TASK rt
  JOIN (SELECT DISTINCT rs.patient_id, rs.rule_id
        FROM SAARTHI.OPERATIONAL.READINESS_STATE rs
        JOIN patient_scope p ON p.patient_id = rs.patient_id) r
    ON rt.issue_id = r.patient_id || ':' || r.rule_id
  WHERE NOT EXISTS (SELECT 1 FROM SAARTHI.OPERATIONAL.REVIEW_ISSUE ri WHERE ri.issue_id = rt.issue_id)
)
SELECT t.patient_id, t.rule_id, t.encounter_id, t.task_id, t.issue_id,
       t.owner_practitioner_id, owner.name AS owner_name, t.state, t.decision, t.reason,
       TO_VARCHAR(t.created_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS created_at
FROM task_subjects t
LEFT JOIN SAARTHI.GOVERNANCE.PRACTITIONER owner
  ON owner.practitioner_id = t.owner_practitioner_id
WHERE t.idempotency_key NOT LIKE 'web-event:%'
ORDER BY t.created_at DESC, t.task_id
);
ELSEIF (VIEW_NAME = 'census') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
WITH patient_scope AS (
  SELECT DISTINCT p.patient_id, p.name
  FROM SAARTHI.CORE.PATIENT p
  JOIN SAARTHI.GOVERNANCE.CARE_TEAM ct ON ct.patient_id = p.patient_id
  JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr ON pr.practitioner_id = ct.practitioner_id
  LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id = pr.facility_id
  WHERE pr.snowflake_user = CURRENT_USER() AND pr.active = TRUE
    AND ct.role_type IN ('treating', 'coordinator')
    AND ct.active_from <= CURRENT_DATE()
    AND (ct.active_to IS NULL OR ct.active_to >= CURRENT_DATE())
    AND EXISTS (
      SELECT 1 FROM SAARTHI.GOVERNANCE.CONSENT c
      WHERE c.patient_id = p.patient_id AND c.status = 'active'
        AND c.valid_from <= CURRENT_TIMESTAMP()
        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
        AND c.purpose_code IN ('treatment', 'coordination')
        AND COALESCE(ARRAY_CONTAINS('identity'::VARIANT, c.data_categories), FALSE)
        AND (:VIEW_NAME = 'patients' OR (
          COALESCE(ARRAY_CONTAINS('clinical'::VARIANT, c.data_categories), FALSE)
          AND COALESCE(ARRAY_CONTAINS('financial'::VARIANT, c.data_categories), FALSE)))
        AND (c.granted_to_facility_id = pr.facility_id OR c.granted_to_org_id = f.org_id)
    )
)
   , plan AS (
      SELECT patient_id, regimen_display
        FROM SAARTHI.CORE.TREATMENT_PLAN
      QUALIFY ROW_NUMBER() OVER (PARTITION BY patient_id
                                 ORDER BY version DESC, decided_at DESC NULLS LAST) = 1
  )
   , dx AS (
      SELECT patient_id, display AS diagnosis, code AS diagnosis_code
        FROM SAARTHI.CORE.CLINICAL_EVENT
       WHERE event_type = 'diagnosis' AND display IS NOT NULL
      QUALIFY ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY event_time DESC, event_id DESC) = 1
  )
  SELECT e.encounter_id, p.patient_id, p.name, p.district, p.state, p.primary_language,
         plan.regimen_display, dx.diagnosis, dx.diagnosis_code, e.cycle_number,
         TO_VARCHAR(e.scheduled_time, 'YYYY-MM-DD"T"HH24:MI:SS') AS scheduled,
         rs.gate, rs.rule_id, rs.rule_version, rs.outcome, rs.severity, rs.reason,
         TO_VARCHAR(rs.known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS') AS known_as_of,
         TO_VARCHAR(rs.computed_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS computed_at
    FROM SAARTHI.CORE.ENCOUNTER e
    JOIN SAARTHI.CORE.PATIENT p ON p.patient_id = e.patient_id
    LEFT JOIN plan ON plan.patient_id = e.patient_id
    LEFT JOIN dx ON dx.patient_id = e.patient_id
    LEFT JOIN SAARTHI.OPERATIONAL.READINESS_STATE rs ON rs.encounter_id = e.encounter_id
   WHERE e.encounter_type = 'daycare'
     AND e.scheduled_time >= CURRENT_DATE()
     AND e.scheduled_time <  DATEADD(day, :HORIZON_DAYS, CURRENT_DATE())
 AND e.patient_id IN (SELECT patient_id FROM patient_scope)
 ORDER BY e.scheduled_time, p.name
);
ELSEIF (VIEW_NAME = 'practitioner') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT name, qualification FROM SAARTHI.GOVERNANCE.PRACTITIONER WHERE snowflake_user = CURRENT_USER() AND active=TRUE
);
ELSE RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
RETURN OBJECT_CONSTRUCT('rows',v_rows);
END;
$$;

CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.GET_WEB_PATIENT_DATA(VIEW_NAME VARCHAR, ARGUMENT VARCHAR)
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS $$
DECLARE KNOWN_AS_OF VARCHAR DEFAULT NULL;
v_known_as_of TIMESTAMP_NTZ; v_known_as_of_s VARCHAR; v_binding_id VARCHAR;
v_patient_id VARCHAR; v_practitioner VARCHAR; v_care_team_id VARCHAR; v_consent_id VARCHAR;
v_rows ARRAY; v_expected ARRAY; v_doc_id VARCHAR; v_doc_cutoff VARCHAR; v_scheme_fin BOOLEAN DEFAULT FALSE;
BEGIN
-- >>> SAARTHI PREAMBLE v1 BEGIN
    -- 0 -- KNOWN_AS_OF. Resolved before anything can fail, so every error carries it.
    v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:KNOWN_AS_OF), CURRENT_TIMESTAMP());
    v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');

    -- 1 -- SELECTION. The subject comes from a human click, never from question text.
    v_binding_id := (SELECT binding_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE session_id = CURRENT_SESSION()
                        AND released_at IS NULL
                      ORDER BY bound_at DESC
                      LIMIT 1);
    IF (v_binding_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_bound',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_patient_id := (SELECT patient_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE binding_id = :v_binding_id);

    -- 2 -- AUTHORISATION. CURRENT_USER() survives owner's-rights elevation; CURRENT_ROLE() does not (F3).
    v_practitioner := (SELECT practitioner_id
                         FROM SAARTHI.GOVERNANCE.PRACTITIONER
                        WHERE snowflake_user = CURRENT_USER()
                          AND active = TRUE);
    IF (v_practitioner IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_care_team_id := (SELECT care_team_id
                         FROM SAARTHI.GOVERNANCE.CARE_TEAM
                        WHERE practitioner_id = :v_practitioner
                          AND patient_id     = :v_patient_id
                          AND role_type IN ('treating', 'coordinator')
                          AND active_from   <= CURRENT_DATE()
                          AND (active_to IS NULL OR active_to >= CURRENT_DATE())
                        ORDER BY active_from DESC
                        LIMIT 1);
    IF (v_care_team_id IS NULL) THEN
        -- Reveals nothing about whether the patient exists. Do not add a reason.
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    -- 3 -- CONSENT, at query time. Never at ingest, never cached in the binding.
    v_consent_id := (SELECT c.consent_id
                       FROM SAARTHI.GOVERNANCE.CONSENT c
                       JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
                         ON p.practitioner_id = :v_practitioner
                       LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f
                         ON f.facility_id = p.facility_id
                      WHERE c.patient_id = :v_patient_id
                        AND c.status     = 'active'
                        AND c.valid_from <= CURRENT_TIMESTAMP()
                        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
                        AND c.purpose_code IN ('treatment', 'coordination')
                        AND (c.granted_to_facility_id = p.facility_id
                          OR c.granted_to_org_id      = f.org_id)
                      ORDER BY c.valid_from DESC
                      LIMIT 1);
    IF (v_consent_id IS NULL) THEN
        -- Release the binding: the context is cleared, not merely hidden.
        UPDATE SAARTHI.GOVERNANCE.PATIENT_BINDING
           SET released_at = CURRENT_TIMESTAMP()
         WHERE binding_id = :v_binding_id
           AND released_at IS NULL;
        -- This code DOES reveal that a record exists. That is deliberate: it only
        -- reaches a user who previously had legitimate access to it.
        RETURN OBJECT_CONSTRUCT('error', 'access_withdrawn',
                                'known_as_of', :v_known_as_of_s);
    END IF;
-- <<< SAARTHI PREAMBLE v1 END
LET v_categories ARRAY := (SELECT data_categories FROM SAARTHI.GOVERNANCE.CONSENT
                          WHERE consent_id = :v_consent_id);
IF (VIEW_NAME IN ('context','snapshot','tasks','answers','packets','document','documents')
    AND (NOT COALESCE(ARRAY_CONTAINS('identity'::VARIANT,:v_categories),FALSE)
      OR NOT COALESCE(ARRAY_CONTAINS('clinical'::VARIANT,:v_categories),FALSE)
      OR (VIEW_NAME != 'context'
        AND NOT COALESCE(ARRAY_CONTAINS('financial'::VARIANT,:v_categories),FALSE)))) THEN
  RETURN OBJECT_CONSTRUCT('error','consent_not_valid',
    'detail','This combined view requires consent for every included data category.',
    'known_as_of',:v_known_as_of_s);
END IF;
IF (VIEW_NAME = 'context') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
-- Same visit as the 'snapshot' gates: the next upcoming daycare visit, else the most
-- recent past one. Requiring a future visit blanked the header the day after a visit
-- while the gates still described it.
WITH next_visit AS (
         SELECT patient_id, cycle_number,
                TO_VARCHAR(scheduled_time, 'YYYY-MM-DD"T"HH24:MI:SS') AS scheduled_at
           FROM SAARTHI.CORE.ENCOUNTER
          WHERE encounter_type = 'daycare' AND patient_id = :v_patient_id
          QUALIFY ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY
            IFF(scheduled_time >= CURRENT_TIMESTAMP(), 0, 1),
            IFF(scheduled_time >= CURRENT_TIMESTAMP(), scheduled_time, NULL) ASC NULLS LAST,
            IFF(scheduled_time < CURRENT_TIMESTAMP(), scheduled_time, NULL) DESC NULLS LAST) = 1
       ), latest_plan AS (
         SELECT patient_id, regimen_display
           FROM SAARTHI.CORE.TREATMENT_PLAN
          QUALIFY ROW_NUMBER() OVER (
            PARTITION BY patient_id ORDER BY version DESC, decided_at DESC) = 1
       )
       SELECT p.name, p.primary_language, nv.scheduled_at, nv.cycle_number,
              lp.regimen_display,
              (SELECT b.consent_id FROM SAARTHI.GOVERNANCE.PATIENT_BINDING b
                WHERE b.session_id = CURRENT_SESSION() AND b.released_at IS NULL
                ORDER BY b.bound_at DESC LIMIT 1) AS consent_id,
              pr.name AS practitioner_name,
              (SELECT treating.name
                 FROM SAARTHI.GOVERNANCE.CARE_TEAM ct
                 JOIN SAARTHI.GOVERNANCE.PRACTITIONER treating
                   ON treating.practitioner_id = ct.practitioner_id
                WHERE ct.patient_id = :v_patient_id AND ct.role_type = 'treating'
                  AND treating.active = TRUE AND NULLIF(TRIM(treating.name),'') IS NOT NULL
                  AND ct.active_from <= CURRENT_DATE()
                  AND (ct.active_to IS NULL OR ct.active_to >= CURRENT_DATE())
                ORDER BY ct.active_from DESC, treating.practitioner_id LIMIT 1)
                AS treating_practitioner_name
         FROM SAARTHI.CORE.PATIENT p
         JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr
           ON pr.snowflake_user = CURRENT_USER() AND pr.active = TRUE
         LEFT JOIN next_visit nv ON nv.patient_id = p.patient_id
         LEFT JOIN latest_plan lp ON lp.patient_id = p.patient_id
        WHERE p.patient_id = :v_patient_id
);
ELSEIF (VIEW_NAME = 'snapshot') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
WITH ranked_encounters AS (
         SELECT e.patient_id, e.encounter_id,
                ROW_NUMBER() OVER (ORDER BY
                  IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), 0, 1),
                  IFF(e.scheduled_time >= CURRENT_TIMESTAMP(),
                      e.scheduled_time, NULL) ASC NULLS LAST,
                  IFF(e.scheduled_time < CURRENT_TIMESTAMP(),
                      e.scheduled_time, NULL) DESC NULLS LAST
                ) AS visit_rank
           FROM SAARTHI.CORE.ENCOUNTER e
          WHERE e.patient_id = :v_patient_id AND e.encounter_type = 'daycare'
       ), gate_cites AS (
         -- One plain comma-LATERAL FLATTEN, nothing else in its FROM: the documented form.
         -- Later joins happen in gate_spans, so no JOIN/comma mixing exists in one FROM clause.
         SELECT rs.rule_id, rs.rule_version, rs.known_as_of, f.value::VARCHAR AS cited_id
           FROM SAARTHI.OPERATIONAL.READINESS_STATE rs,
                LATERAL FLATTEN(input => rs.evidence_ids) f
          WHERE rs.patient_id = :v_patient_id
            AND rs.encounter_id IN (SELECT encounter_id FROM ranked_encounters WHERE visit_rank = 1)
       ), gate_spans AS (
         -- Exact source spans for every gate citation that is a verified document assertion.
         -- Span-less citations (event ids, coverage ids) stay as ids: provenance is never guessed.
         SELECT gc.rule_id, gc.rule_version,
                ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(
                  'patient_id', d.patient_id, 'scope', d.scope,
                  'assertion_id', a.assertion_id, 'doc_id', a.doc_id, 'version', d.version,
                  'page_index', a.page_index, 'char_start', a.char_start, 'char_end', a.char_end,
                  'excerpt_start', GREATEST(a.char_start - 120, 0),
                  'excerpt', SUBSTR(dp.text, GREATEST(a.char_start - 120, 0) + 1,
                                    a.char_end - GREATEST(a.char_start - 120, 0) + 120),
                  'known_as_of', TO_VARCHAR(gc.known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS'),
                  'verification_status', a.verification_status)
                  ) WITHIN GROUP (ORDER BY a.doc_id, a.page_index, a.char_start, a.assertion_id) AS source_spans
           FROM gate_cites gc
           JOIN SAARTHI.EVIDENCE.ASSERTION a ON a.assertion_id = gc.cited_id
           JOIN SAARTHI.DOCUMENTS.DOCUMENT d ON d.doc_id = a.doc_id
           JOIN SAARTHI.DOCUMENTS.DOC_PAGE dp ON dp.doc_id = a.doc_id AND dp.page_index = a.page_index
          WHERE d.patient_id = :v_patient_id AND d.scope = 'patient' AND d.status = 'active'
            AND a.verification_status = 'verified'
            AND a.char_start >= 0 AND a.char_end > a.char_start AND a.char_end <= LENGTH(dp.text)
          GROUP BY gc.rule_id, gc.rule_version
       )
       SELECT rs.gate, rs.rule_id, rs.rule_version, rs.outcome, rs.severity, rs.reason,
              rs.evidence_ids::VARCHAR AS evidence_ids,
              gs.source_spans::VARCHAR AS source_spans,
              TO_VARCHAR(rs.known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS') AS known_as_of
         FROM SAARTHI.OPERATIONAL.READINESS_STATE rs
         JOIN ranked_encounters e
           ON e.patient_id = rs.patient_id AND e.encounter_id = rs.encounter_id
         LEFT JOIN gate_spans gs
           ON gs.rule_id = rs.rule_id AND gs.rule_version = rs.rule_version
        WHERE e.visit_rank = 1
        ORDER BY rs.gate, rs.rule_id
);
ELSEIF (VIEW_NAME = 'tasks') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT rt.task_id,rt.issue_id,rt.owner_practitioner_id,COALESCE(pr.name,rt.owner_practitioner_id) AS owner,
rt.state,rt.decision,rt.reason,rt.actor_practitioner_id,actor.name AS actor,
COALESCE(ri.version,0) AS issue_version, rt.idempotency_key LIKE 'web-event:%' AS is_event,
TO_VARCHAR(rt.created_at,'YYYY-MM-DD"T"HH24:MI:SS') AS created_at
FROM SAARTHI.OPERATIONAL.REVIEW_TASK rt
LEFT JOIN SAARTHI.OPERATIONAL.REVIEW_ISSUE ri ON ri.issue_id=rt.issue_id
LEFT JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr ON pr.practitioner_id=rt.owner_practitioner_id
LEFT JOIN SAARTHI.GOVERNANCE.PRACTITIONER actor ON actor.practitioner_id=rt.actor_practitioner_id
WHERE (rt.issue_id=:v_patient_id||':'||:ARGUMENT OR (ri.patient_id=:v_patient_id AND ri.rule_id=:ARGUMENT)
   -- Write read-back by task id, still scoped to the bound patient's own issues.
   OR (rt.task_id=:ARGUMENT AND (ri.patient_id=:v_patient_id OR STARTSWITH(rt.issue_id, :v_patient_id||':'))))
ORDER BY rt.created_at DESC,rt.task_id
);
ELSEIF (VIEW_NAME = 'owners') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT DISTINCT p.practitioner_id, p.name FROM SAARTHI.GOVERNANCE.CARE_TEAM ct
JOIN SAARTHI.GOVERNANCE.PRACTITIONER p ON p.practitioner_id=ct.practitioner_id
LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id=p.facility_id
WHERE ct.patient_id=:v_patient_id AND p.active=TRUE AND ct.role_type IN ('treating','coordinator')
AND ct.active_from<=CURRENT_DATE() AND (ct.active_to IS NULL OR ct.active_to>=CURRENT_DATE())
AND EXISTS (SELECT 1 FROM SAARTHI.GOVERNANCE.CONSENT c WHERE c.patient_id=ct.patient_id
AND c.status='active' AND c.valid_from<=CURRENT_TIMESTAMP() AND (c.valid_until IS NULL OR c.valid_until>=CURRENT_TIMESTAMP())
AND c.purpose_code IN ('treatment','coordination') AND (c.granted_to_facility_id=p.facility_id OR c.granted_to_org_id=f.org_id))
ORDER BY p.name,p.practitioner_id
);
ELSEIF (VIEW_NAME = 'schemes') THEN
-- Scheme status derives from COVERAGE rows, so it is financial data (CR1-07). Without a
-- financial grant the registry rows are still listed (they are not patient data) but the
-- patient-specific limit, status and packages are withheld and the state says why (R3).
v_scheme_fin := COALESCE(ARRAY_CONTAINS('financial'::VARIANT,
    (SELECT data_categories FROM SAARTHI.GOVERNANCE.CONSENT WHERE consent_id = :v_consent_id)), FALSE);
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT scheme_id, scheme_name, scheme_type,
       IFF(:v_scheme_fin, annual_limit, NULL) AS annual_limit,
       IFF(:v_scheme_fin, eligibility_status, 'financial_consent_required') AS eligibility_status,
       IFF(:v_scheme_fin, covered_packages, NULL) AS covered_packages
FROM SAARTHI.OPERATIONAL.DT_SCHEME_ELIGIBILITY WHERE patient_id=:v_patient_id
);
ELSEIF (VIEW_NAME = 'answers') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT run_id, question_class, answer_status, known_as_of::VARCHAR AS known_as_of,
evidence_ids, claims_json, validation_results, created_at::VARCHAR AS created_at
FROM SAARTHI.EVIDENCE.ANSWER_RUN WHERE patient_id=:v_patient_id ORDER BY created_at DESC LIMIT 50
);
ELSEIF (VIEW_NAME = 'packets') THEN
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT ep.packet_id, ep.evidence_ids,ep.gate_snapshot,ep.consent_id,
pr.name AS practitioner_name,ep.delivered_at::VARCHAR AS delivered_at
FROM SAARTHI.EVIDENCE.EVIDENCE_PACKET ep LEFT JOIN SAARTHI.GOVERNANCE.PRACTITIONER pr
ON pr.practitioner_id=ep.delivered_to_practitioner_id WHERE ep.patient_id=:v_patient_id
  AND (:ARGUMENT IS NULL OR ep.packet_id=:ARGUMENT)  -- write read-back looks the packet up by id
ORDER BY ep.delivered_at DESC, ep.packet_id LIMIT 50
);
ELSEIF (VIEW_NAME = 'document') THEN
-- Citation readers send doc_id|known_as_of. Resolve the bounded identifier and
-- cutoff separately; comparing the whole argument to doc_id hid valid sources.
v_doc_id := SPLIT_PART(:ARGUMENT, '|', 1);
IF (v_doc_id IS NULL OR NOT REGEXP_LIKE(v_doc_id, '^[A-Za-z0-9_-]{1,160}$')
    OR ARRAY_SIZE(SPLIT(:ARGUMENT, '|')) > 2) THEN
  RETURN OBJECT_CONSTRUCT('error','invalid_argument','known_as_of',v_known_as_of_s);
END IF;
IF (POSITION('|', :ARGUMENT) > 0) THEN
  v_doc_cutoff := SPLIT_PART(:ARGUMENT, '|', 2);
  v_known_as_of := TRY_TO_TIMESTAMP_NTZ(:v_doc_cutoff, 'YYYY-MM-DD"T"HH24:MI:SS');
  IF (v_known_as_of IS NULL OR v_known_as_of > CURRENT_TIMESTAMP()::TIMESTAMP_NTZ) THEN
    RETURN OBJECT_CONSTRUCT('error','invalid_argument','known_as_of',v_known_as_of_s);
  END IF;
  v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');
END IF;
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT d.doc_id,dp.page_index,dp.text,d.doc_type,d.scope,d.version,
TO_VARCHAR(d.signed_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS source_recorded_at,
TO_VARCHAR(d.effective_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS event_time,
TO_VARCHAR(d.ingested_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS ingested_at,
d.status AS document_status,
TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD"T"HH24:MI:SS') AS status_observed_at
FROM SAARTHI.DOCUMENTS.DOC_PAGE dp JOIN SAARTHI.DOCUMENTS.DOCUMENT d ON d.doc_id=dp.doc_id
WHERE d.doc_id=:v_doc_id AND d.scope='patient' AND d.patient_id=:v_patient_id AND d.status='active'
AND d.ingested_at<=:v_known_as_of ORDER BY dp.page_index
);
ELSEIF (VIEW_NAME = 'documents') THEN
-- ARGUMENT carries the caller's known_as_of cutoff; the reply must echo it exactly.
IF (ARGUMENT IS NOT NULL) THEN
  v_known_as_of := TRY_TO_TIMESTAMP_NTZ(:ARGUMENT, 'YYYY-MM-DD"T"HH24:MI:SS');
  IF (v_known_as_of IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('error','invalid_argument','known_as_of',:v_known_as_of_s);
  END IF;
  v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');
END IF;
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_rows FROM (
SELECT d.doc_id, d.doc_type, d.version, d.scope, d.source_quality,
       f.name AS source_facility, COALESCE(pg.page_count, 0) AS page_count,
       -- R7: a document is 'present' only through a verified present assertion. A single-pass or
       -- unverified read is 'pending'. Unreadable / superseded / explicitly_negative surface as
       -- themselves; a document with no extraction yet is 'pending' (pipeline not run), never blank.
       CASE WHEN a.conflicting_assertions > 0 THEN 'conflicting'
            WHEN a.verified_present_assertions > 0 THEN 'present'
            WHEN a.unreadable_assertions > 0 THEN 'unreadable'
            WHEN a.explicitly_negative_assertions > 0 THEN 'explicitly_negative'
            WHEN a.superseded_assertions > 0 THEN 'superseded'
            ELSE 'pending' END AS missingness_state,
       COALESCE(a.assertion_count, 0) AS assertion_count,
       COALESCE(a.verified_assertions, 0) AS verified_assertions,
       COALESCE(a.conflicting_assertions, 0) AS conflicting_assertions,
       :v_known_as_of_s AS verification_observed_at,
       TO_VARCHAR(d.effective_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS event_time,
       TO_VARCHAR(d.signed_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS source_recorded_at,
       TO_VARCHAR(d.ingested_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS ingested_at
FROM SAARTHI.DOCUMENTS.DOCUMENT d
LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id = d.source_facility_id
LEFT JOIN (SELECT doc_id, COUNT(*) AS page_count FROM SAARTHI.DOCUMENTS.DOC_PAGE GROUP BY doc_id) pg
  ON pg.doc_id = d.doc_id
LEFT JOIN (SELECT doc_id, COUNT(*) AS assertion_count,
                  COUNT_IF(verification_status = 'verified') AS verified_assertions,
                  COUNT_IF(verification_status = 'conflicting') AS conflicting_assertions,
                  COUNT_IF(missingness_state = 'present' AND verification_status = 'verified')
                    AS verified_present_assertions,
                  COUNT_IF(missingness_state = 'unreadable') AS unreadable_assertions,
                  COUNT_IF(missingness_state = 'explicitly_negative') AS explicitly_negative_assertions,
                  COUNT_IF(missingness_state = 'superseded') AS superseded_assertions
             FROM SAARTHI.EVIDENCE.ASSERTION GROUP BY doc_id) a ON a.doc_id = d.doc_id
WHERE d.patient_id = :v_patient_id AND d.scope = 'patient' AND d.status = 'active'
  AND d.ingested_at <= :v_known_as_of
ORDER BY d.signed_at DESC NULLS LAST, d.doc_id
);
-- Expected records: documentation gates not satisfied for the selected visit. State comes
-- from the rule outcome, never from reason prose: not_evaluated = awaited, fail = absent (R3).
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(*)), ARRAY_CONSTRUCT()) INTO :v_expected FROM (
WITH ranked_encounters AS (
  SELECT e.encounter_id,
         ROW_NUMBER() OVER (ORDER BY
           IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), 0, 1),
           IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), e.scheduled_time, NULL) ASC NULLS LAST,
           IFF(e.scheduled_time < CURRENT_TIMESTAMP(), e.scheduled_time, NULL) DESC NULLS LAST
         ) AS visit_rank
    FROM SAARTHI.CORE.ENCOUNTER e
   WHERE e.patient_id = :v_patient_id AND e.encounter_type = 'daycare'
)
SELECT rc.display_name AS title, rs.rule_id,
       IFF(rs.outcome = 'not_evaluated', 'pending', 'not_received') AS missingness_state,
       rs.reason
FROM SAARTHI.OPERATIONAL.READINESS_STATE rs
JOIN ranked_encounters e ON e.encounter_id = rs.encounter_id AND e.visit_rank = 1
JOIN SAARTHI.OPERATIONAL.RULE_CATALOG rc
  ON rc.rule_id = rs.rule_id AND rc.rule_version = rs.rule_version
WHERE rs.patient_id = :v_patient_id AND rs.gate = 'documentation'
  AND rs.outcome IN ('not_evaluated', 'fail')
ORDER BY rs.rule_id
);
RETURN OBJECT_CONSTRUCT('rows',v_rows,'expected_documents',v_expected,
  'known_as_of',v_known_as_of_s,'binding_id',v_binding_id);
ELSEIF (VIEW_NAME = 'facts') THEN
-- ARGUMENT is {"domain": ..., "known_as_of": ...}. Only labs honour the cutoff (they carry
-- ingested_at); every other domain is current at query time and says so.
LET v_args VARIANT := TRY_PARSE_JSON(:ARGUMENT);
LET v_domain VARCHAR := v_args:domain::VARCHAR;
LET v_requested VARCHAR := v_args:known_as_of::VARCHAR;
LET v_facts VARIANT;
IF (v_requested IS NOT NULL) THEN
  v_known_as_of := TRY_TO_TIMESTAMP_NTZ(:v_requested, 'YYYY-MM-DD"T"HH24:MI:SS');
  IF (v_known_as_of IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('error','invalid_argument','known_as_of',:v_known_as_of_s);
  END IF;
END IF;
LET v_required_category VARCHAR := CASE :v_domain
  WHEN 'demographics' THEN 'identity' WHEN 'identity' THEN 'identity'
  WHEN 'coverage' THEN 'financial' ELSE 'clinical' END;
IF (NOT COALESCE(ARRAY_CONTAINS(:v_required_category::VARIANT,:v_categories),FALSE)) THEN
  RETURN OBJECT_CONSTRUCT('error','consent_not_valid','known_as_of',:v_known_as_of_s);
END IF;
IF (v_domain = 'labs') THEN
  v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');
  v_facts := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(
      'event_id', h.event_id, 'concept', h.concept_name, 'value', h.value_num,
      'value_text', h.value_text, 'unit', h.unit, 'abnormal_flag', h.abnormal_flag,
      -- SHARED RULE (identical to 06_get_timeline.sql; contract-tested).
      'value_state', CASE
          WHEN h.plausibility_state <> 'present' THEN h.plausibility_state
          WHEN h.value_num IS NOT NULL OR NULLIF(TRIM(h.value_text), '') IS NOT NULL THEN 'present'
          WHEN ce.status = 'ordered' THEN 'pending'
          WHEN ce.status = 'cancelled' THEN 'not_received'
          WHEN COALESCE(NULLIF(TRIM(h.concept_name), ''), NULLIF(TRIM(ce.display), ''), NULLIF(TRIM(ce.code), '')) IS NOT NULL THEN 'present'
          ELSE 'unreadable' END,
      'is_derived', h.is_derived, 'derivation', h.derivation,
      'valid_until', TO_VARCHAR(h.valid_until, 'YYYY-MM-DD"T"HH24:MI:SS'),
      'event_time', TO_VARCHAR(h.event_time, 'YYYY-MM-DD"T"HH24:MI:SS'),
      'source_recorded_at', TO_VARCHAR(h.source_recorded_at, 'YYYY-MM-DD"T"HH24:MI:SS'),
      'ingested_at', TO_VARCHAR(h.ingested_at, 'YYYY-MM-DD"T"HH24:MI:SS'),
      'source_event_ids', IFF(h.is_derived, ARRAY_CONSTRUCT(), ARRAY_CONSTRUCT(h.event_id)),
      'source_assertion_ids', COALESCE(l.assertion_ids, ARRAY_CONSTRUCT()),
      'source_document_ids', COALESCE(l.doc_ids, ARRAY_CONSTRUCT()),
      'source_links_observed_at', :v_known_as_of_s))
      WITHIN GROUP (ORDER BY h.event_time DESC NULLS LAST, h.concept_name), ARRAY_CONSTRUCT())
    FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS h
    LEFT JOIN SAARTHI.CORE.CLINICAL_EVENT ce ON ce.event_id = h.event_id
    LEFT JOIN (SELECT el.target_id, ARRAY_AGG(DISTINCT a.assertion_id) assertion_ids,
                      ARRAY_AGG(DISTINCT a.doc_id) doc_ids
                 FROM SAARTHI.EVIDENCE.EVIDENCE_LINK el
                 JOIN SAARTHI.EVIDENCE.ASSERTION a ON a.assertion_id = el.assertion_id
                 JOIN SAARTHI.DOCUMENTS.DOCUMENT d ON d.doc_id = a.doc_id
                 JOIN SAARTHI.CORE.CLINICAL_EVENT source_event
                   ON source_event.event_id = el.target_id
                  AND source_event.patient_id = d.patient_id
                  AND source_event.concept_id = a.concept_id
                  AND source_event.unit = a.unit
                  AND source_event.value_num = TRY_TO_DOUBLE(REPLACE(a.value, ',', ''))
                WHERE el.relation = 'supports' AND d.status = 'active'
                  AND a.verification_status = 'verified'
                  AND a.missingness_state = 'present'
                  AND d.scope = 'patient'
                  AND d.patient_id = :v_patient_id
                  AND d.ingested_at <= :v_known_as_of
                GROUP BY el.target_id) l ON l.target_id = h.event_id
   WHERE h.patient_id = :v_patient_id AND h.event_type IN ('lab', 'vitals')
     AND h.ingested_at <= :v_known_as_of);
  RETURN OBJECT_CONSTRUCT('domain','labs','facts',v_facts,'known_as_of',v_known_as_of_s,
    'requested_known_as_of',v_requested,'as_of_semantics','ingested_cutoff','binding_id',v_binding_id);
ELSEIF (v_domain = 'demographics') THEN
  v_facts := (SELECT OBJECT_CONSTRUCT_KEEP_NULL('patient_id', patient_id, 'name', name,
      'dob', TO_VARCHAR(dob), 'gender', gender, 'district', district, 'state', state,
      'primary_language', primary_language)
    FROM SAARTHI.CORE.PATIENT WHERE patient_id = :v_patient_id);
ELSEIF (v_domain = 'coverage') THEN
  v_facts := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL('payer_name', payer_name,
      'annual_limit', annual_limit, 'used_amount', used_amount,
      'is_family_floater', is_family_floater)) WITHIN GROUP (ORDER BY priority, coverage_id),
      ARRAY_CONSTRUCT())
    FROM SAARTHI.CORE.COVERAGE WHERE patient_id = :v_patient_id);
ELSEIF (v_domain = 'treatment_plan') THEN
  v_facts := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL('version', version,
      'regimen_display', regimen_display, 'intent', intent,
      'decided_at', TO_VARCHAR(decided_at, 'YYYY-MM-DD"T"HH24:MI:SS')))
      WITHIN GROUP (ORDER BY version DESC), ARRAY_CONSTRUCT())
    FROM SAARTHI.CORE.TREATMENT_PLAN WHERE patient_id = :v_patient_id);
ELSEIF (v_domain = 'encounters') THEN
  v_facts := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL('encounter_id', encounter_id,
      'cycle_number', cycle_number, 'event_time', TO_VARCHAR(event_time, 'YYYY-MM-DD"T"HH24:MI:SS'),
      'gap_type', gap_type)) WITHIN GROUP (ORDER BY event_time, encounter_id), ARRAY_CONSTRUCT())
    FROM SAARTHI.CORE.ENCOUNTER WHERE patient_id = :v_patient_id);
ELSEIF (v_domain = 'identity') THEN
  v_facts := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL('source_system', source_system,
      'link_status', link_status)) WITHIN GROUP (ORDER BY source_system), ARRAY_CONSTRUCT())
    FROM SAARTHI.CORE.ID_MAP WHERE patient_id = :v_patient_id);
ELSE
  RETURN OBJECT_CONSTRUCT('error','invalid_argument','known_as_of',:v_known_as_of_s);
END IF;
RETURN OBJECT_CONSTRUCT('domain',v_domain,'facts',COALESCE(v_facts, OBJECT_CONSTRUCT()),
  'known_as_of',TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD"T"HH24:MI:SS'),
  'requested_known_as_of',v_requested,'as_of_semantics','current_at_query','binding_id',v_binding_id);
ELSEIF (VIEW_NAME = 'coverage_comparison') THEN
-- Authorization rows have no ingestion clock, so they are current at query; letters are
-- limited to documents received by the cutoff. ARGUMENT carries that cutoff.
IF (ARGUMENT IS NOT NULL) THEN
  v_known_as_of := TRY_TO_TIMESTAMP_NTZ(:ARGUMENT, 'YYYY-MM-DD"T"HH24:MI:SS');
  IF (v_known_as_of IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('error','invalid_argument','known_as_of',:v_known_as_of_s);
  END IF;
  v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');
END IF;
IF (COALESCE(ARRAY_CONTAINS('financial'::VARIANT,
    (SELECT data_categories FROM SAARTHI.GOVERNANCE.CONSENT WHERE consent_id = :v_consent_id)), FALSE) = FALSE) THEN
  RETURN OBJECT_CONSTRUCT('error','consent_not_valid','known_as_of',:v_known_as_of_s);
END IF;
LET v_auths ARRAY := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(
    'auth_id', a.auth_id, 'status', a.status, 'letter_status', a.letter_status,
    'payer_name', c.payer_name,
    'requested_at', TO_VARCHAR(a.requested_at, 'YYYY-MM-DD"T"HH24:MI:SS'),
    'decided_at', TO_VARCHAR(a.decided_at, 'YYYY-MM-DD"T"HH24:MI:SS'),
    'expires_at', TO_VARCHAR(a.expires_at, 'YYYY-MM-DD"T"HH24:MI:SS')))
    WITHIN GROUP (ORDER BY a.decided_at DESC NULLS LAST, a.requested_at DESC NULLS LAST, a.auth_id),
    ARRAY_CONSTRUCT())
  FROM (SELECT * FROM SAARTHI.CORE.AUTHORIZATION WHERE patient_id = :v_patient_id
         ORDER BY decided_at DESC NULLS LAST, requested_at DESC NULLS LAST, auth_id LIMIT 21) a
  LEFT JOIN SAARTHI.CORE.COVERAGE c ON c.coverage_id = a.coverage_id);
LET v_letters ARRAY := (SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT_KEEP_NULL(
    'assertion_id', l.assertion_id, 'predicate', l.predicate, 'value', l.value,
    'verification_status', l.verification_status, 'doc_id', l.doc_id, 'doc_type', l.doc_type,
    'page_index', l.page_index, 'char_start', l.char_start, 'char_end', l.char_end,
    'source_link_status', l.source_link_status, 'excerpt_start', l.excerpt_start,
    'excerpt', IFF(l.source_link_status = 'verified_assertion_exact_page_span',
      SUBSTR(l.text, l.excerpt_start + 1, l.char_end - l.excerpt_start + 120), NULL),
    'source_facility', l.source_facility, 'event_time', l.event_time,
    'source_recorded_at', l.source_recorded_at, 'ingested_at', l.ingested_at))
    WITHIN GROUP (ORDER BY l.ingested_at DESC, l.assertion_id), ARRAY_CONSTRUCT())
  FROM (SELECT a.assertion_id, a.predicate, a.value, a.verification_status, a.doc_id, d.doc_type,
               a.page_index, a.char_start, a.char_end, dp.text, f.name AS source_facility,
               GREATEST(COALESCE(a.char_start, 0) - 120, 0) AS excerpt_start,
               IFF(a.verification_status = 'verified' AND dp.doc_id IS NOT NULL
                   AND a.char_start >= 0 AND a.char_end > a.char_start
                   AND a.char_end <= LENGTH(dp.text),
                   'verified_assertion_exact_page_span', 'span_unavailable') AS source_link_status,
               TO_VARCHAR(d.effective_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS event_time,
               TO_VARCHAR(d.signed_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS source_recorded_at,
               TO_VARCHAR(d.ingested_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS ingested_at
          FROM SAARTHI.EVIDENCE.ASSERTION a
          JOIN SAARTHI.DOCUMENTS.DOCUMENT d ON d.doc_id = a.doc_id
          LEFT JOIN SAARTHI.DOCUMENTS.DOC_PAGE dp
            ON dp.doc_id = a.doc_id AND dp.page_index = a.page_index
          LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id = d.source_facility_id
         WHERE d.patient_id = :v_patient_id AND d.scope = 'patient' AND d.status = 'active'
           AND d.doc_type = 'authorization_letter' AND d.ingested_at <= :v_known_as_of
         ORDER BY d.ingested_at DESC, a.assertion_id LIMIT 21) l);
LET v_rule VARIANT := (WITH ranked_encounters AS (
    SELECT e.encounter_id, ROW_NUMBER() OVER (ORDER BY
      IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), 0, 1),
      IFF(e.scheduled_time >= CURRENT_TIMESTAMP(), e.scheduled_time, NULL) ASC NULLS LAST,
      IFF(e.scheduled_time < CURRENT_TIMESTAMP(), e.scheduled_time, NULL) DESC NULLS LAST) AS visit_rank
      FROM SAARTHI.CORE.ENCOUNTER e
     WHERE e.patient_id = :v_patient_id AND e.encounter_type = 'daycare')
  SELECT OBJECT_CONSTRUCT_KEEP_NULL('rule_id', rs.rule_id, 'rule_version', rs.rule_version,
      'outcome', rs.outcome, 'reason', rs.reason,
      'known_as_of', TO_VARCHAR(rs.known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS'))
    FROM SAARTHI.OPERATIONAL.READINESS_STATE rs
    JOIN ranked_encounters e ON e.encounter_id = rs.encounter_id AND e.visit_rank = 1
   WHERE rs.patient_id = :v_patient_id AND rs.rule_id = 'COV-AUTH-001' LIMIT 1);
RETURN OBJECT_CONSTRUCT('rows', ARRAY_CONSTRUCT(OBJECT_CONSTRUCT_KEEP_NULL(
    'known_as_of', v_known_as_of_s, 'requested_known_as_of', :ARGUMENT,
    'as_of_semantics', 'authorization_current_at_query_document_ingestion_cutoff',
    'observed_at', TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    'authorizations_truncated', ARRAY_SIZE(v_auths) > 20,
    'letters_truncated', ARRAY_SIZE(v_letters) > 20,
    'rule', v_rule,
    'authorizations', ARRAY_SLICE(v_auths, 0, 20),
    'letters', ARRAY_SLICE(v_letters, 0, 20))),
  'known_as_of', v_known_as_of_s, 'binding_id', v_binding_id);
ELSE RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
RETURN OBJECT_CONSTRUCT('rows',v_rows,'known_as_of',v_known_as_of_s,'binding_id',v_binding_id);
END;
$$;
-- ===== END procedures/web_reads.sql =====

-- ===== BEGIN procedures/web_workflows.sql =====
-- Human task lifecycle only. Uses existing REVIEW_ISSUE.version for optimistic locking.
-- REVIEW_TASK keeps append-only action receipts (web-event:<target>:<request>),
-- while the original task row is the current projection. Receipts are excluded from queues.
CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.UPDATE_WEB_REVIEW_TASK(
TASK_REF VARCHAR, ACTION VARCHAR, NEW_OWNER VARCHAR, NOTE VARCHAR, EXPECTED_VERSION INTEGER, REQUEST_KEY VARCHAR)
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS $$
DECLARE KNOWN_AS_OF VARCHAR DEFAULT NULL;
v_known_as_of TIMESTAMP_NTZ; v_known_as_of_s VARCHAR; v_binding_id VARCHAR;
v_patient_id VARCHAR; v_practitioner VARCHAR; v_care_team_id VARCHAR; v_consent_id VARCHAR;

v_issue VARCHAR; v_owner VARCHAR; v_state VARCHAR; v_next_state VARCHAR; v_receipt VARCHAR; v_changed INTEGER;
BEGIN
-- >>> SAARTHI PREAMBLE v1 BEGIN
    -- 0 -- KNOWN_AS_OF. Resolved before anything can fail, so every error carries it.
    v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:KNOWN_AS_OF), CURRENT_TIMESTAMP());
    v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');

    -- 1 -- SELECTION. The subject comes from a human click, never from question text.
    v_binding_id := (SELECT binding_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE session_id = CURRENT_SESSION()
                        AND released_at IS NULL
                      ORDER BY bound_at DESC
                      LIMIT 1);
    IF (v_binding_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_bound',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_patient_id := (SELECT patient_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE binding_id = :v_binding_id);

    -- 2 -- AUTHORISATION. CURRENT_USER() survives owner's-rights elevation; CURRENT_ROLE() does not (F3).
    v_practitioner := (SELECT practitioner_id
                         FROM SAARTHI.GOVERNANCE.PRACTITIONER
                        WHERE snowflake_user = CURRENT_USER()
                          AND active = TRUE);
    IF (v_practitioner IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_care_team_id := (SELECT care_team_id
                         FROM SAARTHI.GOVERNANCE.CARE_TEAM
                        WHERE practitioner_id = :v_practitioner
                          AND patient_id     = :v_patient_id
                          AND role_type IN ('treating', 'coordinator')
                          AND active_from   <= CURRENT_DATE()
                          AND (active_to IS NULL OR active_to >= CURRENT_DATE())
                        ORDER BY active_from DESC
                        LIMIT 1);
    IF (v_care_team_id IS NULL) THEN
        -- Reveals nothing about whether the patient exists. Do not add a reason.
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    -- 3 -- CONSENT, at query time. Never at ingest, never cached in the binding.
    v_consent_id := (SELECT c.consent_id
                       FROM SAARTHI.GOVERNANCE.CONSENT c
                       JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
                         ON p.practitioner_id = :v_practitioner
                       LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f
                         ON f.facility_id = p.facility_id
                      WHERE c.patient_id = :v_patient_id
                        AND c.status     = 'active'
                        AND c.valid_from <= CURRENT_TIMESTAMP()
                        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
                        AND c.purpose_code IN ('treatment', 'coordination')
                        AND (c.granted_to_facility_id = p.facility_id
                          OR c.granted_to_org_id      = f.org_id)
                      ORDER BY c.valid_from DESC
                      LIMIT 1);
    IF (v_consent_id IS NULL) THEN
        -- Release the binding: the context is cleared, not merely hidden.
        UPDATE SAARTHI.GOVERNANCE.PATIENT_BINDING
           SET released_at = CURRENT_TIMESTAMP()
         WHERE binding_id = :v_binding_id
           AND released_at IS NULL;
        -- This code DOES reveal that a record exists. That is deliberate: it only
        -- reaches a user who previously had legitimate access to it.
        RETURN OBJECT_CONSTRUCT('error', 'access_withdrawn',
                                'known_as_of', :v_known_as_of_s);
    END IF;
-- <<< SAARTHI PREAMBLE v1 END
IF (NOT EXISTS (SELECT 1 FROM SAARTHI.GOVERNANCE.CARE_TEAM WHERE care_team_id=:v_care_team_id AND role_type IN ('treating','coordinator'))) THEN RETURN OBJECT_CONSTRUCT('error','no_patient_access'); END IF;
IF (ACTION IS NULL OR ACTION NOT IN ('acknowledge','reassign','resolve') OR NOTE IS NULL OR LENGTH(TRIM(NOTE))<3 OR LENGTH(NOTE)>2000 OR EXPECTED_VERSION IS NULL OR EXPECTED_VERSION<0 OR REQUEST_KEY IS NULL OR LENGTH(REQUEST_KEY)>80 OR LENGTH(REQUEST_KEY)<8) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
SELECT rt.issue_id, rt.owner_practitioner_id, rt.state INTO :v_issue,:v_owner,:v_state
FROM SAARTHI.OPERATIONAL.REVIEW_TASK rt WHERE rt.task_id=:TASK_REF AND rt.idempotency_key NOT LIKE 'web-event:%'
AND (EXISTS (SELECT 1 FROM SAARTHI.OPERATIONAL.REVIEW_ISSUE ri WHERE ri.issue_id=rt.issue_id AND ri.patient_id=:v_patient_id)
 OR EXISTS (SELECT 1 FROM SAARTHI.OPERATIONAL.READINESS_STATE rs WHERE rs.patient_id=:v_patient_id AND rs.patient_id||':'||rs.rule_id=rt.issue_id));
IF (v_issue IS NULL) THEN RETURN OBJECT_CONSTRUCT('error','binding_mismatch'); END IF;
v_receipt := 'web-event:'||TASK_REF||':'||REQUEST_KEY;
IF (EXISTS (SELECT 1 FROM SAARTHI.OPERATIONAL.REVIEW_TASK WHERE idempotency_key=:v_receipt AND actor_practitioner_id=:v_practitioner AND decision=:ACTION AND reason=:NOTE AND (:ACTION!='reassign' OR owner_practitioner_id=:NEW_OWNER))) THEN RETURN OBJECT_CONSTRUCT('task_id',TASK_REF,'idempotent_replay',TRUE); END IF;
IF (EXISTS (SELECT 1 FROM SAARTHI.OPERATIONAL.REVIEW_TASK WHERE idempotency_key=:v_receipt)) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
IF (v_state IS NULL OR v_state IN ('resolved','closed','cancelled') OR (ACTION='acknowledge' AND v_state!='open')) THEN RETURN OBJECT_CONSTRUCT('error','invalid_transition'); END IF;
IF (ACTION='reassign') THEN
 IF (NEW_OWNER IS NULL OR NOT EXISTS (
 SELECT 1 FROM SAARTHI.GOVERNANCE.CARE_TEAM ct
JOIN SAARTHI.GOVERNANCE.PRACTITIONER p ON p.practitioner_id=ct.practitioner_id
LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f ON f.facility_id=p.facility_id
WHERE ct.patient_id=:v_patient_id AND p.active=TRUE AND ct.role_type IN ('treating','coordinator')
AND ct.active_from<=CURRENT_DATE() AND (ct.active_to IS NULL OR ct.active_to>=CURRENT_DATE())
AND EXISTS (SELECT 1 FROM SAARTHI.GOVERNANCE.CONSENT c WHERE c.patient_id=ct.patient_id
AND c.status='active' AND c.valid_from<=CURRENT_TIMESTAMP() AND (c.valid_until IS NULL OR c.valid_until>=CURRENT_TIMESTAMP())
AND c.purpose_code IN ('treatment','coordination') AND (c.granted_to_facility_id=p.facility_id OR c.granted_to_org_id=f.org_id))
AND p.practitioner_id=:NEW_OWNER
 )) THEN RETURN OBJECT_CONSTRUCT('error','owner_not_authorized'); END IF;
 v_owner := NEW_OWNER;
END IF;
v_next_state := CASE WHEN ACTION='acknowledge' THEN 'acknowledged' WHEN ACTION='resolve' THEN 'resolved' ELSE v_state END;
BEGIN TRANSACTION;
-- Upgrade the existing patient:rule identifier into its specified issue row; no new patient or rule.
MERGE INTO SAARTHI.OPERATIONAL.REVIEW_ISSUE t USING (
 SELECT :v_issue AS issue_id,rs.* FROM SAARTHI.OPERATIONAL.READINESS_STATE rs
 WHERE rs.patient_id=:v_patient_id AND rs.patient_id||':'||rs.rule_id=:v_issue
 QUALIFY ROW_NUMBER() OVER (ORDER BY rs.known_as_of DESC,rs.encounter_id)=1
) s ON t.issue_id=s.issue_id
WHEN NOT MATCHED THEN INSERT(issue_id,rule_id,rule_version,patient_id,encounter_id,gate,state,outcome,reason,evidence_ids,severity,version)
VALUES(s.issue_id,s.rule_id,s.rule_version,s.patient_id,s.encounter_id,s.gate,'open',s.outcome,s.reason,s.evidence_ids,s.severity,0);
UPDATE SAARTHI.OPERATIONAL.REVIEW_ISSUE SET version=version+1 WHERE issue_id=:v_issue AND patient_id=:v_patient_id AND version=:EXPECTED_VERSION;
v_changed := SQLROWCOUNT;
IF (v_changed!=1) THEN ROLLBACK; RETURN OBJECT_CONSTRUCT('error','stale_task'); END IF;
UPDATE SAARTHI.OPERATIONAL.REVIEW_TASK SET owner_practitioner_id=:v_owner,state=:v_next_state
WHERE task_id=:TASK_REF AND state=:v_state;
v_changed := SQLROWCOUNT;
IF (v_changed!=1) THEN ROLLBACK; RETURN OBJECT_CONSTRUCT('error','stale_task'); END IF;
INSERT INTO SAARTHI.OPERATIONAL.REVIEW_TASK(task_id,issue_id,owner_practitioner_id,state,decision,reason,actor_practitioner_id,idempotency_key)
SELECT UUID_STRING(),:v_issue,:v_owner,:v_next_state,:ACTION,:NOTE,:v_practitioner,:v_receipt;
-- Keep the issue consistent with its tasks: when the last open work item on an issue is
-- resolved the issue closes; it never stays 'open' behind an all-resolved task list.
UPDATE SAARTHI.OPERATIONAL.REVIEW_ISSUE SET state='closed'
WHERE issue_id=:v_issue AND patient_id=:v_patient_id AND :ACTION='resolve'
AND NOT EXISTS (SELECT 1 FROM SAARTHI.OPERATIONAL.REVIEW_TASK rt2 WHERE rt2.issue_id=:v_issue
  AND rt2.idempotency_key NOT LIKE 'web-event:%' AND rt2.state IN ('open','acknowledged'));
COMMIT;
RETURN OBJECT_CONSTRUCT('task_id',TASK_REF,'state',v_next_state,'version',EXPECTED_VERSION+1,'idempotent_replay',FALSE);
EXCEPTION WHEN OTHER THEN
 ROLLBACK;
 RAISE;
END;
$$;

-- On-demand, one bound patient/visit; no AI and no scheduled refresh.
CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.REFRESH_BOUND_READINESS()
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS $$
DECLARE KNOWN_AS_OF VARCHAR DEFAULT NULL;
v_known_as_of TIMESTAMP_NTZ; v_known_as_of_s VARCHAR; v_binding_id VARCHAR;
v_patient_id VARCHAR; v_practitioner VARCHAR; v_care_team_id VARCHAR; v_consent_id VARCHAR;

v_encounter_id VARCHAR; v_gates_response VARIANT;
BEGIN
-- >>> SAARTHI PREAMBLE v1 BEGIN
    -- 0 -- KNOWN_AS_OF. Resolved before anything can fail, so every error carries it.
    v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:KNOWN_AS_OF), CURRENT_TIMESTAMP());
    v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');

    -- 1 -- SELECTION. The subject comes from a human click, never from question text.
    v_binding_id := (SELECT binding_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE session_id = CURRENT_SESSION()
                        AND released_at IS NULL
                      ORDER BY bound_at DESC
                      LIMIT 1);
    IF (v_binding_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_bound',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_patient_id := (SELECT patient_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE binding_id = :v_binding_id);

    -- 2 -- AUTHORISATION. CURRENT_USER() survives owner's-rights elevation; CURRENT_ROLE() does not (F3).
    v_practitioner := (SELECT practitioner_id
                         FROM SAARTHI.GOVERNANCE.PRACTITIONER
                        WHERE snowflake_user = CURRENT_USER()
                          AND active = TRUE);
    IF (v_practitioner IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_care_team_id := (SELECT care_team_id
                         FROM SAARTHI.GOVERNANCE.CARE_TEAM
                        WHERE practitioner_id = :v_practitioner
                          AND patient_id     = :v_patient_id
                          AND role_type IN ('treating', 'coordinator')
                          AND active_from   <= CURRENT_DATE()
                          AND (active_to IS NULL OR active_to >= CURRENT_DATE())
                        ORDER BY active_from DESC
                        LIMIT 1);
    IF (v_care_team_id IS NULL) THEN
        -- Reveals nothing about whether the patient exists. Do not add a reason.
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    -- 3 -- CONSENT, at query time. Never at ingest, never cached in the binding.
    v_consent_id := (SELECT c.consent_id
                       FROM SAARTHI.GOVERNANCE.CONSENT c
                       JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
                         ON p.practitioner_id = :v_practitioner
                       LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f
                         ON f.facility_id = p.facility_id
                      WHERE c.patient_id = :v_patient_id
                        AND c.status     = 'active'
                        AND c.valid_from <= CURRENT_TIMESTAMP()
                        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
                        AND c.purpose_code IN ('treatment', 'coordination')
                        AND (c.granted_to_facility_id = p.facility_id
                          OR c.granted_to_org_id      = f.org_id)
                      ORDER BY c.valid_from DESC
                      LIMIT 1);
    IF (v_consent_id IS NULL) THEN
        -- Release the binding: the context is cleared, not merely hidden.
        UPDATE SAARTHI.GOVERNANCE.PATIENT_BINDING
           SET released_at = CURRENT_TIMESTAMP()
         WHERE binding_id = :v_binding_id
           AND released_at IS NULL;
        -- This code DOES reveal that a record exists. That is deliberate: it only
        -- reaches a user who previously had legitimate access to it.
        RETURN OBJECT_CONSTRUCT('error', 'access_withdrawn',
                                'known_as_of', :v_known_as_of_s);
    END IF;
-- <<< SAARTHI PREAMBLE v1 END
v_encounter_id := (SELECT encounter_id FROM SAARTHI.CORE.ENCOUNTER WHERE patient_id=:v_patient_id AND encounter_type='daycare'
ORDER BY IFF(scheduled_time>=CURRENT_TIMESTAMP(),0,1),
IFF(scheduled_time>=CURRENT_TIMESTAMP(),scheduled_time,NULL) ASC NULLS LAST,
IFF(scheduled_time<CURRENT_TIMESTAMP(),scheduled_time,NULL) DESC NULLS LAST,encounter_id LIMIT 1);
IF (v_encounter_id IS NULL) THEN RETURN OBJECT_CONSTRUCT('error','no_encounter'); END IF;
v_gates_response := (CALL SAARTHI.OPERATIONAL.GET_READINESS(:v_encounter_id,:v_known_as_of_s));
IF (v_gates_response:error IS NOT NULL OR NOT IS_ARRAY(v_gates_response:gates)) THEN RETURN OBJECT_CONSTRUCT('error','readiness_unavailable'); END IF;
        MERGE INTO SAARTHI.OPERATIONAL.READINESS_STATE t
        USING (
            SELECT :v_patient_id AS patient_id,
                   :v_encounter_id AS encounter_id,
                   g.value:gate::VARCHAR         AS gate,
                   g.value:rule_id::VARCHAR      AS rule_id,
                   g.value:rule_version::INTEGER AS rule_version,
                   g.value:outcome::VARCHAR      AS outcome,
                   g.value:severity::VARCHAR     AS severity,
                   g.value:reason::VARCHAR       AS reason,
                   g.value:evidence_ids          AS evidence_ids,
                   TRY_TO_TIMESTAMP_NTZ(g.value:known_as_of::VARCHAR) AS known_as_of
              FROM TABLE(FLATTEN(input => :v_gates_response:gates)) g
        ) s
        ON t.patient_id = s.patient_id
           AND t.encounter_id = s.encounter_id
           AND t.rule_id = s.rule_id
           AND t.gate = s.gate
        WHEN MATCHED THEN UPDATE SET
            t.rule_version = s.rule_version,
            t.outcome = s.outcome,
            t.severity = s.severity,
            t.reason = s.reason,
            t.evidence_ids = s.evidence_ids,
            t.known_as_of = s.known_as_of,
            t.computed_at = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (
            patient_id, encounter_id, gate, rule_id, rule_version,
            outcome, severity, reason, evidence_ids, known_as_of, computed_at
        ) VALUES (
            s.patient_id, s.encounter_id, s.gate, s.rule_id, s.rule_version,
            s.outcome, s.severity, s.reason, s.evidence_ids, s.known_as_of, CURRENT_TIMESTAMP()
        );
-- Snapshot, not history: drop rules the evaluator no longer returns for this encounter
-- (e.g. a rule version rescoped away). Skipped when the evaluation failed, so an error can
-- never erase readiness. NOT IN over a NULL key matches nothing: also fails closed.
IF (v_gates_response:error IS NULL AND ARRAY_SIZE(v_gates_response:gates) > 0) THEN
    DELETE FROM SAARTHI.OPERATIONAL.READINESS_STATE
     WHERE patient_id = :v_patient_id
       AND encounter_id = :v_encounter_id
       AND rule_id || ':' || rule_version::VARCHAR NOT IN (
           SELECT g.value:rule_id::VARCHAR || ':' || g.value:rule_version::INTEGER::VARCHAR
             FROM TABLE(FLATTEN(input => :v_gates_response:gates)) g);
END IF;
RETURN v_gates_response;
END;
$$;
-- ===== END procedures/web_workflows.sql =====

-- ===== BEGIN procedures/web_evidence.sql =====
-- Pointer-only answer audit, re-authorized in the same patient binding as the answer.
CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.RECORD_WEB_ANSWER(QUESTION VARCHAR, AS_OF VARCHAR, EVIDENCE_IDS ARRAY, RUN_REF VARCHAR, ANSWER_STATE VARCHAR)
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS $$
DECLARE KNOWN_AS_OF VARCHAR DEFAULT NULL;
v_known_as_of TIMESTAMP_NTZ; v_known_as_of_s VARCHAR; v_binding_id VARCHAR;
v_patient_id VARCHAR; v_practitioner VARCHAR; v_care_team_id VARCHAR; v_consent_id VARCHAR;
v_class VARIANT; v_ids ARRAY; v_id VARCHAR; v_status VARCHAR;
v_pointer_claims ARRAY; v_checked_pointers VARIANT; v_extra_ids ARRAY;
BEGIN
-- >>> SAARTHI PREAMBLE v1 BEGIN
    -- 0 -- KNOWN_AS_OF. Resolved before anything can fail, so every error carries it.
    v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:KNOWN_AS_OF), CURRENT_TIMESTAMP());
    v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');

    -- 1 -- SELECTION. The subject comes from a human click, never from question text.
    v_binding_id := (SELECT binding_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE session_id = CURRENT_SESSION()
                        AND released_at IS NULL
                      ORDER BY bound_at DESC
                      LIMIT 1);
    IF (v_binding_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_bound',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_patient_id := (SELECT patient_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE binding_id = :v_binding_id);

    -- 2 -- AUTHORISATION. CURRENT_USER() survives owner's-rights elevation; CURRENT_ROLE() does not (F3).
    v_practitioner := (SELECT practitioner_id
                         FROM SAARTHI.GOVERNANCE.PRACTITIONER
                        WHERE snowflake_user = CURRENT_USER()
                          AND active = TRUE);
    IF (v_practitioner IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_care_team_id := (SELECT care_team_id
                         FROM SAARTHI.GOVERNANCE.CARE_TEAM
                        WHERE practitioner_id = :v_practitioner
                          AND patient_id     = :v_patient_id
                          AND role_type IN ('treating', 'coordinator')
                          AND active_from   <= CURRENT_DATE()
                          AND (active_to IS NULL OR active_to >= CURRENT_DATE())
                        ORDER BY active_from DESC
                        LIMIT 1);
    IF (v_care_team_id IS NULL) THEN
        -- Reveals nothing about whether the patient exists. Do not add a reason.
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    -- 3 -- CONSENT, at query time. Never at ingest, never cached in the binding.
    v_consent_id := (SELECT c.consent_id
                       FROM SAARTHI.GOVERNANCE.CONSENT c
                       JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
                         ON p.practitioner_id = :v_practitioner
                       LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f
                         ON f.facility_id = p.facility_id
                      WHERE c.patient_id = :v_patient_id
                        AND c.status     = 'active'
                        AND c.valid_from <= CURRENT_TIMESTAMP()
                        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
                        AND c.purpose_code IN ('treatment', 'coordination')
                        AND (c.granted_to_facility_id = p.facility_id
                          OR c.granted_to_org_id      = f.org_id)
                      ORDER BY c.valid_from DESC
                      LIMIT 1);
    IF (v_consent_id IS NULL) THEN
        -- Release the binding: the context is cleared, not merely hidden.
        UPDATE SAARTHI.GOVERNANCE.PATIENT_BINDING
           SET released_at = CURRENT_TIMESTAMP()
         WHERE binding_id = :v_binding_id
           AND released_at IS NULL;
        -- This code DOES reveal that a record exists. That is deliberate: it only
        -- reaches a user who previously had legitimate access to it.
        RETURN OBJECT_CONSTRUCT('error', 'access_withdrawn',
                                'known_as_of', :v_known_as_of_s);
    END IF;
-- <<< SAARTHI PREAMBLE v1 END
IF (QUESTION IS NULL OR LENGTH(QUESTION)>4000 OR RUN_REF IS NULL OR LENGTH(RUN_REF)>80 OR ARRAY_SIZE(EVIDENCE_IDS)>100) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
v_class := (CALL SAARTHI.OPERATIONAL.CLASSIFY_QUESTION(:QUESTION));
IF (v_class:classification::VARCHAR NOT IN ('CLASS_A','CLASS_B') OR v_class:classification IS NULL) THEN RETURN OBJECT_CONSTRUCT('error','classification_unavailable'); END IF;
v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:AS_OF),v_known_as_of);
SELECT COALESCE(ARRAY_AGG(DISTINCT id),ARRAY_CONSTRUCT()) INTO :v_ids FROM (
 SELECT e.event_id AS id FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS e WHERE e.patient_id=:v_patient_id AND e.ingested_at<=:v_known_as_of AND ARRAY_CONTAINS(e.event_id::VARIANT,:EVIDENCE_IDS)
 UNION
 SELECT a.assertion_id FROM SAARTHI.EVIDENCE.ASSERTION a JOIN SAARTHI.DOCUMENTS.DOCUMENT d ON d.doc_id=a.doc_id
 WHERE d.patient_id=:v_patient_id AND d.scope='patient' AND d.status='active' AND d.ingested_at<=:v_known_as_of
 AND a.verification_status='verified' AND ARRAY_CONTAINS(a.assertion_id::VARIANT,:EVIDENCE_IDS)
);
SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT('text','Recorded source pointer',
    'claim_type','textual','evidence',ARRAY_CONSTRUCT(OBJECT_CONSTRUCT(
        'id',id,'kind',kind)))),ARRAY_CONSTRUCT()) INTO :v_pointer_claims
FROM (
    SELECT DISTINCT i.value::VARCHAR AS id,'structured' AS kind
      FROM TABLE(FLATTEN(input=>:EVIDENCE_IDS)) i
     WHERE STARTSWITH(i.value::VARCHAR,'ROW-') OR STARTSWITH(i.value::VARCHAR,'RULE--')
    UNION
    SELECT DISTINCT c.chunk_id AS id,'reference_clause' AS kind
      FROM TABLE(FLATTEN(input=>:EVIDENCE_IDS)) i
      JOIN SAARTHI.DOCUMENTS.DOC_CHUNK c ON c.chunk_id=i.value::VARCHAR
     WHERE c.doc_scope='reference' AND c.patient_id IS NULL
);
IF (ARRAY_SIZE(v_pointer_claims)>0) THEN
    v_checked_pointers := (CALL SAARTHI.OPERATIONAL.VALIDATE_ANSWER(:v_pointer_claims,
        TO_VARCHAR(:v_known_as_of,'YYYY-MM-DD"T"HH24:MI:SS')));
    IF (v_checked_pointers:error IS NOT NULL) THEN RETURN v_checked_pointers; END IF;
    SELECT COALESCE(ARRAY_AGG(DISTINCT e.value:id::VARCHAR),ARRAY_CONSTRUCT())
      INTO :v_extra_ids
      FROM TABLE(FLATTEN(input=>:v_checked_pointers:claims)) c,
           LATERAL FLATTEN(input=>c.value:evidence) e;
    v_ids := ARRAY_DISTINCT(ARRAY_CAT(v_ids,v_extra_ids));
END IF;
v_status := CASE WHEN v_class:classification::VARCHAR='CLASS_A' THEN 'refused' WHEN ANSWER_STATE='error' THEN 'error' ELSE 'recorded' END;
IF (EXISTS (SELECT 1 FROM SAARTHI.EVIDENCE.ANSWER_RUN WHERE run_id=:RUN_REF AND (patient_id!=:v_patient_id OR practitioner_id!=:v_practitioner))) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
MERGE INTO SAARTHI.EVIDENCE.ANSWER_RUN t USING (SELECT :RUN_REF AS id) s ON t.run_id=s.id
WHEN NOT MATCHED THEN INSERT(run_id,question_class,practitioner_id,patient_id,consent_id,known_as_of,answer_status,evidence_ids,model_version,validation_results)
VALUES(s.id,IFF(:v_class:classification::VARCHAR='CLASS_A','A','B'),:v_practitioner,:v_patient_id,:v_consent_id,:v_known_as_of,:v_status,:v_ids,'web-source-pointers@1',OBJECT_CONSTRUCT('pointers_scope_checked',TRUE,'answer_text_retained',FALSE,'does_not_attest_model_prose',TRUE));
RETURN (SELECT OBJECT_CONSTRUCT('run_id',run_id,'status',answer_status,
    'known_as_of',TO_VARCHAR(known_as_of,'YYYY-MM-DD"T"HH24:MI:SS'))
    FROM SAARTHI.EVIDENCE.ANSWER_RUN
    WHERE run_id=:RUN_REF AND patient_id=:v_patient_id
      AND practitioner_id=:v_practitioner);
END;
$$;

CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.PREPARE_WEB_PACKET(QUESTION VARCHAR, PACKET_REF VARCHAR)
RETURNS VARIANT LANGUAGE SQL EXECUTE AS OWNER AS $$
DECLARE KNOWN_AS_OF VARCHAR DEFAULT NULL;
v_known_as_of TIMESTAMP_NTZ; v_known_as_of_s VARCHAR; v_binding_id VARCHAR;
v_patient_id VARCHAR; v_practitioner VARCHAR; v_care_team_id VARCHAR; v_consent_id VARCHAR;
v_class VARIANT; v_recipient VARCHAR; v_name VARCHAR; v_gates VARIANT; v_ids ARRAY;
BEGIN
-- >>> SAARTHI PREAMBLE v1 BEGIN
    -- 0 -- KNOWN_AS_OF. Resolved before anything can fail, so every error carries it.
    v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:KNOWN_AS_OF), CURRENT_TIMESTAMP());
    v_known_as_of_s := TO_VARCHAR(:v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS');

    -- 1 -- SELECTION. The subject comes from a human click, never from question text.
    v_binding_id := (SELECT binding_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE session_id = CURRENT_SESSION()
                        AND released_at IS NULL
                      ORDER BY bound_at DESC
                      LIMIT 1);
    IF (v_binding_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_bound',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_patient_id := (SELECT patient_id
                       FROM SAARTHI.GOVERNANCE.PATIENT_BINDING
                      WHERE binding_id = :v_binding_id);

    -- 2 -- AUTHORISATION. CURRENT_USER() survives owner's-rights elevation; CURRENT_ROLE() does not (F3).
    v_practitioner := (SELECT practitioner_id
                         FROM SAARTHI.GOVERNANCE.PRACTITIONER
                        WHERE snowflake_user = CURRENT_USER()
                          AND active = TRUE);
    IF (v_practitioner IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    v_care_team_id := (SELECT care_team_id
                         FROM SAARTHI.GOVERNANCE.CARE_TEAM
                        WHERE practitioner_id = :v_practitioner
                          AND patient_id     = :v_patient_id
                          AND role_type IN ('treating', 'coordinator')
                          AND active_from   <= CURRENT_DATE()
                          AND (active_to IS NULL OR active_to >= CURRENT_DATE())
                        ORDER BY active_from DESC
                        LIMIT 1);
    IF (v_care_team_id IS NULL) THEN
        -- Reveals nothing about whether the patient exists. Do not add a reason.
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access',
                                'known_as_of', :v_known_as_of_s);
    END IF;

    -- 3 -- CONSENT, at query time. Never at ingest, never cached in the binding.
    v_consent_id := (SELECT c.consent_id
                       FROM SAARTHI.GOVERNANCE.CONSENT c
                       JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
                         ON p.practitioner_id = :v_practitioner
                       LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f
                         ON f.facility_id = p.facility_id
                      WHERE c.patient_id = :v_patient_id
                        AND c.status     = 'active'
                        AND c.valid_from <= CURRENT_TIMESTAMP()
                        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
                        AND c.purpose_code IN ('treatment', 'coordination')
                        AND (c.granted_to_facility_id = p.facility_id
                          OR c.granted_to_org_id      = f.org_id)
                      ORDER BY c.valid_from DESC
                      LIMIT 1);
    IF (v_consent_id IS NULL) THEN
        -- Release the binding: the context is cleared, not merely hidden.
        UPDATE SAARTHI.GOVERNANCE.PATIENT_BINDING
           SET released_at = CURRENT_TIMESTAMP()
         WHERE binding_id = :v_binding_id
           AND released_at IS NULL;
        -- This code DOES reveal that a record exists. That is deliberate: it only
        -- reaches a user who previously had legitimate access to it.
        RETURN OBJECT_CONSTRUCT('error', 'access_withdrawn',
                                'known_as_of', :v_known_as_of_s);
    END IF;
-- <<< SAARTHI PREAMBLE v1 END
IF (QUESTION IS NULL OR LENGTH(QUESTION)>4000 OR PACKET_REF IS NULL OR LENGTH(PACKET_REF)>80) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
IF (NOT EXISTS (SELECT 1 FROM SAARTHI.GOVERNANCE.CARE_TEAM WHERE care_team_id=:v_care_team_id AND role_type IN ('treating','coordinator'))) THEN RETURN OBJECT_CONSTRUCT('error','no_patient_access'); END IF;
v_class := (CALL SAARTHI.OPERATIONAL.CLASSIFY_QUESTION(:QUESTION));
IF (COALESCE(v_class:classification::VARCHAR,'')!='CLASS_A') THEN RETURN OBJECT_CONSTRUCT('error','clinical_referral_only'); END IF;
SELECT p.practitioner_id,p.name INTO :v_recipient,:v_name FROM SAARTHI.GOVERNANCE.CARE_TEAM ct
JOIN SAARTHI.GOVERNANCE.PRACTITIONER p ON p.practitioner_id=ct.practitioner_id
WHERE ct.patient_id=:v_patient_id AND ct.role_type='treating' AND p.active=TRUE
AND ct.active_from<=CURRENT_DATE() AND (ct.active_to IS NULL OR ct.active_to>=CURRENT_DATE())
ORDER BY ct.active_from DESC,p.practitioner_id LIMIT 1;
IF (v_recipient IS NULL) THEN RETURN OBJECT_CONSTRUCT('error','treating_practitioner_unavailable'); END IF;
IF (EXISTS (SELECT 1 FROM SAARTHI.EVIDENCE.EVIDENCE_PACKET WHERE packet_id=:PACKET_REF AND (patient_id!=:v_patient_id OR created_by_practitioner_id!=:v_practitioner))) THEN RETURN OBJECT_CONSTRUCT('error','invalid_argument'); END IF;
v_gates := (CALL SAARTHI.OPERATIONAL.GET_READINESS(NULL,NULL));
IF (v_gates:error IS NOT NULL OR NOT IS_ARRAY(v_gates:gates)) THEN RETURN OBJECT_CONSTRUCT('error','readiness_unavailable'); END IF;
SELECT COALESCE(ARRAY_AGG(DISTINCT e.value::VARCHAR),ARRAY_CONSTRUCT()) INTO :v_ids
FROM TABLE(FLATTEN(input=>:v_gates:gates)) g,LATERAL FLATTEN(input=>g.value:evidence_ids) e;
MERGE INTO SAARTHI.EVIDENCE.EVIDENCE_PACKET t USING (SELECT :PACKET_REF AS id) s ON t.packet_id=s.id
WHEN NOT MATCHED THEN INSERT(packet_id,patient_id,question,created_by_practitioner_id,evidence_ids,gate_snapshot,consent_id,delivered_to_practitioner_id,delivered_at)
VALUES(s.id,:v_patient_id,:QUESTION,:v_practitioner,:v_ids,:v_gates,:v_consent_id,:v_recipient,NULL);
RETURN (SELECT OBJECT_CONSTRUCT('packet_id',ep.packet_id,'practitioner_name',p.name,
    'practitioner',OBJECT_CONSTRUCT('practitioner_id',p.practitioner_id,'name',p.name,
        'nmc_registration_no',p.nmc_registration_no),
    'status',IFF(ep.delivered_at IS NULL,'prepared','delivered'),
    'known_as_of',ep.gate_snapshot:known_as_of,'gate_snapshot',ep.gate_snapshot,
    'evidence_ids',ep.evidence_ids,'delivered',ep.delivered_at IS NOT NULL)
    FROM SAARTHI.EVIDENCE.EVIDENCE_PACKET ep
    JOIN SAARTHI.GOVERNANCE.PRACTITIONER p ON p.practitioner_id=ep.delivered_to_practitioner_id
    WHERE ep.packet_id=:PACKET_REF AND ep.patient_id=:v_patient_id
      AND ep.created_by_practitioner_id=:v_practitioner);
END;
$$;
-- ===== END procedures/web_evidence.sql =====

-- VERIFY: expect one row per name, CREATED just now.
SELECT procedure_name, created FROM SAARTHI.INFORMATION_SCHEMA.PROCEDURES
 WHERE procedure_schema = 'OPERATIONAL' AND procedure_name IN ('GET_WEB_WORKSPACE', 'GET_WEB_PATIENT_DATA', 'UPDATE_WEB_REVIEW_TASK', 'REFRESH_BOUND_READINESS', 'RECORD_WEB_ANSWER', 'PREPARE_WEB_PACKET')
 ORDER BY 1;  -- expect 6 rows
