-- 02_gates_and_scheme_table.sql: gate evaluation, binding, scheme eligibility dynamic table
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;

-- ===== BEGIN procedures/evaluate_gates.sql =====
-- =============================================================================
-- STEP 14 - evaluate_gates (internal - never exposed to the agent)
-- =============================================================================
-- SPEC.md §4.4. The single source of truth for gate outcomes - R1: every
-- status, number, threshold comparison comes from this SQL, never the LLM.
-- A scheduled Task (step 16, TASK_REFRESH_READINESS) materialises the result
-- into READINESS_STATE; this procedure is what it calls.
--
-- This build implements THREE rule shapes:
--   (a) simple threshold - operator, value, unit, max_age_days in threshold_json.
--       Covers CLIN-ANC-001, CLIN-PLT-001, ENDO-HBA1C-001.
--   (b) freshness-only - concept + max_age_days but NO operator/value. Rule passes
--       if the event exists and is within max_age_days, fails otherwise. Covers
--       SURV-LVEF-001 and SURV-LVEF-002 (LVEF surveillance requires a recent
--       measurement; the rule does not gate on the absolute value).
--   (c) stratified (T-score bands) - bespoke evaluator for ENDO-DEXA-001. Bands
--       per NCCN v4.2024: T>=-1.0 -> 24-month interval; else -> 12-month interval.
--       QUS modality would surface as no T_SCORE row (different concept_id via
--       the ontology join), which the outer 'no evidence found' branch already
--       handles per SPEC.md 524.
-- Per-agent multi-value rules (CLIN-CRCL-001, CLIN-BILI-001), the HER2 state
-- machine (DOC-HER2-001), and presence/coverage/identity rules still need bespoke
-- evaluators - they remain in the fallback 'not_implemented' branch until the
-- next evaluator pass. A rule whose gate logic isn't implemented here returns
-- not_evaluated with an explicit reason, never a guessed pass/fail.
--
-- Every concept lookup below resolves concept_id via a CLINICAL_ONTOLOGY subquery
-- on canonical_name, never a literal UUID. ontology.sql mints a fresh UUID_STRING()
-- per account, so a hardcoded concept_id is a foreign key to nothing anywhere but
-- the account it was copied from - verified live: a prior version of this file
-- hardcoded 6 concept_ids from one account, and on a second account every one of
-- CLIN-CRCL-001, CLIN-BILI-001 and DOC-HER2-001 silently returned not_evaluated
-- ("missing") instead of reading the real data that was sitting right there.
--
-- Uses explicit CURSOR + OPEN/FETCH/CLOSE into scalar variables throughout,
-- not the FOR-loop record-variable form: dot-access on a FOR-loop record
-- (rec.field) inside plain scripting logic (LET/IF, outside an embedded SQL
-- statement) does not resolve reliably in this account's Snowflake Scripting
-- runtime - verified by direct testing, not assumed - so every field this
-- procedure needs is fetched into its own named variable instead.
CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.evaluate_gates(
    p_patient_id VARCHAR, p_encounter_id VARCHAR, p_known_as_of VARCHAR DEFAULT NULL)
  RETURNS VARIANT
  LANGUAGE SQL
  COMMENT = 'Contract 2 procedure 10. R1: the single source of truth for gate outcomes. Not an agent tool.'
  EXECUTE AS OWNER
AS
$$
DECLARE
    v_known_as_of TIMESTAMP_NTZ DEFAULT NULL;
    v_snapshot TIMESTAMP_TZ;
    v_scheduled   TIMESTAMP_NTZ DEFAULT NULL;
    v_out         ARRAY DEFAULT ARRAY_CONSTRUCT();

    v_rule_id      VARCHAR;
    v_rule_version INTEGER;
    v_gate         VARCHAR;
    v_severity     VARCHAR;
    v_concept      VARCHAR;
    v_operator     VARCHAR;
    v_threshold    FLOAT;
    v_max_age_days FLOAT;
    v_expected_unit VARCHAR;

    v_evt_value    FLOAT;
    v_evt_id       VARCHAR;
    v_derivation   VARCHAR;
    v_age_days     FLOAT;
    v_ev           ARRAY;   -- source record ids a gate cites (events, assertions, ids, coverage)
    v_support      ARRAY;

    v_outcome VARCHAR;
    v_reason  VARCHAR;
    v_found   BOOLEAN;

    v_has_plan       BOOLEAN;
    v_breast         BOOLEAN;
    v_scope_known    BOOLEAN;
    v_her2_targeted  BOOLEAN;
    v_surgical       BOOLEAN;

    -- Binds: cutoff twice, scope_known, surgical, breast, her2_targeted.
    c_rules CURSOR FOR
        SELECT rule_id, rule_version, gate, severity,
               threshold_json:concept::VARCHAR   AS concept,
               threshold_json:operator::VARCHAR  AS operator,
               threshold_json:value::FLOAT       AS threshold_value,
               threshold_json:max_age_days::FLOAT AS max_age_days,
               threshold_json:unit::VARCHAR AS expected_unit
          FROM SAARTHI.OPERATIONAL.RULE_CATALOG
         WHERE threshold_json:concept IS NOT NULL     -- only the "simple threshold" shape
           AND effective_from <= ?
           AND (effective_to IS NULL OR effective_to > ?)
           AND (disease_scope IS NULL
                OR NOT ?
                OR (disease_scope = 'oncology' AND (rule_id <> 'SURG-CLEAR-001' OR ?))
                OR (disease_scope = 'breast_cancer' AND ?)
                OR (disease_scope = 'trastuzumab' AND ?))
         QUALIFY ROW_NUMBER() OVER (PARTITION BY rule_id ORDER BY rule_version DESC) = 1
         ORDER BY specificity DESC;
BEGIN
    v_known_as_of := COALESCE(TRY_TO_TIMESTAMP_NTZ(:p_known_as_of), CURRENT_TIMESTAMP());
    v_snapshot := TRY_TO_TIMESTAMP_TZ(
        TO_VARCHAR(v_known_as_of,'YYYY-MM-DD"T"HH24:MI:SS.FF9') || '+00:00');
    -- Freshness is measured against the encounter the evidence has to be fresh FOR.
    -- With no encounter, the only defensible anchor is the moment being asked
    -- about. A NULL anchor made every age NULL, every "age > max" comparison
    -- NULL, and every freshness rule fall through to its pass branch with a
    -- NULL reason - a silent pass on evidence of unknown age (R3), verified live.
    v_scheduled := COALESCE(
        (SELECT scheduled_time FROM SAARTHI.CORE.ENCOUNTER AT(TIMESTAMP => :v_snapshot) WHERE encounter_id = :p_encounter_id),
        v_known_as_of);

    -- Rule applicability, from RULE_CATALOG.disease_scope. A rule that does not
    -- apply is omitted, not reported not_evaluated: "LVEF not evaluated" on a
    -- FOLFOX patient is noise that trains clinicians to ignore the strip.
    -- When nothing about the patient's disease or regimen is on record, every
    -- rule applies - unknown scope is not the same as "does not apply" (R3).
    v_has_plan := (SELECT COUNT(*) > 0 FROM SAARTHI.CORE.TREATMENT_PLAN AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id);
    v_breast := (SELECT COUNT(*) > 0 FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                  WHERE patient_id = :p_patient_id AND event_type = 'diagnosis' AND code LIKE 'C50%');
    v_scope_known := v_has_plan OR (SELECT COUNT(*) > 0 FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                  WHERE patient_id = :p_patient_id AND event_type = 'diagnosis');
    -- applies_to for SURV-LVEF-*: "trastuzumab and other HER2-targeted agents".
    -- Read from the most recent plan only - a superseded regimen no longer applies.
    v_her2_targeted := (SELECT COUNT(*) > 0 FROM (
        SELECT regimen_display FROM SAARTHI.CORE.TREATMENT_PLAN AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id
         QUALIFY ROW_NUMBER() OVER (ORDER BY version DESC, decided_at DESC NULLS LAST) = 1) latest
        WHERE latest.regimen_display ILIKE ANY ('%trastuzumab%', '%pertuzumab%', '%T-DM1%', '%trastuzumab emtansine%'));
    -- applies_to for SURG-CLEAR-001: "patients with a surgical interruption
    -- mid-treatment". The structured proxy is a surgical note on record.
    v_surgical := (SELECT COUNT(*) > 0 FROM SAARTHI.DOCUMENTS.DOCUMENT
                    WHERE patient_id = :p_patient_id AND doc_type = 'surgical_note');

    OPEN c_rules USING (v_known_as_of, v_known_as_of,
        v_scope_known, v_surgical, v_breast, v_her2_targeted);
    FETCH c_rules INTO v_rule_id, v_rule_version, v_gate, v_severity, v_concept, v_operator, v_threshold, v_max_age_days,
        v_expected_unit;

    WHILE (v_rule_id IS NOT NULL) DO
        v_found := FALSE;
        v_evt_value := NULL;
        v_evt_id := NULL;
        v_derivation := NULL;
        v_age_days := NULL;

        SELECT CASE WHEN he.plausibility_state = 'present'
                AND (:v_expected_unit IS NULL OR he.unit = :v_expected_unit
                     OR (:v_expected_unit = '/uL' AND he.unit IN ('/cumm','/CUMM')))
               THEN he.value_num END,
               he.event_id, he.derivation, DATEDIFF('day', he.event_time, :v_scheduled)
          INTO :v_evt_value, :v_evt_id, :v_derivation, :v_age_days
          FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS he
         WHERE he.patient_id = :p_patient_id
           AND he.concept_name = :v_concept
           AND he.ingested_at <= :v_known_as_of
         ORDER BY he.event_time DESC
         LIMIT 1;

        IF (v_evt_id IS NOT NULL AND v_evt_value IS NOT NULL) THEN
            v_found := TRUE;

            IF (v_rule_id = 'ENDO-DEXA-001') THEN
                -- Stratified T-score interval per NCCN v4.2024. T-score band
                -- determines the max age; freshness is compared against that band.
                -- v_evt_value carries the T-score from concept T_SCORE.
                IF (v_evt_value >= -1.0 AND v_age_days > 730) THEN
                    v_outcome := 'fail';
                    v_reason := 'DEXA T-score ' || v_evt_value::VARCHAR || ' (normal, T>=-1.0) - 24-month interval, last scan ' || v_age_days::VARCHAR || ' days old, overdue';
                ELSEIF (v_evt_value >= -1.0) THEN
                    v_outcome := 'pass';
                    v_reason := 'DEXA T-score ' || v_evt_value::VARCHAR || ' (normal, T>=-1.0) - 24-month interval, last scan ' || v_age_days::VARCHAR || ' days old, within interval';
                ELSEIF (v_evt_value > -2.5 AND v_age_days > 365) THEN
                    v_outcome := 'fail';
                    v_reason := 'DEXA T-score ' || v_evt_value::VARCHAR || ' (osteopenia, -2.5<T<-1.0) - 12-month interval per NCCN, last scan ' || v_age_days::VARCHAR || ' days old, overdue';
                ELSEIF (v_evt_value > -2.5) THEN
                    v_outcome := 'pass';
                    v_reason := 'DEXA T-score ' || v_evt_value::VARCHAR || ' (osteopenia, -2.5<T<-1.0) - 12-month interval per NCCN, last scan ' || v_age_days::VARCHAR || ' days old, within interval';
                ELSEIF (v_age_days > 365) THEN
                    v_outcome := 'fail';
                    v_reason := 'DEXA T-score ' || v_evt_value::VARCHAR || ' (osteoporosis, T<=-2.5) - 12-month interval, last scan ' || v_age_days::VARCHAR || ' days old, overdue';
                ELSE
                    v_outcome := 'pass';
                    v_reason := 'DEXA T-score ' || v_evt_value::VARCHAR || ' (osteoporosis, T<=-2.5) - 12-month interval, last scan ' || v_age_days::VARCHAR || ' days old, within interval';
                END IF;
            ELSEIF (v_operator IS NULL AND v_max_age_days IS NOT NULL) THEN
                -- Freshness-only shape (SURV-LVEF-001/002). No threshold on the
                -- value - the rule requires a recent measurement, not a target
                -- value. Pass if within max_age_days; fail otherwise.
                IF (v_age_days > v_max_age_days) THEN
                    v_outcome := 'fail';
                    v_reason := v_concept || ' last measured ' || v_age_days::VARCHAR || ' days ago, exceeds ' || v_max_age_days::VARCHAR || '-day surveillance interval';
                ELSE
                    v_outcome := 'pass';
                    v_reason := v_concept || ' measured ' || v_age_days::VARCHAR || ' days ago, within ' || v_max_age_days::VARCHAR || '-day surveillance interval';
                END IF;
            ELSEIF (v_operator IS NULL) THEN
                -- Rules with a shape this evaluator does not implement yet
                -- (per-agent multi-value, presence/coverage/identity, HER2 state
                -- machine). Evidence exists but the logic to read it does not -
                -- say so explicitly, never go silent.
                v_outcome := 'not_evaluated';
                v_reason := 'evidence exists but this rule''s threshold shape is not yet implemented by evaluate_gates';
            ELSEIF (v_max_age_days IS NOT NULL AND v_age_days > v_max_age_days) THEN
                v_outcome := 'fail';
                v_reason := v_concept || ' assessment is ' || v_age_days::VARCHAR || ' days old, exceeds ' || v_max_age_days::VARCHAR || '-day limit';
            ELSEIF (v_operator = '>=' AND v_evt_value >= v_threshold) THEN
                v_outcome := 'pass';
                v_reason := v_concept || ' is ' || v_evt_value::VARCHAR || ', meets threshold ' || v_threshold::VARCHAR;
            ELSEIF (v_operator = '>=' AND v_evt_value < v_threshold) THEN
                v_outcome := 'fail';
                v_reason := v_concept || ' is ' || v_evt_value::VARCHAR || ', below threshold ' || v_threshold::VARCHAR;
            ELSEIF (v_operator = '<' AND v_evt_value < v_threshold) THEN
                v_outcome := 'pass';
                v_reason := v_concept || ' is ' || v_evt_value::VARCHAR || ', within threshold ' || v_threshold::VARCHAR;
            ELSEIF (v_operator = '<' AND v_evt_value >= v_threshold) THEN
                v_outcome := 'fail';
                v_reason := v_concept || ' is ' || v_evt_value::VARCHAR || ', at or above threshold ' || v_threshold::VARCHAR;
            ELSE
                v_outcome := 'not_evaluated';
                v_reason := 'unrecognised operator ' || v_operator;
            END IF;

            -- Cite the structured event AND any verified document assertion that supports it
            -- (EVIDENCE_LINK 'supports', written by reconcile_evidence). A derived value
            -- (ANC) has no direct event, so its citation is the derived id only.
            v_support := (SELECT ARRAY_AGG(DISTINCT el.assertion_id)
                            FROM SAARTHI.EVIDENCE.EVIDENCE_LINK el
                           WHERE el.target_type = 'clinical_event'
                             AND el.target_id = :v_evt_id
                             AND el.relation = 'supports');
            v_out := ARRAY_APPEND(v_out, OBJECT_CONSTRUCT(
                'gate', v_gate, 'rule_id', v_rule_id, 'rule_version', v_rule_version,
                'outcome', v_outcome, 'severity', v_severity, 'reason', v_reason,
                'evidence_ids', ARRAY_CAT(ARRAY_CONSTRUCT(v_evt_id), COALESCE(v_support, ARRAY_CONSTRUCT())),
                'derived', v_derivation,
                'known_as_of', TO_VARCHAR(v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS')));
        ELSE
            v_out := ARRAY_APPEND(v_out, OBJECT_CONSTRUCT(
                'gate', v_gate, 'rule_id', v_rule_id, 'rule_version', v_rule_version,
                'outcome', 'not_evaluated', 'severity', v_severity,
                'reason', 'no usable ' || v_concept || ' evidence found as of ' || TO_VARCHAR(v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS'),
                'evidence_ids', ARRAY_CONSTRUCT(),
                'known_as_of', TO_VARCHAR(v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS')));
        END IF;

        FETCH c_rules INTO v_rule_id, v_rule_version, v_gate, v_severity, v_concept, v_operator, v_threshold, v_max_age_days,
        v_expected_unit;
    END WHILE;
    CLOSE c_rules;

    -- =========================================================================
    -- Second pass: rules WITHOUT threshold_json.concept - dispatched by rule_id.
    -- Covers identity (ID-LINK-001, ID-QUAR-001), coverage (COV-AUTH-001,
    -- COV-LIMIT-001), documentation (DOC-PATH-001, DOC-DISC-001, DOC-HER2-001),
    -- surgical clearance (SURG-CLEAR-001), and per-agent multi-input clinical
    -- (CLIN-CRCL-001, CLIN-BILI-001). Rules for which required inputs are not
    -- seeded return not_evaluated with a specific reason naming the missing
    -- inputs - never a silent skip and never a guessed pass/fail.
    -- =========================================================================
    LET c_special CURSOR FOR
        SELECT rule_id, rule_version, gate, severity
          FROM SAARTHI.OPERATIONAL.RULE_CATALOG
         WHERE threshold_json:concept IS NULL
           AND effective_from <= ?
           AND (effective_to IS NULL OR effective_to > ?)
           AND (disease_scope IS NULL
                OR NOT ?
                OR (disease_scope = 'oncology' AND (rule_id <> 'SURG-CLEAR-001' OR ?))
                OR (disease_scope = 'breast_cancer' AND ?)
                OR (disease_scope = 'trastuzumab' AND ?))
         QUALIFY ROW_NUMBER() OVER (PARTITION BY rule_id ORDER BY rule_version DESC) = 1
         ORDER BY specificity DESC;

    OPEN c_special USING (v_known_as_of, v_known_as_of,
        v_scope_known, v_surgical, v_breast, v_her2_targeted);
    FETCH c_special INTO v_rule_id, v_rule_version, v_gate, v_severity;

    WHILE (v_rule_id IS NOT NULL) DO
        v_outcome := 'not_evaluated';
        v_reason  := 'evaluator not implemented';
        v_ev      := ARRAY_CONSTRUCT();

        IF (v_rule_id = 'ID-LINK-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(map_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.ID_MAP AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id AND link_status IN ('abha_linked','manually_verified'));
            LET v_linked NUMBER := (SELECT COUNT(*) FROM SAARTHI.CORE.ID_MAP AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND link_status IN ('abha_linked','manually_verified'));
            IF (v_linked >= 1) THEN
                v_outcome := 'pass';
                v_reason  := v_linked::VARCHAR || ' verified identifier link(s) present (abha_linked or manually_verified)';
            ELSE
                v_outcome := 'fail';
                v_reason  := 'no verified identifier links on file - abha_linked or manually_verified required';
            END IF;
        ELSEIF (v_rule_id = 'ID-QUAR-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(map_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.ID_MAP AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id AND link_status = 'quarantined');
            LET v_quar NUMBER := (SELECT COUNT(*) FROM SAARTHI.CORE.ID_MAP AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND link_status = 'quarantined');
            IF (v_quar = 0) THEN
                v_outcome := 'pass';
                v_reason  := 'no quarantined identity matches on record';
            ELSE
                v_outcome := 'fail';
                v_reason  := v_quar::VARCHAR || ' quarantined identity match(es) - manual reconciliation required, no evidence contributes until resolved (R4)';
            END IF;
        ELSEIF (v_rule_id = 'DOC-PATH-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(event_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id AND event_type = 'pathology');
            LET v_final_path NUMBER := (SELECT COUNT(*) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND event_type = 'pathology' AND status = 'final');
            LET v_pending_path NUMBER := (SELECT COUNT(*) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND event_type = 'pathology' AND status IN ('preliminary','pending'));
            IF (v_final_path >= 1) THEN
                v_outcome := 'pass';
                v_reason  := v_final_path::VARCHAR || ' pathology report(s) in final status';
            ELSEIF (v_pending_path >= 1) THEN
                v_outcome := 'not_evaluated';
                v_reason  := v_pending_path::VARCHAR || ' pathology report(s) preliminary/pending - awaiting final';
            ELSE
                v_outcome := 'fail';
                v_reason  := 'no pathology reports on record';
            END IF;
        ELSEIF (v_rule_id = 'DOC-DISC-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(event_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id
                        AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'HER2_IHC'));
            -- discordant_across_specimens is not a failure - both readings surface
            -- as evidence, and a human reconciles per SPEC §12. Only same-specimen
            -- disagreement is a real conflict. This evaluator checks HER2 as the
            -- canonical case; a fuller sweep would enumerate every concept.
            LET v_her2_specimens NUMBER := (SELECT COUNT(DISTINCT specimen_id) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'HER2_IHC') AND specimen_id IS NOT NULL);
            IF (v_her2_specimens > 1) THEN
                v_outcome := 'pass';
                v_reason  := 'HER2 read on ' || v_her2_specimens::VARCHAR || ' distinct specimens - discordant_across_specimens: both readings surfaced, never auto-resolved';
            ELSE
                v_outcome := 'pass';
                v_reason  := 'no cross-source discordance detected';
            END IF;
        ELSEIF (v_rule_id = 'DOC-HER2-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(event_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id
                        AND concept_id IN (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name IN ('HER2_IHC','HER2_FISH')));
            -- HER2 state machine: ihc IN (0,1,3) -> final; ihc=2 -> FISH reflex.
            -- Latest specimen is authoritative when specimens differ (final resection
            -- outranks outside biopsy in real practice). value_text pattern is like
            -- 'grade=III ihc=2+'.
            LET v_latest_ihc VARCHAR := (SELECT value_text FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'HER2_IHC') ORDER BY event_time DESC LIMIT 1);
            IF (v_latest_ihc IS NULL) THEN
                v_outcome := 'fail';
                v_reason  := 'no HER2 IHC recorded';
            ELSEIF (v_latest_ihc ILIKE '%ihc=2%' OR v_latest_ihc ILIKE '%ihc 2%') THEN
                -- IHC 2+ is equivocal: status is final only once a FISH result on
                -- or after that IHC exists. ASCO/CAP 2018 dual-probe groups:
                --   group 1  ratio >= 2.0 AND mean HER2 copies >= 4.0  -> positive
                --   group 5  ratio <  2.0 AND copies < 4.0             -> negative
                --   groups 2-4 (discordant ratio/copies)               -> needs
                --            concurrent IHC review; not final, never guessed.
                -- value_text carries 'ratio=2.6 copies=5.8'.
                LET v_ihc_time TIMESTAMP_NTZ := (SELECT MAX(event_time) FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'HER2_IHC'));
                LET v_fish VARCHAR := (SELECT value_text FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND status = 'final' AND event_time >= :v_ihc_time AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'HER2_FISH') ORDER BY event_time DESC LIMIT 1);
                LET v_ratio  FLOAT := TRY_TO_DOUBLE(REGEXP_SUBSTR(:v_fish, 'ratio=([0-9.]+)', 1, 1, 'e', 1));
                LET v_copies FLOAT := TRY_TO_DOUBLE(REGEXP_SUBSTR(:v_fish, 'copies=([0-9.]+)', 1, 1, 'e', 1));
                IF (v_fish IS NULL) THEN
                    v_outcome := 'not_evaluated';
                    v_reason  := 'HER2 IHC=2 on latest specimen (' || v_latest_ihc || ') - FISH reflex required, no FISH result on record yet';
                ELSEIF (v_ratio IS NULL OR v_copies IS NULL) THEN
                    v_outcome := 'not_evaluated';
                    v_reason  := 'FISH result on record but ratio/copy number unreadable (' || v_fish || ') - manual review';
                ELSEIF (v_ratio >= 2.0 AND v_copies >= 4.0) THEN
                    v_outcome := 'pass';
                    v_reason  := 'HER2 status final: IHC 2+ reflexed to FISH, amplified (ratio ' || v_ratio::VARCHAR || ', ' || v_copies::VARCHAR || ' copies/cell - ASCO/CAP 2018 group 1, positive)';
                ELSEIF (v_ratio < 2.0 AND v_copies < 4.0) THEN
                    v_outcome := 'pass';
                    v_reason  := 'HER2 status final: IHC 2+ reflexed to FISH, not amplified (ratio ' || v_ratio::VARCHAR || ', ' || v_copies::VARCHAR || ' copies/cell - ASCO/CAP 2018 group 5, negative)';
                ELSE
                    v_outcome := 'not_evaluated';
                    v_reason  := 'FISH ratio ' || v_ratio::VARCHAR || ' with ' || v_copies::VARCHAR || ' copies/cell is ASCO/CAP 2018 group 2-4 - concurrent IHC review required, not final';
                END IF;
            ELSE
                v_outcome := 'pass';
                v_reason  := 'HER2 status final from IHC alone: ' || v_latest_ihc;
            END IF;
        ELSEIF (v_rule_id = 'COV-LIMIT-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(coverage_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.COVERAGE AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id);
            LET v_cov_used FLOAT := (SELECT used_amount FROM SAARTHI.CORE.COVERAGE AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id ORDER BY priority ASC NULLS LAST LIMIT 1);
            LET v_cov_limit FLOAT := (SELECT annual_limit FROM SAARTHI.CORE.COVERAGE AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id ORDER BY priority ASC NULLS LAST LIMIT 1);
            IF (v_cov_limit IS NULL) THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'no COVERAGE row on file for patient';
            ELSEIF (v_cov_used < v_cov_limit) THEN
                v_outcome := 'pass';
                v_reason  := 'used ' || v_cov_used::VARCHAR || ' of annual limit ' || v_cov_limit::VARCHAR || ' - within limit (family-floater aggregation OOS per SPEC 175)';
            ELSE
                v_outcome := 'fail';
                v_reason  := 'used ' || v_cov_used::VARCHAR || ' meets or exceeds annual limit ' || v_cov_limit::VARCHAR;
            END IF;
        ELSEIF (v_rule_id = 'COV-AUTH-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(auth_id), ARRAY_CONSTRUCT()) FROM SAARTHI.CORE.AUTHORIZATION AT(TIMESTAMP => :v_snapshot)
                      WHERE patient_id = :p_patient_id
                        AND (encounter_id = :p_encounter_id OR encounter_id IS NULL)
                        AND (expires_at IS NULL OR expires_at > :v_known_as_of));
            LET v_pa_status VARCHAR := (SELECT status FROM SAARTHI.CORE.AUTHORIZATION AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND (encounter_id = :p_encounter_id OR encounter_id IS NULL) AND (expires_at IS NULL OR expires_at > :v_known_as_of) ORDER BY decided_at DESC NULLS LAST, requested_at DESC NULLS LAST LIMIT 1);
            LET v_pa_letter VARCHAR := (SELECT letter_status FROM SAARTHI.CORE.AUTHORIZATION AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND (encounter_id = :p_encounter_id OR encounter_id IS NULL) AND (expires_at IS NULL OR expires_at > :v_known_as_of) ORDER BY decided_at DESC NULLS LAST, requested_at DESC NULLS LAST LIMIT 1);
            IF (v_pa_status IS NULL) THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'no pre-authorisation record for this patient/encounter';
            ELSEIF (v_pa_letter IS NOT NULL AND v_pa_letter != v_pa_status) THEN
                v_outcome := 'conflicting';
                v_reason  := 'pre-auth table status is ''' || v_pa_status || ''' but letter says ''' || v_pa_letter || ''' - human reconciliation required';
            ELSEIF (v_pa_status = 'approved') THEN
                v_outcome := 'pass';
                v_reason  := 'pre-authorisation approved and current';
            ELSEIF (v_pa_status = 'pending') THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'pre-authorisation status is pending - decision not yet issued';
            ELSEIF (v_pa_status = 'expired') THEN
                v_outcome := 'fail';
                v_reason  := 'pre-authorisation expired - renewal required';
            ELSE
                v_outcome := 'fail';
                v_reason  := 'pre-authorisation status: ' || v_pa_status;
            END IF;
        ELSEIF (v_rule_id = 'CLIN-CRCL-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(event_id), ARRAY_CONSTRUCT()) FROM (
                       SELECT event_id FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                        WHERE patient_id = :p_patient_id AND status = 'final'
                          AND concept_id IN (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name IN ('CREATININE','WEIGHT'))
                        QUALIFY ROW_NUMBER() OVER (PARTITION BY concept_id ORDER BY event_time DESC) = 1));
            -- Cockcroft-Gault: CrCl = ((140 - age) * weight_kg * (0.85 if female else 1)) / (72 * creatinine)
            LET v_creat  FLOAT := (SELECT CASE WHEN unit = 'mg/dL' AND value_num > 0 THEN value_num END FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'CREATININE') AND status = 'final' ORDER BY event_time DESC LIMIT 1);
            LET v_weight FLOAT := (SELECT CASE WHEN unit = 'kg' AND value_num > 0 THEN value_num END FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'WEIGHT') AND status = 'final' ORDER BY event_time DESC LIMIT 1);
            LET v_age    FLOAT := (SELECT DATEDIFF('year', dob, :v_known_as_of::DATE)
                - IFF(TO_CHAR(:v_known_as_of::DATE,'MMDD') < TO_CHAR(dob,'MMDD'),1,0) FROM SAARTHI.CORE.PATIENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id);
            LET v_female BOOLEAN := (SELECT CASE gender WHEN 'female' THEN TRUE WHEN 'male' THEN FALSE END FROM SAARTHI.CORE.PATIENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id);
            IF (v_creat IS NULL OR v_weight IS NULL OR v_age IS NULL
                OR v_age < 0 OR v_age >= 140 OR v_female IS NULL) THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'CrCl requires valid units, creatinine, weight, age and recorded sex; missing: ' ||
                             IFF(v_creat IS NULL, 'creatinine ', '') ||
                             IFF(v_weight IS NULL, 'weight ', '') ||
                             IFF(v_age IS NULL OR v_age < 0 OR v_age >= 140, 'age ', '') ||
                             IFF(v_female IS NULL, 'recorded sex ', '');
            ELSE
                LET v_crcl FLOAT := ((140 - v_age) * v_weight * IFF(v_female, 0.85, 1.0)) / (72 * v_creat);
                -- Safest-agent threshold (60 mL/min - cisplatin/methotrexate). If CrCl
                -- clears the strictest threshold, all listed agents are covered.
                IF (v_crcl >= 60) THEN
                    v_outcome := 'pass';
                    v_reason  := 'CrCl ' || ROUND(v_crcl,1)::VARCHAR || ' mL/min (Cockcroft-Gault, age=' || v_age::VARCHAR || ' weight=' || v_weight::VARCHAR || ' cr=' || v_creat::VARCHAR || ') - clears strictest per-agent minimum (60 for cisplatin)';
                ELSEIF (v_crcl >= 45) THEN
                    v_outcome := 'pass';
                    v_reason  := 'CrCl ' || ROUND(v_crcl,1)::VARCHAR || ' mL/min - meets pemetrexed/mid-tier thresholds, below cisplatin 60 minimum';
                ELSEIF (v_crcl >= 30) THEN
                    v_outcome := 'pass';
                    v_reason  := 'CrCl ' || ROUND(v_crcl,1)::VARCHAR || ' mL/min - meets carboplatin/capecitabine 30 minimum only';
                ELSE
                    v_outcome := 'fail';
                    v_reason  := 'CrCl ' || ROUND(v_crcl,1)::VARCHAR || ' mL/min - below any listed per-agent minimum (30-60 range)';
                END IF;
            END IF;
        ELSEIF (v_rule_id = 'CLIN-BILI-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(event_id), ARRAY_CONSTRUCT()) FROM (
                       SELECT event_id FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot)
                        WHERE patient_id = :p_patient_id AND status = 'final'
                          AND concept_id IN (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name IN ('BILIRUBIN','AST'))
                        QUALIFY ROW_NUMBER() OVER (PARTITION BY concept_id ORDER BY event_time DESC) = 1));
            -- Per-agent bilirubin thresholds. Uses doxorubicin (bilirubin<=1.2 mg/dL)
            -- as the safety-first default because it is the strictest absolute limit
            -- across the three agents named in the rule (docetaxel is x-ULN; doxorubicin
            -- is absolute mg/dL). AST also read for informational context.
            LET v_bili FLOAT := (SELECT CASE WHEN unit = 'mg/dL' AND value_num >= 0 THEN value_num END FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'BILIRUBIN') AND status = 'final' ORDER BY event_time DESC LIMIT 1);
            LET v_ast  FLOAT := (SELECT CASE WHEN unit IN ('U/L','IU/L') AND value_num >= 0 THEN value_num END FROM SAARTHI.CORE.CLINICAL_EVENT AT(TIMESTAMP => :v_snapshot) WHERE patient_id = :p_patient_id AND concept_id = (SELECT concept_id FROM SAARTHI.OPERATIONAL.CLINICAL_ONTOLOGY WHERE canonical_name = 'AST') AND status = 'final' ORDER BY event_time DESC LIMIT 1);
            IF (v_bili IS NULL) THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'per-agent bilirubin rule requires a bilirubin measurement';
            ELSEIF (v_bili <= 1.2) THEN
                v_outcome := 'pass';
                v_reason  := 'bilirubin ' || v_bili::VARCHAR || ' mg/dL clears strictest per-agent absolute (doxorubicin <=1.2)' || IFF(v_ast IS NOT NULL, ', AST ' || v_ast::VARCHAR || ' U/L for context', '');
            ELSEIF (v_bili <= 1.8) THEN
                v_outcome := 'pass';
                v_reason  := 'bilirubin ' || v_bili::VARCHAR || ' mg/dL within 1.5x ULN band (paclitaxel/docetaxel-eligible; doxorubicin threshold exceeded)';
            ELSE
                v_outcome := 'fail';
                v_reason  := 'bilirubin ' || v_bili::VARCHAR || ' mg/dL exceeds any listed per-agent threshold - hold hepatobiliary-clearance chemo';
            END IF;
        ELSEIF (v_rule_id = 'SURG-CLEAR-001') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(assertion_id), ARRAY_CONSTRUCT()) FROM (
                       SELECT assertion_id FROM SAARTHI.EVIDENCE.ASSERTION
                        WHERE subject = :p_patient_id AND verification_status = 'verified'
                          AND predicate IN ('wound_healing_status','infection_status','surgical_clearance_signed_by_practitioner')
                        QUALIFY ROW_NUMBER() OVER (PARTITION BY predicate ORDER BY assertion_id DESC) = 1));
            -- Requires three assertions: wound_healing_status IN (adequate, healed),
            -- infection_status = resolved, surgical_clearance_signed_by_practitioner IS NOT NULL.
            LET v_wound VARCHAR := (SELECT value FROM SAARTHI.EVIDENCE.ASSERTION WHERE subject = :p_patient_id AND predicate = 'wound_healing_status' AND verification_status = 'verified' ORDER BY assertion_id DESC LIMIT 1);
            LET v_infect VARCHAR := (SELECT value FROM SAARTHI.EVIDENCE.ASSERTION WHERE subject = :p_patient_id AND predicate = 'infection_status' AND verification_status = 'verified' ORDER BY assertion_id DESC LIMIT 1);
            LET v_signed VARCHAR := (SELECT value FROM SAARTHI.EVIDENCE.ASSERTION WHERE subject = :p_patient_id AND predicate = 'surgical_clearance_signed_by_practitioner' AND verification_status = 'verified' ORDER BY assertion_id DESC LIMIT 1);
            IF (v_wound IS NULL OR v_infect IS NULL OR v_signed IS NULL) THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'surgical clearance requires three verified assertions; missing: ' ||
                             IFF(v_wound IS NULL, 'wound_healing_status ', '') ||
                             IFF(v_infect IS NULL, 'infection_status ', '') ||
                             IFF(v_signed IS NULL, 'clearance_signature ', '');
            ELSEIF (v_wound NOT IN ('adequate','healed')) THEN
                v_outcome := 'fail';
                v_reason  := 'wound_healing_status is ''' || v_wound || ''' - required: adequate or healed';
            ELSEIF (v_infect != 'resolved') THEN
                v_outcome := 'fail';
                v_reason  := 'infection_status is ''' || v_infect || ''' - required: resolved';
            ELSE
                v_outcome := 'pass';
                v_reason  := 'surgical clearance verified: wound=' || v_wound || ', infection=' || v_infect || ', signed by ' || v_signed;
            END IF;
        ELSEIF (v_rule_id = 'SURV-LVEF-002') THEN
            v_ev := (SELECT COALESCE(ARRAY_AGG(event_id), ARRAY_CONSTRUCT()) FROM (
                       SELECT event_id FROM (
                         SELECT event_id,
                                ROW_NUMBER() OVER (ORDER BY event_time ASC, event_id ASC)  AS rn_first,
                                ROW_NUMBER() OVER (ORDER BY event_time DESC, event_id DESC) AS rn_last
                           FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS
                          WHERE patient_id = :p_patient_id AND concept_name = 'LVEF' AND ingested_at <= :v_known_as_of)
                        WHERE rn_first = 1 OR rn_last = 1
                        ORDER BY event_id));
            -- Delta rule: hold if (baseline - current) >= 16, OR (current < 50 AND drop >= 10).
            -- Needs at least two LVEF measurements to compute a delta.
            LET v_lvef_readings NUMBER := (SELECT COUNT(*) FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS WHERE patient_id = :p_patient_id AND concept_name = 'LVEF' AND ingested_at <= :v_known_as_of);
            IF (v_lvef_readings < 2) THEN
                v_outcome := 'not_evaluated';
                v_reason  := 'delta rule requires baseline + current LVEF, only ' || v_lvef_readings::VARCHAR || ' measurement(s) on record';
            ELSE
                LET v_baseline FLOAT := (SELECT value_num FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS WHERE patient_id = :p_patient_id AND concept_name = 'LVEF' AND ingested_at <= :v_known_as_of ORDER BY event_time ASC LIMIT 1);
                LET v_current  FLOAT := (SELECT value_num FROM SAARTHI.CORE.DT_HARMONIZED_EVENTS WHERE patient_id = :p_patient_id AND concept_name = 'LVEF' AND ingested_at <= :v_known_as_of ORDER BY event_time DESC LIMIT 1);
                LET v_drop FLOAT := v_baseline - v_current;
                IF (v_drop >= 16) THEN
                    v_outcome := 'fail';
                    v_reason  := 'LVEF dropped ' || v_drop::VARCHAR || 'pp from baseline (' || v_baseline::VARCHAR || ' -> ' || v_current::VARCHAR || ') - hold trastuzumab (>= 16pp threshold)';
                ELSEIF (v_current < 50 AND v_drop >= 10) THEN
                    v_outcome := 'fail';
                    v_reason  := 'LVEF ' || v_current::VARCHAR || ' below 50 AND dropped ' || v_drop::VARCHAR || 'pp from baseline (>=10pp threshold when current<50) - hold trastuzumab';
                ELSE
                    v_outcome := 'pass';
                    v_reason  := 'LVEF ' || v_current::VARCHAR || ' vs baseline ' || v_baseline::VARCHAR || ' (drop ' || v_drop::VARCHAR || 'pp) - within thresholds, continue';
                END IF;
            END IF;
        ELSE
            v_outcome := 'not_evaluated';
            v_reason  := 'rule ' || v_rule_id || ' has no evaluator dispatch';
        END IF;

        v_out := ARRAY_APPEND(v_out, OBJECT_CONSTRUCT(
            'gate', v_gate, 'rule_id', v_rule_id, 'rule_version', v_rule_version,
            'outcome', v_outcome, 'severity', v_severity, 'reason', v_reason,
            'evidence_ids', v_ev,
            'known_as_of', TO_VARCHAR(v_known_as_of, 'YYYY-MM-DD"T"HH24:MI:SS')));

        FETCH c_special INTO v_rule_id, v_rule_version, v_gate, v_severity;
    END WHILE;
    CLOSE c_special;

    RETURN OBJECT_CONSTRUCT('patient_id', p_patient_id, 'encounter_id', p_encounter_id, 'gates', v_out);
END;
$$;
-- ===== END procedures/evaluate_gates.sql =====

-- ===== BEGIN procedures/bind_patient.sql =====
-- =============================================================================
-- STEP 14 - bind_patient (internal - never exposed to the agent)
-- =============================================================================
-- COPILOT-SPEC.md §0. Selection is a human click, recorded, re-validated on
-- every tool call. Validates CARE_TEAM + CONSENT BEFORE writing - any
-- failure raises, no binding is created, no detail about why is returned.
CREATE OR REPLACE PROCEDURE SAARTHI.OPERATIONAL.bind_patient(p_patient_id VARCHAR)
  RETURNS VARIANT
  LANGUAGE SQL
  COMMENT = 'Contract 2 procedure 9. Validates care team + consent before writing. Not an agent tool.'
  EXECUTE AS OWNER
AS
$$
DECLARE
    v_practitioner  VARCHAR;
    v_care_team_id  VARCHAR;
    v_consent_id    VARCHAR;
    v_binding_id    VARCHAR;
BEGIN
    -- 1. resolve CURRENT_USER() -> PRACTITIONER
    v_practitioner := (SELECT practitioner_id
                         FROM SAARTHI.GOVERNANCE.PRACTITIONER
                        WHERE snowflake_user = CURRENT_USER()
                          AND active = TRUE);
    IF (v_practitioner IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access');
    END IF;

    -- 2. require an ACTIVE CARE_TEAM row for (practitioner, p_patient_id) today
    v_care_team_id := (SELECT care_team_id
                         FROM SAARTHI.GOVERNANCE.CARE_TEAM
                        WHERE practitioner_id = :v_practitioner
                          AND patient_id     = :p_patient_id
                          AND role_type IN ('treating', 'coordinator')
                          AND active_from   <= CURRENT_DATE()
                          AND (active_to IS NULL OR active_to >= CURRENT_DATE())
                        ORDER BY active_from DESC
                        LIMIT 1);
    IF (v_care_team_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'no_patient_access');
    END IF;

    -- 3. require a valid CONSENT covering purpose and today's date
    v_consent_id := (SELECT c.consent_id
                       FROM SAARTHI.GOVERNANCE.CONSENT c
                       JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
                         ON p.practitioner_id = :v_practitioner
                       LEFT JOIN SAARTHI.GOVERNANCE.FACILITY f
                         ON f.facility_id = p.facility_id
                      WHERE c.patient_id = :p_patient_id
                        AND c.status     = 'active'
                        AND c.valid_from <= CURRENT_TIMESTAMP()
                        AND (c.valid_until IS NULL OR c.valid_until >= CURRENT_TIMESTAMP())
                        AND c.purpose_code IN ('treatment', 'coordination')
                        AND (c.granted_to_facility_id = p.facility_id
                          OR c.granted_to_org_id      = f.org_id)
                      ORDER BY c.valid_from DESC
                      LIMIT 1);
    IF (v_consent_id IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('error', 'consent_not_valid');
    END IF;

    -- 4. release any prior binding for CURRENT_SESSION()
    UPDATE SAARTHI.GOVERNANCE.PATIENT_BINDING
       SET released_at = CURRENT_TIMESTAMP()
     WHERE session_id = CURRENT_SESSION()
       AND released_at IS NULL;

    -- 5. insert the new binding, return binding_id
    v_binding_id := UUID_STRING();
    INSERT INTO SAARTHI.GOVERNANCE.PATIENT_BINDING
        (binding_id, session_id, snowflake_user, patient_id, care_team_id, consent_id, bound_at)
    VALUES
        (:v_binding_id, CURRENT_SESSION(), CURRENT_USER(), :p_patient_id, :v_care_team_id, :v_consent_id, CURRENT_TIMESTAMP());

    RETURN OBJECT_CONSTRUCT('binding_id', v_binding_id);
END;
$$;
-- ===== END procedures/bind_patient.sql =====

-- ===== BEGIN dynamic_tables/04_scheme_eligibility.sql =====
-- =============================================================================
-- STEP 15c - DT_SCHEME_ELIGIBILITY (patient x scheme registry)
-- =============================================================================
-- SPEC.md §14 diagram. Cross-joins patients with SCHEME_REGISTRY and applies
-- the scheme's eligibility rules (income ceiling, state domicile). Determines
-- which schemes a patient qualifies for. Deterministic; refreshed on lag.
--
-- Eligibility per SPEC / real Indian scheme rules:
--   PM-JAY: SECC-C families only + income ceiling. We proxy SECC-C
--           membership with a CURRENT (date-valid) COVERAGE.payer_type='scheme' row
--           (present -> eligible; otherwise income_or_seccc_uncertain).
--   State schemes: domicile match is necessary, not sufficient -> 'eligibility_unverified'
--           until income / ration-card evidence exists (never 'eligible' from domicile alone).

CREATE OR REPLACE DYNAMIC TABLE SAARTHI.OPERATIONAL.DT_SCHEME_ELIGIBILITY
  TARGET_LAG = '10 minute'
  REFRESH_MODE = FULL
  INITIALIZE = ON_CREATE
  WAREHOUSE = SAARTHI_AI_WH
AS
SELECT
    p.patient_id,
    p.name,
    p.state         AS patient_state,
    sr.scheme_id,
    sr.scheme_name,
    sr.scheme_type,
    sr.annual_limit,
    sr.state_scope,
    CASE
        WHEN sr.scheme_type = 'central' THEN
            CASE WHEN COALESCE(sc.has_current_scheme_coverage, FALSE)
                 THEN 'eligible'
                 ELSE 'income_or_seccc_uncertain'
            END
        -- Domicile alone is not eligibility: income / SECC tests were never evaluated (R1/R3).
        WHEN sr.state_scope = p.state THEN 'eligibility_unverified'
        ELSE 'not_applicable'
    END AS eligibility_status,
    sr.covered_packages
FROM SAARTHI.CORE.PATIENT p
LEFT JOIN (
    -- CURRENT_DATE() is evaluated per refresh, which is why this table is REFRESH_MODE = FULL
    -- (incremental refresh does not support context functions). No correlated subquery.
    SELECT c.patient_id,
           COUNT_IF((c.effective_from IS NULL OR c.effective_from <= CURRENT_DATE())
                AND (c.effective_to   IS NULL OR c.effective_to   >= CURRENT_DATE())) > 0
             AS has_current_scheme_coverage
      FROM SAARTHI.CORE.COVERAGE c
     WHERE c.payer_type = 'scheme'
     GROUP BY c.patient_id
) sc ON sc.patient_id = p.patient_id
CROSS JOIN SAARTHI.OPERATIONAL.SCHEME_REGISTRY sr
WHERE sr.scheme_type = 'central'
   OR sr.state_scope = p.state;
-- ===== END dynamic_tables/04_scheme_eligibility.sql =====

-- ===== BEGIN semantic/01_semantic_view.sql (guarded) =====
EXECUTE IMMEDIATE $$
BEGIN
CREATE OR REPLACE SEMANTIC VIEW SAARTHI.OPERATIONAL.SAARTHI_SEMANTIC_VIEW
  TABLES (
    patient AS SAARTHI.CORE.PATIENT PRIMARY KEY (patient_id) WITH SYNONYMS ('patients') COMMENT = 'One row per patient',
    encounter AS SAARTHI.CORE.ENCOUNTER PRIMARY KEY (encounter_id) WITH SYNONYMS ('encounters', 'visits', 'cycles') COMMENT = 'Treatment cycles and visits',
    readiness AS SAARTHI.OPERATIONAL.READINESS_STATE PRIMARY KEY (patient_id, encounter_id, gate, rule_id) WITH SYNONYMS ('gates', 'readiness gates') COMMENT = 'Latest gate outcome per patient, encounter and rule. not_evaluated means evidence is missing, never a pass',
    review_issue AS SAARTHI.OPERATIONAL.REVIEW_ISSUE PRIMARY KEY (issue_id) WITH SYNONYMS ('blockers', 'review queue', 'issues') COMMENT = 'Coordinator review issues',
    authorization AS SAARTHI.CORE.AUTHORIZATION PRIMARY KEY (auth_id) WITH SYNONYMS ('authorisations', 'pre-authorisations') COMMENT = 'Scheme authorisations; letter_status is the value printed on the letter and may differ from status',
    scheme_eligibility AS SAARTHI.OPERATIONAL.DT_SCHEME_ELIGIBILITY PRIMARY KEY (patient_id, scheme_id) WITH SYNONYMS ('scheme eligibility') COMMENT = 'Patient by scheme eligibility status from versioned SQL'
  )
  RELATIONSHIPS (
    encounter (patient_id) REFERENCES patient,
    readiness (patient_id) REFERENCES patient,
    review_issue (patient_id) REFERENCES patient,
    authorization (patient_id) REFERENCES patient,
    scheme_eligibility (patient_id) REFERENCES patient
  )
  FACTS (
    encounter.is_complication AS IFF(encounter.gap_type = 'clinical_complication', 1, 0),
    readiness.is_not_evaluated AS IFF(readiness.outcome = 'not_evaluated', 1, 0),
    readiness.is_failed AS IFF(readiness.outcome = 'fail', 1, 0),
    review_issue.is_open_blocker AS IFF(review_issue.state='open'
        AND review_issue.severity='blocker',1,0),
    authorization.is_conflicting AS IFF(authorization.status='conflicting'
        OR (authorization.status IN ('pending','approved','denied','expired')
        AND authorization.letter_status IN ('pending','approved','denied','expired')
        AND authorization.status<>authorization.letter_status),1,0),
    authorization.is_curable_denial AS IFF(authorization.status = 'denied' AND authorization.denial_is_curable, 1, 0),
    scheme_eligibility.is_eligible AS IFF(scheme_eligibility.eligibility_status = 'eligible', 1, 0)
  )
  DIMENSIONS (
    patient.state AS patient.state WITH SYNONYMS ('region') COMMENT = 'Patient home state',
    encounter.gap_type AS encounter.gap_type COMMENT = 'Reason for delay, if any',
    encounter.cycle_number AS encounter.cycle_number,
    readiness.readiness_patient_id AS readiness.patient_id COMMENT = 'Patient the gate belongs to',
    authorization.authorization_patient_id AS authorization.patient_id,
    readiness.gate AS readiness.gate COMMENT = 'Readiness gate name',
    readiness.outcome AS readiness.outcome COMMENT = 'pass, fail, not_evaluated or conflicting',
    readiness.severity AS readiness.severity,
    review_issue.issue_gate AS review_issue.gate,
    review_issue.issue_state AS review_issue.state COMMENT = 'open, evidence_received, closed or escalated',
    review_issue.issue_severity AS review_issue.severity,
    authorization.auth_status AS authorization.status COMMENT = 'pending, approved, denied, partial, expired or conflicting',
    authorization.letter_status AS authorization.letter_status,
    authorization.scheme AS authorization.scheme,
    authorization.denial_is_curable AS authorization.denial_is_curable,
    scheme_eligibility.scheme_name AS scheme_eligibility.scheme_name,
    scheme_eligibility.eligibility_status AS scheme_eligibility.eligibility_status
  )
  METRICS (
    encounter.encounter_count AS COUNT(encounter.encounter_id) COMMENT = 'Total encounters',
    encounter.complication_count AS SUM(encounter.is_complication) COMMENT = 'Encounters with a clinical complication gap',
    readiness.not_evaluated_gate_count AS SUM(readiness.is_not_evaluated) COMMENT = 'Gates with evidence missing (not a pass)',
    readiness.failed_gate_count AS SUM(readiness.is_failed) COMMENT = 'Gates that failed',
    review_issue.open_blocker_count AS SUM(review_issue.is_open_blocker)
        COMMENT = 'Open review issues with blocker severity',
    authorization.conflicting_authorization_count AS SUM(authorization.is_conflicting) COMMENT = 'Authorisations where table and letter disagree',
    authorization.curable_denial_count AS SUM(authorization.is_curable_denial) COMMENT = 'Denied authorisations flagged procedurally curable',
    scheme_eligibility.eligible_scheme_count AS SUM(scheme_eligibility.is_eligible) COMMENT = 'Patient-scheme pairs with status eligible'
  )
  COMMENT = 'SAARTHI record-state questions (Class B only). Gates, review issues, authorisations, scheme eligibility, cohort encounters. Clinical judgment questions are refused upstream.'
  AI_QUESTION_CATEGORIZATION 'Answer only record and coverage state questions (what is documented, missing, conflicting, authorised, counted). Reject any question asking for clinical judgment, prognosis, dosing, safety or a recommendation, and say it needs the treating practitioner.'
  AI_VERIFIED_QUERIES (
    vq_patients_missing_evidence AS (
      QUESTION 'Which patients have gates with evidence not yet received?'
      SQL 'SELECT patient_id, COUNT(*) AS not_evaluated_gates FROM SAARTHI.OPERATIONAL.READINESS_STATE WHERE outcome = ''not_evaluated'' GROUP BY patient_id ORDER BY not_evaluated_gates DESC'
    ),
    vq_open_blockers_per_gate AS (
      QUESTION 'How many open blockers per gate?'
      SQL 'SELECT gate, COUNT(*) AS open_blockers FROM SAARTHI.OPERATIONAL.REVIEW_ISSUE
        WHERE state = ''open'' AND severity = ''blocker''
        GROUP BY gate ORDER BY open_blockers DESC'
    ),
    vq_conflicting_authorisation AS (
      QUESTION 'Which patients have conflicting authorisation status?'
      SQL 'SELECT patient_id, scheme, status, letter_status FROM SAARTHI.CORE.AUTHORIZATION
        WHERE status = ''conflicting'' OR (status IN (''pending'',''approved'',''denied'',''expired'')
          AND letter_status IN (''pending'',''approved'',''denied'',''expired'')
          AND status <> letter_status)
        ORDER BY patient_id'
    ),
    vq_failed_gates_per_gate AS (
      QUESTION 'How many gates failed, by gate?'
      SQL 'SELECT gate, COUNT(*) AS failed_gates FROM SAARTHI.OPERATIONAL.READINESS_STATE WHERE outcome = ''fail'' GROUP BY gate ORDER BY failed_gates DESC'
    ),
    vq_eligible_schemes AS (
      QUESTION 'How many patients are eligible for each scheme?'
      SQL 'SELECT scheme_name, COUNT(*) AS eligible_patients FROM SAARTHI.OPERATIONAL.DT_SCHEME_ELIGIBILITY WHERE eligibility_status = ''eligible'' GROUP BY scheme_name ORDER BY eligible_patients DESC'
    ),
    vq_curable_denials AS (
      QUESTION 'How many denied authorisations are flagged curable?'
      SQL 'SELECT COUNT(*) AS curable_denials FROM SAARTHI.CORE.AUTHORIZATION WHERE status = ''denied'' AND denial_is_curable = TRUE'
    ),
    vq_review_issues_by_state AS (
      QUESTION 'How many review issues are there in each state?'
      SQL 'SELECT state, COUNT(*) AS issues FROM SAARTHI.OPERATIONAL.REVIEW_ISSUE GROUP BY state ORDER BY issues DESC'
    )
  );
    RETURN 'created: SAARTHI_SEMANTIC_VIEW (with 7 verified queries)';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'skipped SAARTHI_SEMANTIC_VIEW (previous view kept; clause syntax unverified): ' || SQLERRM;
END;
$$;
-- ===== END semantic/01_semantic_view.sql (guarded) =====

-- VERIFY: expect one row per name, CREATED just now.
SELECT procedure_name, created FROM SAARTHI.INFORMATION_SCHEMA.PROCEDURES
 WHERE procedure_schema = 'OPERATIONAL' AND procedure_name IN ('EVALUATE_GATES', 'BIND_PATIENT')
 ORDER BY 1;  -- expect 2 rows
SHOW DYNAMIC TABLES LIKE 'DT_SCHEME_ELIGIBILITY' IN SCHEMA SAARTHI.OPERATIONAL;  -- refresh_mode = FULL
