-- 07_governance_row_access.sql: DOC_PAGE row access policy (layer 3 of R5): detach, recreate, canary, re-attach, negative test
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;

-- ===== BEGIN governance/01_policies.sql (section) =====
EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE SAARTHI.DOCUMENTS.DOC_PAGE DROP ROW ACCESS POLICY SAARTHI.GOVERNANCE.patient_scope;
    RETURN 'detached';
EXCEPTION
    WHEN OTHER THEN
        RETURN 'nothing to detach';
END;
$$;

-- N4-03: the policy argument is p_doc_id, NOT doc_id. Inside the subqueries below DOCUMENT d also has a
-- column called doc_id, and an unqualified `doc_id` binds to the innermost scope (d.doc_id), turning
-- `d.doc_id = doc_id` into a tautology: every DOC_PAGE row would be visible to anyone with any care-team
-- link (and to everyone once any reference document exists). The distinct argument name removes the
-- ambiguity. Proved after deploy by the canary test in deploy step 07 (it must see 0 rows).
-- Layer 3 of R5: even a leaked chunk_id yields nothing, because DOC_PAGE
-- content is re-fetched through this policy, keyed on the real caller.
--
-- Two-branch design:
--   Top branch — reference-corpus docs (SPEC R6). Public clinical guidelines
--     (WHO, NCCN, etc.) with no patient PII. Visible to any authenticated
--     caller; no CURRENT_USER() filtering because reference docs have no
--     user-specific access rules. Required for parse_documents_proc's
--     reference loop and chunk_documents_proc to see reference DOC_PAGE
--     rows at all (patient_id IS NULL means the bottom branch can never
--     match a CARE_TEAM row).
--   Bottom branch — patient-scope enforcement, unchanged. F3: keys on
--     CURRENT_USER(), never CURRENT_ROLE(); survives owner's-rights
--     elevation exactly as R5 Layer 3 requires.
CREATE OR REPLACE ROW ACCESS POLICY SAARTHI.GOVERNANCE.patient_scope
  AS (p_doc_id VARCHAR) RETURNS BOOLEAN ->
    EXISTS (
      SELECT 1 FROM SAARTHI.DOCUMENTS.DOCUMENT d
       WHERE d.doc_id = p_doc_id AND d.scope = 'reference'
    )
    OR EXISTS (
      SELECT 1
      FROM SAARTHI.GOVERNANCE.CARE_TEAM ct
      JOIN SAARTHI.GOVERNANCE.PRACTITIONER p
        ON p.practitioner_id = ct.practitioner_id
      JOIN SAARTHI.DOCUMENTS.DOCUMENT d
        ON d.patient_id = ct.patient_id
      WHERE p.snowflake_user = CURRENT_USER()
        AND p.active = TRUE
        AND ct.role_type IN ('treating', 'coordinator')
        AND ct.active_from <= CURRENT_DATE()
        AND d.doc_id = p_doc_id
        AND (ct.active_to IS NULL OR ct.active_to >= CURRENT_DATE())
        -- N3-05: identity/role/active window now match the procedure preamble. Consent is NOT
        -- re-checked here: it is enforced at query time in every procedure preamble (layer 2),
        -- and pipeline procedures that read DOC_PAGE for the deploying user must not lose pages
        -- when a consent window differs. Documented in evidence/qa/FIX-ROUND-3.md.
    );
-- ===== END governance/01_policies.sql =====

-- N4-03 canary: a synthetic patient-scope document whose patient is on NO care team, so no user may ever see its page.
-- Inserted BEFORE the policy is attached (an INSERT is not filtered, a guarded re-run never needs to see the page:
-- the DOCUMENT row, which has no policy, is the idempotency key). Excluded from the verification counts by name.
EXECUTE IMMEDIATE $$
BEGIN
    IF (NOT EXISTS (SELECT 1 FROM SAARTHI.DOCUMENTS.DOCUMENT WHERE doc_id = 'DOC-RAP-CANARY-01')) THEN
        INSERT INTO SAARTHI.DOCUMENTS.DOCUMENT (doc_id, patient_id, scope, doc_type, version, ingested_at, ingestion_method, status)
        VALUES ('DOC-RAP-CANARY-01', 'PAT-RAP-CANARY', 'patient', 'rap_canary', 1, CURRENT_TIMESTAMP(), 'digital_emr', 'duplicate');
        INSERT INTO SAARTHI.DOCUMENTS.DOC_PAGE (doc_id, page_index, text, char_count)
        VALUES ('DOC-RAP-CANARY-01', 0, 'SYNTHETIC RAP CANARY. No care team may read this page.', 53);
        RETURN 'canary inserted';
    END IF;
    RETURN 'canary already present';
END;
$$;

-- ===== BEGIN governance/02_attach_policies.sql (section) =====
ALTER TABLE SAARTHI.DOCUMENTS.DOC_PAGE
  ADD ROW ACCESS POLICY SAARTHI.GOVERNANCE.patient_scope ON (doc_id);
-- ===== END governance/02_attach_policies.sql =====

-- VERIFY: one row, DOC_PAGE.
SELECT policy_name, ref_entity_name FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'));

-- N4-03 cross-patient negative test (fail closed). The canary page belongs to a patient nobody is on the care
-- team of, so the policy must hide it. PASS: this returns 0 rows, and the block below does not raise.
SELECT doc_id, page_index FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-RAP-CANARY-01';  -- expect 0 rows
EXECUTE IMMEDIATE $$
DECLARE
    rap_leak EXCEPTION (-20020, 'FAIL CLOSED: the DOC_PAGE canary page of a patient with no care team is VISIBLE. patient_scope is not filtering (name-binding or attach fault). Do not run steps 08/09; fix 01_policies.sql and re-run step 07.');
    n INTEGER;
BEGIN
    SELECT COUNT(*) INTO :n FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-RAP-CANARY-01';
    IF (n > 0) THEN
        RAISE rap_leak;
    END IF;
    RETURN 'ok: canary page hidden by patient_scope';
END;
$$;
-- Positive control: a patient the running user IS on the care team of must stay visible (1 row, if you are the PRAC-01 user).
SELECT COUNT(*) AS own_patient_pages_visible FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-SURG-NOTE-01';
