-- 08_pipeline_kickoff.sql: document pipeline: chunk, two-pass extract, reconcile, readiness
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;

-- GUARD (fail closed, N4-02/N4-06): the pipeline reads DOC_PAGE through the row access policy as the CURRENT user.
-- It must run as the Snowflake user stored on PRAC-01, the procedures must exist, and the cohort pages must be
-- visible. Otherwise the CALLs below would see nothing and report success.
EXECUTE IMMEDIATE $$
DECLARE
    not_prac01 EXCEPTION (-20011, 'Current user is not the snowflake_user on PRAC-01: the row access policy hides every page from this user. UPDATE SAARTHI.GOVERNANCE.PRACTITIONER SET snowflake_user = <this user> WHERE practitioner_id = PRAC-01 (and ensure the care-team links exist), or run as that user.');
    no_pages EXCEPTION (-20012, 'Cohort documents (DOC-LAB-DC-*, DOC-PATH-DC-*) have no VISIBLE DOC_PAGE rows for this user: run steps 05-06 first, and run as the PRAC-01 user.');
    procs_missing EXCEPTION (-20013, 'A pipeline procedure is missing (parse_documents_proc, chunk_documents_proc, extract_assertions_proc, reconcile_evidence_proc, refresh_readiness_proc). Deploy it from backend/sql/tasks and backend/sql/procedures first.');
    rap_missing EXCEPTION (-20010, 'DOC_PAGE has no PATIENT_SCOPE row access policy. Run step 07 again before anything else.');
    n INTEGER;
BEGIN
    SELECT COUNT(*) INTO :n
      FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'))
     WHERE ref_entity_name = 'DOC_PAGE';
    IF (n = 0) THEN
        RAISE rap_missing;
    END IF;
    SELECT COUNT(*) INTO :n FROM SAARTHI.GOVERNANCE.PRACTITIONER
     WHERE practitioner_id = 'PRAC-01' AND snowflake_user = CURRENT_USER();
    IF (n = 0) THEN
        RAISE not_prac01;
    END IF;
    SELECT COUNT(DISTINCT procedure_name) INTO :n FROM SAARTHI.INFORMATION_SCHEMA.PROCEDURES
     WHERE procedure_schema = 'OPERATIONAL'
       AND procedure_name IN ('PARSE_DOCUMENTS_PROC', 'CHUNK_DOCUMENTS_PROC', 'EXTRACT_ASSERTIONS_PROC',
                              'RECONCILE_EVIDENCE_PROC', 'REFRESH_READINESS_PROC');
    IF (n < 5) THEN
        RAISE procs_missing;
    END IF;
    SELECT COUNT(*) INTO :n FROM SAARTHI.DOCUMENTS.DOCUMENT d
     WHERE (d.doc_id LIKE 'DOC-LAB-DC-%' OR d.doc_id LIKE 'DOC-PATH-DC-%')
       AND NOT EXISTS (SELECT 1 FROM SAARTHI.DOCUMENTS.DOC_PAGE p WHERE p.doc_id = d.doc_id);
    IF (n > 0) THEN
        RAISE no_pages;
    END IF;
    RETURN 'ok: pipeline preconditions hold';
END;
$$;
-- Run each CALL on its own, in order. Spends Cortex credits (two model families, R7). Paste, then run
-- statement by statement (Run, not Run all): extract_assertions_proc handles a bounded batch per call.
CALL SAARTHI.OPERATIONAL.chunk_documents_proc();
CALL SAARTHI.OPERATIONAL.extract_assertions_proc();  -- REPEAT until it reports nothing pending
CALL SAARTHI.OPERATIONAL.extract_assertions_proc();
CALL SAARTHI.OPERATIONAL.reconcile_evidence_proc();
CALL SAARTHI.OPERATIONAL.refresh_readiness_proc();
-- If TASK_PARSE_DOCUMENTS was started in the preflight, re-enable the graph afterwards:
-- SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('SAARTHI.OPERATIONAL.TASK_PARSE_DOCUMENTS');
