-- 09_verify.sql: post-deploy verification (read-only)
-- GENERATED by backend/scripts/build_deploy_bundle.py from repo SQL. Do not edit; rebuild instead.
-- Paste into ONE Snowsight worksheet and use "Run all". Idempotent. Synthetic data only.
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;
USE DATABASE SAARTHI;
USE WAREHOUSE SAARTHI_AI_WH;

-- GUARD (fail closed): DOC_PAGE must carry PATIENT_SCOPE. If not, run step 07 again before anything else.
EXECUTE IMMEDIATE $$
DECLARE
    rap_missing EXCEPTION (-20010, 'DOC_PAGE has no PATIENT_SCOPE row access policy. Run step 07 (04 failure path) again before anything else.');
    n INTEGER;
BEGIN
    SELECT COUNT(*) INTO :n
      FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'))
     WHERE ref_entity_name = 'DOC_PAGE';
    IF (n = 0) THEN
        RAISE rap_missing;
    END IF;
    RETURN 'ok: PATIENT_SCOPE is attached to DOC_PAGE';
END;
$$;
-- All read-only. QUERY_HISTORY is live; ACCESS_HISTORY lags up to 180 minutes (do not mix them up).
-- 1. Documents per patient. PASS: all 12 patients appear. PAT-DC-01..11 carry the manifest documents
--    (16 documents over 11 patients in total, 5 patients with a pathology report). PAT-DEEP-0001 carries
--    DOC-SURG-NOTE-01 (1 page, synthetic), DOC-DUP-ORIG-01, DOC-DUP-COPY-01 (status duplicate), DOC-INJECT-01.
SELECT patient_id, COUNT(*) AS documents, COUNT_IF(status = 'active') AS active
  FROM SAARTHI.DOCUMENTS.DOCUMENT WHERE scope = 'patient' AND doc_id NOT LIKE 'DOC-RAP-CANARY%' GROUP BY 1 ORDER BY 1;
-- 2. Pages. PASS: every manifest and seeded document that has text has a non-empty page; empty = 0 for the 16 manifest docs.
SELECT d.doc_id, COUNT(p.page_index) AS pages, COUNT_IF(p.char_count > 0) AS non_empty
  FROM SAARTHI.DOCUMENTS.DOCUMENT d LEFT JOIN SAARTHI.DOCUMENTS.DOC_PAGE p ON p.doc_id = d.doc_id
 WHERE d.scope = 'patient' AND d.doc_id NOT LIKE 'DOC-RAP-CANARY%' GROUP BY 1 ORDER BY 1;
-- 2b. Duplicate pages (N4-02). PASS: 0 rows.
SELECT doc_id, page_index, COUNT(*) AS n FROM SAARTHI.DOCUMENTS.DOC_PAGE GROUP BY 1, 2 HAVING COUNT(*) > 1;
-- 3. Assertions by status (R7). The counts depend on live model output, so the criterion is an invariant, not a number:
SELECT verification_status, missingness_state, COUNT(*) AS n
  FROM SAARTHI.EVIDENCE.ASSERTION GROUP BY 1, 2 ORDER BY 1, 2;
--    PASS: this returns 0 rows (a verified assertion needs two agreeing passes (NULL = NULL is fine for
--    pending/unreadable) and a source span):
SELECT assertion_id, doc_id FROM SAARTHI.EVIDENCE.ASSERTION
 WHERE verification_status = 'verified'
   AND (pass1_value IS DISTINCT FROM pass2_value OR char_start IS NULL OR char_end IS NULL);
--    PASS: DOC-SURG-NOTE-01 assertions are not 'verified' until the two-pass run has read the page:
SELECT assertion_id, verification_status, missingness_state FROM SAARTHI.EVIDENCE.ASSERTION
 WHERE doc_id = 'DOC-SURG-NOTE-01' ORDER BY 1;
-- 4. Evidence links. PASS: relation 'supports' rows exist once the pipeline has verified numeric lab assertions.
SELECT relation, COUNT(*) AS n FROM SAARTHI.EVIDENCE.EVIDENCE_LINK GROUP BY 1 ORDER BY 1;
-- 5. Gates per patient. PASS: all 12 patients have rows and with_evidence >= 1 (gates cite structured event,
--    coverage, authorization or verified-assertion ids). A patient with with_evidence = 0 is a failure to investigate.
--    Gates with no inputs legitimately keep an empty evidence_ids; those are listed by the second query.
SELECT patient_id, COUNT(*) AS gates, COUNT_IF(ARRAY_SIZE(evidence_ids) > 0) AS with_evidence,
       COUNT_IF(ARRAY_SIZE(evidence_ids) = 0) AS empty
  FROM SAARTHI.OPERATIONAL.READINESS_STATE GROUP BY 1 ORDER BY 1;
SELECT patient_id, rule_id, outcome, reason FROM SAARTHI.OPERATIONAL.READINESS_STATE
 WHERE ARRAY_SIZE(evidence_ids) = 0 ORDER BY 1, 2;
-- 6. Objects. PASS: DT_SCHEME_ELIGIBILITY refresh_mode = FULL; RAP attached to DOC_PAGE only.
SHOW DYNAMIC TABLES LIKE 'DT_SCHEME_ELIGIBILITY' IN SCHEMA SAARTHI.OPERATIONAL;
SELECT policy_name, ref_entity_name, ref_entity_domain FROM TABLE(SAARTHI.INFORMATION_SCHEMA.POLICY_REFERENCES(
  POLICY_NAME => 'SAARTHI.GOVERNANCE.PATIENT_SCOPE'));
--    Cross-patient negative test (N4-03). PASS: 0 rows (the canary page belongs to a patient with no care team):
SELECT doc_id, page_index FROM SAARTHI.DOCUMENTS.DOC_PAGE WHERE doc_id = 'DOC-RAP-CANARY-01';
-- 7. Tasks stay as the checklist recorded them (re-created tasks are SUSPENDED).
SHOW TASKS IN SCHEMA SAARTHI.OPERATIONAL;
-- 8. Timeline/labs state rule (N3-01) is checked in the app, not here (the procedure binds on the caller):
--    /patient/PAT-DC-01 timeline shows the diagnosis event as "Present", never "Not received".
