// Copilot record tools: a deterministic router from a Class B question to the governed reads
// the patient screen already uses, and a composer that turns those rows into an answer card.
// Nothing here is generated by a model (R1). Every status, number and date is copied from a
// SQL read; the sentences are fixed templates over those values. Class A questions never get
// here: the classifier refuses them first (question-routing.mjs).

import { formatClock } from "./display-format.mjs";

/** @typedef {"readiness" | "labs" | "documents" | "coverage" | "timeline" | "conflicts"
 *   | "tasks" | "visit"} RecordTool */

const LAB_CONCEPTS = [
  ["PLT", "Platelets", /\b(platelets?|plt)\b/],
  ["ANC", "Neutrophils (ANC)", /\b(anc|neutrophils?|neutropenia)\b/],
  ["WBC", "White cells (WBC)", /\b(wbc|white (blood )?cells?|leucocytes?|leukocytes?)\b/],
  ["HB", "Haemoglobin", /\b(ha?emoglobin|hb|hgb)\b/],
  ["CREATININE", "Creatinine", /\b(creatinine|crcl|renal|kidney)\b/],
  ["BILIRUBIN", "Bilirubin", /\b(bilirubin|liver|hepatic)\b/],
  ["AST", "AST", /\b(ast|sgot)\b/],
  ["ALT", "ALT", /\b(alt|sgpt)\b/],
  ["HBA1C", "HbA1c", /\b(hba1c|a1c|diabet\w*|glucose)\b/],
  ["LVEF", "LVEF", /\b(lvef|ejection fraction|echo\w*)\b/],
  ["WEIGHT", "Weight", /\bweight\b/],
  ["NEUTROPHIL_PCT", "Neutrophils (%)", /\bneutrophil ?%|\bneutrophil percent\w*/],
];
const LAB_LABEL = Object.fromEntries(LAB_CONCEPTS.map(([concept, label]) => [concept, label]));

// Most specific first: a question about "conflicting lab values" is a conflicts question.
const TOOL_PATTERNS = /** @type {[RecordTool, RegExp][]} */ ([
  ["conflicts", /\b(conflict\w*|contradict\w*|disagree\w*|mismatch\w*|discrepan\w*|inconsisten\w*)\b/],
  ["tasks", /\b(tasks?|assigned|owners?|follow-?ups?|escalat\w*|who is (handling|working|responsible))\b/],
  ["coverage", /\b(coverage|covered|insur\w*|pre-?auth\w*|authori[sz]\w*|schemes?|pm-?jay|payers?|claims?|annual limit|cashless)\b/],
  ["documents", /\b(documents?|reports?|pdfs?|letters?|uploaded|scanned|paperwork|files?|received)\b/],
  ["timeline", /\b(timeline|history|chronolog\w*|recent(ly)?|what happened|what changed|since)\b/],
  ["visit", /\b(next visit|appointment|scheduled|schedule|which cycle|cycle number|regimen|day-?care visit|medications?|medicines?|drugs?|treatment plan|protocol)\b/],
  ["labs", /\b(labs?|blood|cbc|counts?|results?|values?|levels?)\b/],
  ["readiness", /\b(ready|readiness|missing|block\w*|checks?|gates?|outstanding|pending|status|summar\w*|overview|issues?|problems?|stopping|holding|clear(ed)?|what do we have|tell me about|brief|documented|gaps?|recap|consent)\b/],
]);

const CHECK_GROUPS = [
  ["identity", /\b(identity|abha|mrn|identifiers?|linkage)\b/],
  ["documentation", /\b(documentation|pathology|her2)\b/],
  ["safety", /\b(safety|dexa|bone)\b/],
  ["clinical", /\b(clinical)\b/],
];

/**
 * @param {string} question the user's own words (without the on-screen context preamble)
 * @param {{kind: string, id: string}[]} [references] items the user attached from the screen
 * @returns {{tool: RecordTool, concepts: string[], ruleIds: string[], eventIds: string[],
 *   documentIds: string[], group: string | null} | null}
 */
export function matchRecordTool(question, references = []) {
  const text = question.toLowerCase();
  const ruleIds = references.filter((item) => item.kind === "check").map((item) => item.id);
  const eventIds = references.filter((item) => item.kind === "fact").map((item) => item.id);
  const documentIds = references.filter((item) => item.kind === "document").map((item) => item.id);
  const concepts = LAB_CONCEPTS.filter(([, , pattern]) => pattern.test(text))
    .map(([concept]) => concept);
  const group = CHECK_GROUPS.find(([, pattern]) => pattern.test(text))?.[0] ?? null;
  // A medication question is answered by the visit card, led by the recorded regimen.
  const focus = /\b(medications?|medicines?|drugs?|regimen|treatment plan|protocol|chemo(therapy)? is)\b/
    .test(text) ? "regimen" : null;
  const base = { concepts, ruleIds, eventIds, documentIds, group, focus };
  const named = TOOL_PATTERNS.find(([, pattern]) => pattern.test(text))?.[0] ?? null;
  // Words name the tool; without them, attached items do, then a named lab value.
  if (named === "labs" || (!named && concepts.length)) return { ...base, tool: "labs" };
  if (named) return { ...base, tool: named };
  if (documentIds.length) return { ...base, tool: "documents" };
  if (eventIds.length) return { ...base, tool: "labs" };
  if (ruleIds.length || group) return { ...base, tool: "readiness" };
  return null;
}

// Measured on imaging (echo, DEXA), not in a lab: the facts read covers lab and vitals
// events only, so these are read from the timeline, which carries every event type.
const IMAGING_CONCEPTS = new Set(["LVEF", "T_SCORE"]);

/** Which governed reads a tool needs. "snapshot" is always read for clocks and checks. */
export function readsFor(tool, concepts = []) {
  const imaging = concepts.some((concept) => IMAGING_CONCEPTS.has(concept));
  return {
    readiness: ["snapshot"],
    labs: imaging ? ["snapshot", "labs", "timeline"] : ["snapshot", "labs"],
    documents: ["snapshot", "documents"],
    coverage: ["snapshot", "coverage", "schemes"],
    timeline: ["snapshot", "timeline"],
    conflicts: ["snapshot", "documents", "labs"],
    tasks: ["snapshot", "tasks"],
    visit: ["snapshot"],
  }[tool];
}

// ------------------------------------------------------------------------------ helpers

const STATE_WORDS = {
  present: "Received", explicitly_negative: "Recorded negative", pending: "Pending",
  not_received: "Not received", conflicting: "Conflict", unreadable: "Unreadable",
  superseded: "Superseded",
};
const STATE_TONES = {
  present: "neutral", explicitly_negative: "neutral", pending: "warning",
  not_received: "warning", conflicting: "critical", unreadable: "warning", superseded: "neutral",
};

/** @param {{outcome: string, severity?: string}} gate */
export function gateState(gate) {
  if (gate.outcome === "pass") return { state: "Met", tone: "positive" };
  if (gate.outcome === "conflicting") return { state: "Conflict", tone: "critical" };
  if (gate.outcome === "not_evaluated") return { state: "Not evaluated", tone: "warning" };
  return gate.severity === "advisory"
    ? { state: "Advisory", tone: "warning" } : { state: "Blocked", tone: "critical" };
}

const RANK = { Blocked: 0, Conflict: 1, "Not evaluated": 2, Advisory: 3, Met: 4 };

function number(value) {
  return Number.isInteger(value) ? value.toLocaleString("en-IN") : String(value);
}

/** @param {{value?: number | null, value_text?: string | null, unit?: string | null,
 *   value_state?: string}} fact */
function factValue(fact) {
  if (typeof fact.value === "number") return [number(fact.value), fact.unit].filter(Boolean).join(" ");
  if (fact.value_text) return fact.value_text;
  return STATE_WORDS[fact.value_state ?? "not_received"] ?? "Not received";
}

function humanize(value) {
  const text = String(value ?? "").replace(/_/g, " ").trim();
  return text ? text[0].toUpperCase() + text.slice(1) : "Unlabelled";
}

function plural(count, one, many = `${one}s`) {
  return `${count} ${count === 1 ? one : many}`;
}

/** Gates that cite this event and did not pass: the record check that flagged it. */
function flaggingGate(gates, eventId) {
  return gates.find((gate) => gate.outcome !== "pass" && gate.evidence_ids?.includes(eventId));
}

const MAX_ITEMS = 8;

function card(tool, fields) {
  const items = fields.items ?? [];
  return {
    tool, title: fields.title, summary: fields.summary,
    items: items.slice(0, MAX_ITEMS), more: Math.max(0, items.length - MAX_ITEMS),
    actions: (fields.actions ?? []).slice(0, 2),
    known_as_of: fields.knownAsOf ?? null,
    sources: [...new Set(fields.sources ?? [])].slice(0, 100),
    basis: fields.basis ?? null,
  };
}

// ----------------------------------------------------------------------------- composers

/**
 * @param {ReturnType<typeof matchRecordTool> & {}} match
 * @param {{patient: {gates: object[], knownAsOf: string | null, patientName: string,
 *   nextVisit?: string | null, scheduledAt?: string | null, cycleNumber?: number | null,
 *   regimen?: string | null, treatingPractitionerName?: string | null},
 *   labs?: {facts: object[], known_as_of?: string}, documents?: {rows: object[],
 *   expected_documents: object[], known_as_of?: string},
 *   coverage?: {rows: object[], known_as_of?: string}, schemes?: object[],
 *   timeline?: {timeline: object[], known_as_of: string, truncated?: boolean},
 *   tasks?: Record<string, object[]>}} reads
 */
export function composeRecordAnswer(match, reads) {
  const compose = { readiness, labs, documents, coverage, timeline, conflicts, tasks, visit }[match.tool];
  return compose(match, reads);
}

function readiness(match, { patient }) {
  let gates = patient.gates;
  let scope = "record checks";
  if (match.ruleIds.length) {
    gates = gates.filter((gate) => match.ruleIds.includes(gate.rule_id));
    scope = "selected record checks";
  } else if (match.group) {
    gates = gates.filter((gate) => gate.gate === match.group);
    scope = `${match.group} record checks`;
  }
  const rows = gates.map((gate) => ({ gate, ...gateState(gate) }))
    .sort((a, b) => RANK[a.state] - RANK[b.state]
      || String(a.gate.rule_id).localeCompare(String(b.gate.rule_id)));
  const open = rows.filter((row) => row.state !== "Met");
  const counts = ["Blocked", "Conflict", "Not evaluated", "Advisory"]
    .map((state) => [state, open.filter((row) => row.state === state).length])
    .filter(([, count]) => count > 0)
    .map(([state, count]) => `${count} ${String(state).toLowerCase()}`);
  const summary = !rows.length
    ? `No ${scope} were returned for ${patient.patientName}.`
    : open.length
      ? `${open.length} of ${plural(rows.length, scope.replace(/s$/, ""), scope)} need attention: `
        + `${counts.join(", ")}. ${rows.length - open.length} met.`
      : `All ${plural(rows.length, scope.replace(/s$/, ""), scope)} are met.`;
  return card("readiness", {
    title: "Record checks",
    summary,
    // Only what needs attention; met checks are counted in the summary, not listed.
    items: (match.ruleIds.length ? rows : open)
      .map(({ gate, state, tone }) => ({
        id: gate.rule_id, label: humanize(gate.gate) + " · " + gate.rule_id,
        value: gate.reason ?? "No reason recorded", state, tone, ruleId: gate.rule_id,
        note: gate.rule_version ? `Rule version ${gate.rule_version}` : null,
      })),
    actions: open.length ? [{ label: "Open review", section: "Review" }]
      : [{ label: "Open overview", section: "Overview" }],
    knownAsOf: patient.knownAsOf,
    sources: gates.flatMap((gate) => gate.evidence_ids ?? []),
    basis: "Outcomes are computed by versioned SQL rules, not by the assistant.",
  });
}

function labs(match, { patient, labs: read, timeline }) {
  const measured = /** @type {any[]} */ (read?.facts ?? []);
  const imaging = /** @type {any[]} */ (timeline?.timeline ?? []).filter((event) =>
    IMAGING_CONCEPTS.has(event.concept) && !measured.some((fact) => fact.event_id === event.event_id));
  const facts = [...measured, ...imaging];
  let chosen = facts;
  if (match.eventIds.length) chosen = facts.filter((fact) => match.eventIds.includes(fact.event_id));
  else if (match.concepts.length) chosen = facts.filter((fact) => match.concepts.includes(fact.concept));
  const asked = match.concepts.map((concept) => LAB_LABEL[concept] ?? concept);
  const items = chosen.map((fact) => {
    const flag = flaggingGate(patient.gates, fact.event_id);
    const flagged = flag ? gateState(flag) : null;
    const state = flagged ?? (fact.value_state && fact.value_state !== "present"
      ? { state: STATE_WORDS[fact.value_state] ?? fact.value_state,
        tone: STATE_TONES[fact.value_state] ?? "warning" }
      : { state: "Recorded", tone: "neutral" });
    return {
      id: fact.event_id, label: LAB_LABEL[fact.concept] ?? humanize(fact.concept),
      value: factValue(fact), ...state, ruleId: flag?.rule_id ?? null,
      note: [`Taken ${formatClock(fact.event_time)}`,
        fact.is_derived && fact.derivation ? fact.derivation : null,
        flag ? `${flag.rule_id}: ${flag.reason}` : null].filter(Boolean).join(" · "),
    };
  }).sort((a, b) => Number(!a.ruleId) - Number(!b.ruleId));
  const missing = asked.filter((label) => !items.some((item) => item.label === label));
  const flaggedCount = items.filter((item) => item.ruleId).length;
  let summary;
  if (!items.length) {
    summary = asked.length
      ? `No ${asked.join(" or ")} result is on record as of ${formatClock(read?.known_as_of ?? patient.knownAsOf)}. Not received is not the same as normal.`
      : "No lab results are on record for this cutoff.";
  } else if (items.length === 1) {
    const [item] = items;
    const fact = chosen.find((candidate) => candidate.event_id === item.id);
    summary = `${item.label}: ${item.value}, taken ${formatClock(fact?.event_time)}.`
      + (item.ruleId ? ` Flagged by ${item.ruleId}.` : "");
  } else if (new Set(items.map((item) => item.label)).size === 1) {
    // One test measured more than once (an echo series): latest first, then the one before.
    const series = [...chosen].sort((a, b) => String(b.event_time).localeCompare(String(a.event_time)));
    const [latest, previous] = series;
    const flag = items.find((item) => item.ruleId)?.ruleId;
    summary = `${items[0].label}: ${factValue(latest)} on ${formatClock(latest.event_time)}, `
      + `previously ${factValue(previous)} on ${formatClock(previous.event_time)}.`
      + (flag ? ` Flagged by ${flag}.` : "");
  } else {
    summary = `${plural(items.length, "latest lab value")} on record; `
      + `${flaggedCount ? `${flaggedCount} flagged by a record check` : "none flagged by a record check"}.`;
  }
  if (items.length && missing.length) summary += ` No ${missing.join(" or ")} result on record.`;
  return card("labs", {
    title: asked.length ? asked.join(", ") : "Lab results",
    summary, items,
    actions: [{ label: "Open facts", section: "Facts" }],
    knownAsOf: read?.known_as_of ?? patient.knownAsOf,
    sources: items.map((item) => item.id),
    basis: "Latest value per test at the record cutoff. Derived values show their formula.",
  });
}

function documents(match, { patient, documents: read }) {
  const rows = /** @type {any[]} */ (read?.rows ?? []);
  const expected = /** @type {any[]} */ (read?.expected_documents ?? []);
  const chosen = match.documentIds.length
    ? rows.filter((row) => match.documentIds.includes(row.doc_id)) : rows;
  const items = [
    ...expected.map((row) => ({
      id: row.doc_id ?? row.doc_type, label: humanize(row.doc_type ?? row.document_type),
      value: "Expected, not received", state: STATE_WORDS.not_received, tone: "warning",
      note: row.reason ?? row.rule_id ?? null, documentId: null,
    })),
    ...chosen.map((row) => {
      const conflicting = Number(row.conflicting_assertions ?? 0);
      const state = conflicting ? "conflicting" : row.missingness_state ?? "present";
      return {
        id: row.doc_id, label: humanize(row.doc_type),
        value: [row.source_facility, formatClock(row.event_time)].filter(Boolean).join(" · "),
        state: STATE_WORDS[state] ?? humanize(state), tone: STATE_TONES[state] ?? "neutral",
        note: (Number(row.assertion_count ?? 0)
          ? `${plural(Number(row.verified_assertions ?? 0), "value")} verified of `
            + `${Number(row.assertion_count)} extracted`
          : "No values extracted yet")
          + (conflicting ? ` · ${plural(conflicting, "conflicting value")}` : "")
          + ` · ${plural(Number(row.page_count ?? 0), "page")}`,
        documentId: row.doc_id,
      };
    }),
  ];
  const summary = `${plural(chosen.length, "document")} on record`
    + (expected.length ? `; ${plural(expected.length, "expected document")} not received.`
      : "; no expected document is outstanding.");
  return card("documents", {
    title: "Documents", summary, items,
    actions: [{ label: "Open documents", section: "Documents" }],
    knownAsOf: read?.known_as_of ?? patient.knownAsOf,
    sources: chosen.map((row) => row.doc_id),
    basis: "Values are verified only when two independent extraction passes agree.",
  });
}

function coverage(match, { patient, coverage: read, schemes = [] }) {
  const gates = patient.gates.filter((gate) => gate.gate === "coverage");
  const row = /** @type {any} */ (read?.rows?.[0] ?? {});
  const items = [
    ...gates.map((gate) => ({ id: gate.rule_id, label: `Coverage · ${gate.rule_id}`,
      value: gate.reason ?? "No reason recorded", ...gateState(gate), ruleId: gate.rule_id,
      note: null })),
    ...(row.authorizations ?? []).map((auth) => ({
      id: auth.auth_id, label: `Pre-authorisation · ${auth.payer_name ?? "payer not recorded"}`,
      value: [auth.requested_at ? `Requested ${formatClock(auth.requested_at)}` : null,
        auth.decided_at ? `decided ${formatClock(auth.decided_at)}` : "no decision recorded"]
        .filter(Boolean).join(", "),
      state: auth.letter_status && auth.letter_status !== auth.status ? "Conflict" : humanize(auth.status),
      tone: auth.letter_status && auth.letter_status !== auth.status ? "critical"
        : auth.status === "approved" ? "positive" : "warning",
      note: [auth.expires_at ? `Expires ${formatClock(auth.expires_at)}` : null,
        auth.letter_status && auth.letter_status !== auth.status
          ? `Letter says ${auth.letter_status}, table says ${auth.status}` : null]
        .filter(Boolean).join(" · ") || null,
    })),
    ...schemes.map((scheme) => ({
      id: scheme.schemeId, label: `Scheme · ${scheme.schemeName}`,
      value: Array.isArray(scheme.packages) && scheme.packages.length
        ? `${plural(scheme.packages.length, "covered package")}: ${scheme.packages.join(", ")}`
        : "No covered packages listed",
      state: humanize(scheme.status), tone: scheme.status === "eligible" ? "positive" : "neutral",
      note: scheme.annualLimit ? `Annual limit ₹${number(scheme.annualLimit)}` : null,
    })),
  ];
  const open = gates.filter((gate) => gate.outcome !== "pass");
  const summary = !gates.length ? "No coverage checks were returned for this patient."
    : open.length ? `${plural(open.length, "coverage check")} not met: ${open[0].reason ?? open[0].rule_id}.`
      : `Coverage checks met: ${gates.map((gate) => gate.reason).filter(Boolean).join("; ")}.`;
  return card("coverage", {
    title: "Coverage and pre-authorisation", summary, items,
    actions: [{ label: "Open coverage", section: "Coverage" }],
    knownAsOf: read?.known_as_of ?? patient.knownAsOf,
    sources: [...gates.flatMap((gate) => gate.evidence_ids ?? []),
      ...(row.authorizations ?? []).map((auth) => auth.auth_id)],
    basis: "Family-floater balances are flagged, never computed.",
  });
}

function timeline(match, { patient, timeline: read }) {
  const events = /** @type {any[]} */ ([...(read?.timeline ?? [])])
    .sort((a, b) => String(b.event_time).localeCompare(String(a.event_time)));
  const items = events.map((event) => ({
    id: event.event_id, label: LAB_LABEL[event.concept] ?? humanize(event.concept),
    value: factValue(event), state: humanize(event.event_type ?? "event"), tone: "neutral",
    note: `${formatClock(event.event_time)}${event.is_derived ? " · derived" : ""}`,
  }));
  const summary = events.length
    ? `${plural(events.length, "event")} on record; most recent ${items[0].label.toLowerCase()} on ${formatClock(events[0].event_time)}.`
      + (read?.truncated ? " The timeline is truncated; open it for the full list." : "")
    : "No timeline events are on record.";
  return card("timeline", {
    title: "Recent record events", summary, items,
    actions: [{ label: "Open timeline", section: "Timeline" }],
    knownAsOf: read?.known_as_of ?? patient.knownAsOf,
    sources: items.slice(0, MAX_ITEMS).map((item) => item.id),
    basis: "Ordered by when each event happened, not when it was received.",
  });
}

function conflicts(match, { patient, documents: docs, labs: lab }) {
  const gates = patient.gates.filter((gate) => gate.outcome === "conflicting");
  const docRows = /** @type {any[]} */ (docs?.rows ?? [])
    .filter((row) => Number(row.conflicting_assertions ?? 0) > 0);
  const facts = /** @type {any[]} */ (lab?.facts ?? [])
    .filter((fact) => fact.value_state === "conflicting");
  const items = [
    ...gates.map((gate) => ({ id: gate.rule_id, label: `${humanize(gate.gate)} · ${gate.rule_id}`,
      value: gate.reason ?? "Sources disagree", state: "Conflict", tone: "critical",
      ruleId: gate.rule_id, note: null })),
    ...docRows.map((row) => ({ id: row.doc_id, label: humanize(row.doc_type),
      value: `${plural(Number(row.conflicting_assertions), "value")} where the two readings disagree`,
      state: "Conflict", tone: "critical", note: row.source_facility ?? null,
      documentId: row.doc_id })),
    ...facts.map((fact) => ({ id: fact.event_id, label: LAB_LABEL[fact.concept] ?? humanize(fact.concept),
      value: "Sources disagree", state: "Conflict", tone: "critical",
      note: `Taken ${formatClock(fact.event_time)}` })),
  ];
  const summary = items.length
    ? `${plural(items.length, "conflict")} on record: ${plural(gates.length, "record check")}, `
      + `${plural(docRows.length, "document")}, ${plural(facts.length, "lab value")}. `
      + "A check in conflict is not evaluated until the sources are reconciled."
    : `No conflicts found across ${plural(patient.gates.length, "record check")}, `
      + `${plural((docs?.rows ?? []).length, "document")} and `
      + `${plural((lab?.facts ?? []).length, "lab value")}.`;
  return card("conflicts", {
    title: "Conflicting sources", summary, items,
    actions: items.length ? [{ label: "Open review", section: "Review" }] : [],
    knownAsOf: patient.knownAsOf,
    sources: items.map((item) => item.id),
    basis: "Checked: rule outcomes, document readings and lab values at this cutoff.",
  });
}

function tasks(match, { patient, tasks: byRule = {} }) {
  const rows = Object.entries(byRule).flatMap(([ruleId, list]) =>
    /** @type {any[]} */ (list).filter((task) => !task.isEvent).map((task) => ({ ...task, ruleId })));
  const items = rows.map((task) => ({
    id: task.taskId, label: `${humanize(task.action)} · ${task.ruleId}`,
    value: task.owner || "Unassigned", state: humanize(task.state),
    tone: task.state === "resolved" || task.state === "closed" ? "positive" : "warning",
    ruleId: task.ruleId, note: [task.createdAt ? `Opened ${formatClock(task.createdAt)}` : null,
      task.reason || null].filter(Boolean).join(" · ") || null,
  }));
  const open = patient.gates.filter((gate) => gate.outcome !== "pass").length;
  const summary = items.length
    ? `${plural(items.length, "review task")} across ${plural(Object.keys(byRule).length, "open check")}.`
    : open ? `No review tasks yet for the ${plural(open, "open record check")}.`
      : "No open record checks, so no review tasks.";
  return card("tasks", {
    title: "Review tasks", summary, items,
    actions: [{ label: "Open review", section: "Review" }],
    knownAsOf: patient.knownAsOf,
    sources: items.map((item) => item.id),
  });
}

function visit(match, { patient }) {
  const at = patient.scheduledAt;
  // The visit is compared with the answer clock, so a past visit is never called "next".
  const past = Boolean(at && patient.now && at < patient.now);
  const recorded = (value, label) => ({ state: value ? "Recorded" : "Not received",
    tone: value ? "neutral" : "warning", value: value ?? `${label} not recorded` });
  const items = [
    { id: "visit", label: past ? "Last scheduled visit" : "Next visit",
      value: at ? formatClock(at) : "No visit scheduled",
      state: !at ? "Not received" : past ? "Past" : "Scheduled",
      tone: !at || past ? "warning" : "neutral", note: null },
    { id: "cycle", label: "Cycle", note: null,
      ...recorded(patient.cycleNumber ? `Cycle ${patient.cycleNumber}` : null, "Cycle") },
    { id: "regimen", label: "Regimen", note: null, ...recorded(patient.regimen, "Regimen") },
    { id: "practitioner", label: "Treating practitioner", note: null,
      ...recorded(patient.treatingPractitionerName, "Treating practitioner") },
  ];
  const cycle = patient.cycleNumber ? `, cycle ${patient.cycleNumber}` : "";
  if (match.focus === "regimen") {
    const regimen = items.splice(2, 1)[0];
    items.unshift(regimen);
  }
  return card("visit", {
    title: match.focus === "regimen" ? "Treatment" : "Visit", items,
    summary: match.focus === "regimen"
      ? (patient.regimen
        ? `${patient.patientName}'s recorded regimen is ${patient.regimen}`
          + `${patient.cycleNumber ? `; cycle ${patient.cycleNumber}` : ""}`
          + `${at && !past ? ` is due ${formatClock(at)}` : ""}.`
        : `No regimen is recorded for ${patient.patientName}.`)
      : !at ? `No day-care visit is scheduled for ${patient.patientName}.`
      : past ? `${patient.patientName}'s last scheduled day-care visit was ${formatClock(at)}${cycle}. `
        + "No later visit is on record."
        : `${patient.patientName}'s next day-care visit is ${formatClock(at)}${cycle}.`,
    actions: [{ label: "Open overview", section: "Overview" }],
    knownAsOf: patient.knownAsOf,
  });
}

// Every suggestion is worded so the Class A/B classifier (classify_question.sql) recognises it
// as record-state language without the LLM fallback; copilot-tools.test.mjs checks this
// against the SQL patterns. Wording that reaches the fallback is refused when it is
// unavailable, which is correct (fail closed) but makes a suggestion useless.
const ASK = {
  readiness: "What is missing in the record?",
  labs: "Show me the latest lab results",
  documents: "Which documents are pending or not received?",
  coverage: "Status of pre-authorisation and coverage",
  timeline: "Show me the recent timeline",
  conflicts: "Show me the conflicts in the record",
  tasks: "List the open review tasks",
  visit: "Show me the visit schedule",
};

/** The classifier-recognised wording for a tool, used when a request names the tool as an
 * instruction ("show what's missing") rather than asking in its own words. */
export function recordToolQuestion(tool) {
  return ASK[tool] ?? null;
}

/** Follow-on questions per tool: the next thing a coordinator usually asks. */
export function followOns(tool) {
  return {
    readiness: [ASK.documents, ASK.conflicts],
    labs: [ASK.readiness, ASK.timeline],
    documents: [ASK.conflicts, ASK.readiness],
    coverage: [ASK.readiness, ASK.documents],
    timeline: [ASK.labs, ASK.readiness],
    conflicts: [ASK.documents, ASK.tasks],
    tasks: [ASK.readiness, ASK.conflicts],
    visit: [ASK.readiness, ASK.labs],
  }[tool];
}

/** Starter questions, and the list shown when no tool matches. */
export const RECORD_TOOL_STARTERS = [ASK.readiness, ASK.labs, ASK.documents, ASK.coverage];
