-- =============================================================================
-- STEP 9b - PAT-facing role for external MCP clients   *** MANUAL STEP ***
-- =============================================================================
-- Deliberately NOT in setup.sql. PATs are per-operator secrets that must be
-- generated by a human, copied ONCE at creation time, and stashed via
-- `cortex secret store mcp_pat`. Automating that would defeat the point.
--
-- This file provisions a least-privileged role for MCP callers. Per Snowflake
-- docs (docs.snowflake.com/user-guide/snowflake-cortex/cortex-agents-mcp):
--   "When using a Programmatic Access Token (PAT), set it to use the
--    least-privileged role allowed to work with MCP. This will help prevent
--    leaking a secret with access to a highly-privileged role."
--
-- The role gets USAGE on the MCP server, the agent, the warehouse and the
-- agent's eight tool procedures - no table SELECT, no internal procedure.
-- Every query goes through SAARTHI_AGENT. Note that this path does NOT run
-- classify_question or validate_answer (those guard ask_saarthi, which the
-- apps call); see agent/saarthi_mcp.sql. R5 layers 1-3 still hold.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SAARTHI_MCP_CLIENT
    COMMENT = 'Least-privileged role for external MCP clients (Claude Desktop, Cursor, curl). USAGE on the MCP server + agent + warehouse only. No table SELECT. No procedure EXECUTE outside the agent chain.';

-- Zero-blast-radius baseline. Every grant below is the minimum the MCP
-- endpoint needs to answer a request; anything else would broaden the
-- attack surface if the PAT leaks.
GRANT USAGE ON DATABASE SAARTHI TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON SCHEMA SAARTHI.OPERATIONAL TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON WAREHOUSE SAARTHI_AI_WH TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON MCP SERVER SAARTHI.OPERATIONAL.SAARTHI_MCP TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON AGENT SAARTHI.OPERATIONAL.SAARTHI_AGENT TO ROLE SAARTHI_MCP_CLIENT;

-- The agent invokes its 8 tool procedures within the caller's session, so
-- the caller needs USAGE on exactly those (without it the first tool call
-- fails with "Unknown user-defined function ...GET_READINESS"). Each is
-- EXECUTE AS OWNER and re-checks binding, care team and consent itself.
--
-- Named grants only. An earlier version granted ALL and FUTURE procedures,
-- which exposed EVALUATE_GATES(patient_id, ...) and every task body to a
-- token holder - contradicting this file's own "no procedure EXECUTE outside
-- the agent chain" promise above.
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_PATIENT_FACTS(VARCHAR, VARCHAR)          TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_READINESS(VARCHAR, VARCHAR)              TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.SEARCH_PATIENT_DOCUMENTS(VARCHAR, VARCHAR)   TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.SEARCH_REFERENCE_DOCUMENTS(VARCHAR, VARCHAR, VARCHAR) TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.COHORT_QUERY(VARCHAR)                        TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_TIMELINE(VARCHAR)                        TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_CHANGES(VARCHAR, VARCHAR)                TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.CREATE_REVIEW_TASK(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE SAARTHI_MCP_CLIENT;

-- Grant the role to the user who will hold the PAT. DAKSHA is the operator
-- on account JN89282; substitute the operator's user on any other account. Do NOT
-- grant this role to service accounts that also hold ACCOUNTADMIN or
-- SAARTHI_APP - the whole point is a dedicated identity.
GRANT ROLE SAARTHI_MCP_CLIENT TO USER DAKSHA;

-- =============================================================================
-- Network policy - REQUIRED by Snowflake for PAT authentication.
-- =============================================================================
-- Without a network policy attached to the user, PAT auth fails at the wire
-- with HTTP 401 { "code": "390432", "message": "Network policy is required." }.
-- This is a hard Snowflake constraint, not something the app can bypass.
--
-- SAARTHI_MCP_DEMO_POLICY is deliberately permissive (0.0.0.0/0) so a judge
-- on any network can reproduce the demo without asking us to allowlist their
-- IP. Narrow this to specific CIDRs before running in production. Snowflake
-- also supports IPv6 CIDRs (::/0) if the operator's ISP is IPv6-only.
CREATE OR REPLACE NETWORK POLICY SAARTHI_MCP_DEMO_POLICY
    ALLOWED_IP_LIST = ('0.0.0.0/0')
    COMMENT = 'PERMISSIVE demo policy for MCP PAT auth. Deliberately allows all IPs so judges on any network can reproduce the demo. Narrow to specific CIDRs in production.';

ALTER USER DAKSHA SET NETWORK_POLICY = SAARTHI_MCP_DEMO_POLICY;

-- =============================================================================
-- PAT GENERATION - RUN MANUALLY, COPY THE TOKEN ONCE, THEN STASH IT.
-- =============================================================================
-- After running the section above, run the statement below in a *separate*
-- interactive session. Snowflake prints the token exactly once. Copy it
-- immediately into `cortex secret store mcp_pat` and never paste it into
-- any file, chat, or ticket.
--
--   ALTER USER DAKSHA ADD PROGRAMMATIC ACCESS TOKEN SAARTHI_MCP_PAT
--       ROLE_RESTRICTION = 'SAARTHI_MCP_CLIENT'
--       DAYS_TO_EXPIRY = 30
--       COMMENT = 'SAARTHI MCP client - least-privileged, expires in 30 days';
--
-- Verify with:
--   SHOW USER PROGRAMMATIC ACCESS TOKENS FOR USER DAKSHA;
--
-- Rotate via `ALTER USER ... ROTATE ...` before the 30-day mark. Revoke
-- immediately if the laptop holding the secret is ever lost.
