-- =============================================================================
-- STEP 9b - PAT-facing role for external MCP clients   *** MANUAL STEP ***
-- =============================================================================
-- Deliberately NOT in setup.sql. PATs are per-operator secrets that must be
-- generated by a human, copied ONCE at creation time, and stashed via
-- `cortex secret store mcp_pat`. Automating that would defeat the point.
--
-- This file provisions a least-privileged role for MCP callers. Per Snowflake
-- docs (docs.snowflake.com/user-guide/snowflake-cortex/cortex-agents-mcp):
--   "When using a Programmatic Access Token (PAT), set it to use the
--    least-privileged role allowed to work with MCP. This will help prevent
--    leaking a secret with access to a highly-privileged role."
--
-- The role has USAGE and nothing else - no direct table SELECT, no procedure
-- EXECUTE outside the agent's owner's-rights chain. Every actual query goes
-- through SAARTHI_AGENT and therefore through classify_question +
-- validate_answer. R5 layers 1-3 remain intact end-to-end.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SAARTHI_MCP_CLIENT
    COMMENT = 'Least-privileged role for external MCP clients (Claude Desktop, Cursor, curl). USAGE on the MCP server + agent + warehouse only. No table SELECT. No procedure EXECUTE outside the agent chain.';

-- Zero-blast-radius baseline. Every grant below is the minimum the MCP
-- endpoint needs to answer a request; anything else would broaden the
-- attack surface if the PAT leaks.
GRANT USAGE ON DATABASE SAARTHI TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON SCHEMA SAARTHI.OPERATIONAL TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON WAREHOUSE SAARTHI_AI_WH TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON MCP SERVER SAARTHI.OPERATIONAL.SAARTHI_MCP TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON AGENT SAARTHI.OPERATIONAL.SAARTHI_AGENT TO ROLE SAARTHI_MCP_CLIENT;

-- The agent invokes its 8 tool procedures within the caller's session.
-- Every one is EXECUTE AS OWNER, so the procedure body still runs under
-- ACCOUNTADMIN with owner's rights and can read the RAP-protected tables
-- via the agent's owner grants - the caller only needs USAGE (the
-- "entry key") to invoke them. Without this, the agent hits
-- "Unknown user-defined function SAARTHI.OPERATIONAL.GET_READINESS" and
-- the whole session fails at the first tool call.
--
-- Grant USAGE on ALL + FUTURE procedures in OPERATIONAL rather than
-- enumerating the 8 tool procedures, because (a) the agent tool list
-- may grow (see SPEC.md §12), (b) all procedures in this schema are
-- EXECUTE AS OWNER so exposure risk is uniform, and (c) SAARTHI_APP
-- already has this exact grant - the two roles need parity here.
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SAARTHI.OPERATIONAL TO ROLE SAARTHI_MCP_CLIENT;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SAARTHI.OPERATIONAL TO ROLE SAARTHI_MCP_CLIENT;

-- Grant the role to the user who will hold the PAT. Change DAKSHA to the
-- operator user if this is being provisioned for someone else. Do NOT
-- grant this role to service accounts that also hold ACCOUNTADMIN or
-- SAARTHI_APP - the whole point is a dedicated identity.
GRANT ROLE SAARTHI_MCP_CLIENT TO USER DAKSHA;

-- =============================================================================
-- Network policy - REQUIRED by Snowflake for PAT authentication.
-- =============================================================================
-- Without a network policy attached to the user, PAT auth fails at the wire
-- with HTTP 401 { "code": "390432", "message": "Network policy is required." }.
-- This is a hard Snowflake constraint, not something the app can bypass.
--
-- SAARTHI_MCP_DEMO_POLICY is deliberately permissive (0.0.0.0/0) so a judge
-- on any network can reproduce the demo without asking us to allowlist their
-- IP. Narrow this to specific CIDRs before running in production. Snowflake
-- also supports IPv6 CIDRs (::/0) if the operator's ISP is IPv6-only.
CREATE OR REPLACE NETWORK POLICY SAARTHI_MCP_DEMO_POLICY
    ALLOWED_IP_LIST = ('0.0.0.0/0')
    COMMENT = 'PERMISSIVE demo policy for MCP PAT auth. Deliberately allows all IPs so judges on any network can reproduce the demo. Narrow to specific CIDRs in production.';

ALTER USER DAKSHA SET NETWORK_POLICY = SAARTHI_MCP_DEMO_POLICY;

-- =============================================================================
-- PAT GENERATION - RUN MANUALLY, COPY THE TOKEN ONCE, THEN STASH IT.
-- =============================================================================
-- After running the section above, run the statement below in a *separate*
-- interactive session. Snowflake prints the token exactly once. Copy it
-- immediately into `cortex secret store mcp_pat` and never paste it into
-- any file, chat, or ticket.
--
--   ALTER USER DAKSHA ADD PROGRAMMATIC ACCESS TOKEN SAARTHI_MCP_PAT
--       ROLE_RESTRICTION = 'SAARTHI_MCP_CLIENT'
--       DAYS_TO_EXPIRY = 30
--       COMMENT = 'SAARTHI MCP client - least-privileged, expires in 30 days';
--
-- Verify with:
--   SHOW USER PROGRAMMATIC ACCESS TOKENS FOR USER DAKSHA;
--
-- Rotate via `ALTER USER ... ROTATE ...` before the 30-day mark. Revoke
-- immediately if the laptop holding the secret is ever lost.
