-- =============================================================================
-- STEP 19c - Procedure, agent and MCP grants (least privilege)
-- =============================================================================
-- Runs after steps 14-19b, because a GRANT on a procedure, agent or MCP
-- server fails if the object does not exist yet (the reason these cannot live
-- in 03_grants.sql at step 9).
--
-- SAARTHI_APP gets USAGE on its entry points and the agent's tools, and
-- nothing else. Deliberately absent: EVALUATE_GATES, REFRESH_READINESS_PROC,
-- CLASSIFY_QUESTION, VALIDATE_ANSWER and every task body. Those run as owner
-- from inside the entry points; granting them directly would let a caller
-- pass any patient id to EVALUATE_GATES and bypass binding, care team and
-- consent (R5).
--
-- Every tool procedure is EXECUTE AS OWNER and re-checks the session's patient
-- binding, care-team membership and consent itself; USAGE is the entry key,
-- not the authorisation.
--
-- Idempotent on an account that still carries the old blanket grants: they
-- are revoked first.

REVOKE USAGE ON ALL PROCEDURES IN SCHEMA SAARTHI.OPERATIONAL FROM ROLE SAARTHI_APP;
REVOKE USAGE ON FUTURE PROCEDURES IN SCHEMA SAARTHI.OPERATIONAL FROM ROLE SAARTHI_APP;

-- Entry points the apps call.
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.BIND_PATIENT(VARCHAR)                        TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.ASK_SAARTHI(VARCHAR)                         TO ROLE SAARTHI_APP;
-- The agent's eight tools (called inside the caller's session).
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_PATIENT_FACTS(VARCHAR, VARCHAR)          TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_READINESS(VARCHAR, VARCHAR)              TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.SEARCH_PATIENT_DOCUMENTS(VARCHAR, VARCHAR)   TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.SEARCH_REFERENCE_DOCUMENTS(VARCHAR, VARCHAR, VARCHAR) TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.COHORT_QUERY(VARCHAR)                        TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_TIMELINE(VARCHAR)                        TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.GET_CHANGES(VARCHAR, VARCHAR)                TO ROLE SAARTHI_APP;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.CREATE_REVIEW_TASK(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE SAARTHI_APP;

-- Agent and MCP server. USAGE on the MCP server does not confer USAGE on the
-- tools behind it (Snowflake docs), so both are needed for an MCP caller.
GRANT USAGE ON AGENT SAARTHI.OPERATIONAL.SAARTHI_AGENT        TO ROLE SAARTHI_APP;
GRANT USAGE ON MCP SERVER SAARTHI.OPERATIONAL.SAARTHI_MCP     TO ROLE SAARTHI_APP;

-- Judge Console probes: the judge role, and only the probes.
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_01_CROSS_SCOPE()          TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_02_SEARCH_LEAK()          TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_03_CONSENT_REVOKED()      TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_04_PROMPT_INJECTION()     TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_05_FABRICATED_CLAIM()     TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_06_TWO_PASS_DISAGREEMENT() TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_07_TIME_TRAVEL()          TO ROLE SAARTHI_JUDGE;
GRANT USAGE ON PROCEDURE SAARTHI.OPERATIONAL.JUDGE_PROBE_08_BASELINE_DELTA()       TO ROLE SAARTHI_JUDGE;
